# Generated by Django 5.2.17 on 2026-08-27 09:20

import apps.supplier_quotes.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0021_split_manage_items'),
        ('organizations', '0007_accesschangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierQuote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('supplier_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('quote_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical supplier quote',
                'verbose_name_plural': 'historical supplier quotes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('quote_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_independent_supplier_quotes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='independent_supplier_quotes', to='organizations.organization')),
            ],
            options={
                'ordering': ['-quote_date', '-id'],
                'permissions': [('download_supplier_quote_attachment', 'Can download supplier quotation attachments')],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(upload_to=apps.supplier_quotes.models.quote_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supplier_quotes.supplierquote')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_supplier_quote_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=21)),
                ('line_total', models.DecimalField(decimal_places=3, max_digits=21)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='independent_supplier_quote_lines', to='inventory.inventoryitem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_quotes.supplierquote')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='independent_supplier_quote_lines', to='inventory.packageunit')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierquote',
            constraint=models.CheckConstraint(condition=models.Q(('supplier_name', ''), _negated=True), name='supplier_quote_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'sequence'), name='supplier_quote_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supplier_quote_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquoteline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='supplier_quote_line_unit_price_nonnegative'),
        ),
    ]
