# Generated by Django 5.2.17 on 2026-08-19 00:13

import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_sales_account_roles'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('sales', '0002_menu_price_no_overlap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('commission_percent', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='commission percent')),
                ('fixed_fee_per_order', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='fixed fee per order')),
                ('commission_basis', models.CharField(choices=[('GROSS_LIST_AMOUNT', 'إجمالي السعر المعلن'), ('AFTER_RESTAURANT_DISCOUNT', 'بعد خصم المطعم'), ('AFTER_ALL_DISCOUNTS', 'بعد كل الخصومات'), ('CUSTOMER_PAID_AMOUNT', 'المبلغ المدفوع من الزبون')], default='GROSS_LIST_AMOUNT', max_length=32, verbose_name='commission basis')),
                ('settlement_lag_days', models.PositiveSmallIntegerField(default=30, verbose_name='settlement lag (days)')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
            ],
            options={
                'verbose_name': 'delivery agreement',
                'verbose_name_plural': 'delivery agreements',
                'ordering': ['delivery_application__code', 'branch__code', '-effective_from'],
                'permissions': [('manage_sales_agreements', 'Can create and end delivery agreements')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('settlement_cycle_days', models.PositiveSmallIntegerField(default=30, verbose_name='settlement cycle (days)')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='contact person')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
            ],
            options={
                'verbose_name': 'delivery application',
                'verbose_name_plural': 'delivery applications',
                'ordering': ['organization__code', 'code'],
                'permissions': [('manage_delivery_applications', 'Can create, edit and archive delivery applications'), ('view_application_receivables', 'Can view delivery application receivables'), ('manage_application_settlements', 'Can create, reconcile, post and reverse application settlements')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryApplicationBranchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('external_store_code', models.CharField(blank=True, max_length=64, verbose_name='store code')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'delivery application branch setting',
                'verbose_name_plural': 'delivery application branch settings',
                'ordering': ['delivery_application__code', 'branch__code'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='discount percent')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='discount amount')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='maximum amount')),
                ('restaurant_funded_share', models.DecimalField(decimal_places=6, default=Decimal('100'), max_digits=12, verbose_name='restaurant-funded share (%)')),
                ('application_funded_share', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='application-funded share (%)')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
            ],
            options={
                'verbose_name': 'discount program',
                'verbose_name_plural': 'discount programs',
                'ordering': ['organization__code', 'code'],
                'permissions': [('manage_sales_discounts', 'Can create and end discount programs')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryAgreement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('commission_percent', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='commission percent')),
                ('fixed_fee_per_order', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='fixed fee per order')),
                ('commission_basis', models.CharField(choices=[('GROSS_LIST_AMOUNT', 'إجمالي السعر المعلن'), ('AFTER_RESTAURANT_DISCOUNT', 'بعد خصم المطعم'), ('AFTER_ALL_DISCOUNTS', 'بعد كل الخصومات'), ('CUSTOMER_PAID_AMOUNT', 'المبلغ المدفوع من الزبون')], default='GROSS_LIST_AMOUNT', max_length=32, verbose_name='commission basis')),
                ('settlement_lag_days', models.PositiveSmallIntegerField(default=30, verbose_name='settlement lag (days)')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical delivery agreement',
                'verbose_name_plural': 'historical delivery agreements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('settlement_cycle_days', models.PositiveSmallIntegerField(default=30, verbose_name='settlement cycle (days)')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='contact person')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical delivery application',
                'verbose_name_plural': 'historical delivery applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryApplicationBranchSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('external_store_code', models.CharField(blank=True, max_length=64, verbose_name='store code')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical delivery application branch setting',
                'verbose_name_plural': 'historical delivery application branch settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiscountProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='discount percent')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='discount amount')),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='maximum amount')),
                ('restaurant_funded_share', models.DecimalField(decimal_places=6, default=Decimal('100'), max_digits=12, verbose_name='restaurant-funded share (%)')),
                ('application_funded_share', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12, verbose_name='application-funded share (%)')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical discount program',
                'verbose_name_plural': 'historical discount programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='menupriceversion',
            name='sales_menu_price_application_scope_not_yet_available',
        ),
        migrations.AddField(
            model_name='deliveryagreement',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_agreements', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='deliveryagreement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_agreements', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='deliveryapplication',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_applications', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='deliveryapplication',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_application_overrides', to='accounting.account', verbose_name='receivable account override'),
        ),
        migrations.AddField(
            model_name='deliveryagreement',
            name='delivery_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='historicalmenupriceversion',
            name='delivery_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='menupriceversion',
            name='delivery_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_prices', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddConstraint(
            model_name='menupriceversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_application__isnull', False), ('scope', 'APPLICATION')), models.Q(models.Q(('scope', 'APPLICATION'), _negated=True), ('delivery_application__isnull', True)), _connector='OR'), name='sales_menu_price_application_matches_scope'),
        ),
        migrations.AddField(
            model_name='deliveryapplicationbranchsetting',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_application_settings', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='deliveryapplicationbranchsetting',
            name='delivery_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_programs', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_programs', to='sales.saleschannel', verbose_name='channel'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='delivery_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_programs', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_programs', to='sales.menuitem', verbose_name='menu item'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_programs', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryagreement',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryagreement',
            name='delivery_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryagreement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliveryagreement',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryapplication',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliveryapplication',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryapplication',
            name='receivable_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='receivable account override'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryapplicationbranchsetting',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryapplicationbranchsetting',
            name='delivery_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='historicaldeliveryapplicationbranchsetting',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldiscountprogram',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicaldiscountprogram',
            name='channel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleschannel', verbose_name='channel'),
        ),
        migrations.AddField(
            model_name='historicaldiscountprogram',
            name='delivery_application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplication', verbose_name='delivery application'),
        ),
        migrations.AddField(
            model_name='historicaldiscountprogram',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldiscountprogram',
            name='menu_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.menuitem', verbose_name='menu item'),
        ),
        migrations.AddField(
            model_name='historicaldiscountprogram',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplication',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='sales_delivery_application_code_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplication',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9._-]*$')), name='sales_delivery_application_code_format'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplication',
            constraint=models.CheckConstraint(condition=models.Q(('name_ar', ''), _negated=True), name='sales_delivery_application_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='deliveryagreement',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__gte', Decimal('0')), ('commission_percent__lte', Decimal('100'))), name='sales_agreement_percent_in_range'),
        ),
        migrations.AddConstraint(
            model_name='deliveryagreement',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_fee_per_order__gte', Decimal('0'))), name='sales_agreement_fee_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='deliveryagreement',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='sales_agreement_range_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationbranchsetting',
            constraint=models.UniqueConstraint(fields=('delivery_application', 'branch'), name='sales_delivery_application_branch_unique'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='sales_discount_code_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9._-]*$')), name='sales_discount_code_format'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('name_ar', ''), _negated=True), name='sales_discount_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_amount__isnull', True), ('discount_percent__isnull', False)), models.Q(('discount_amount__isnull', False), ('discount_percent__isnull', True)), _connector='OR'), name='sales_discount_percent_xor_amount'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gt', Decimal('0')), ('discount_percent__lte', Decimal('100'))), _connector='OR'), name='sales_discount_percent_in_range'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__isnull', True), ('discount_amount__gt', Decimal('0')), _connector='OR'), name='sales_discount_amount_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_amount__isnull', True), ('maximum_amount__gt', Decimal('0')), _connector='OR'), name='sales_discount_maximum_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('restaurant_funded_share', django.db.models.expressions.CombinedExpression(models.Value(Decimal('100')), '-', models.F('application_funded_share')))), name='sales_discount_funding_shares_close'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('restaurant_funded_share__gte', Decimal('0')), ('restaurant_funded_share__lte', Decimal('100'))), name='sales_discount_restaurant_share_in_range'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('application_funded_share__gte', Decimal('0')), ('application_funded_share__lte', Decimal('100'))), name='sales_discount_application_share_in_range'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('application_funded_share', Decimal('0')), ('delivery_application__isnull', False), _connector='OR'), name='sales_discount_application_funding_names_an_application'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='sales_discount_range_is_ordered'),
        ),
    ]
