# Generated by Django 5.2.17 on 2026-08-19 01:16

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('sales', '0006_sales_day_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalesAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('reason_kind', models.CharField(choices=[('CANCELLED_BEFORE_FULFILLMENT', 'إلغاء قبل التنفيذ'), ('RETURNED_AFTER_FULFILLMENT', 'إرجاع بعد التنفيذ'), ('FINANCIAL_CORRECTION', 'تصحيح مالي')], max_length=32, verbose_name='reason kind')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=12, verbose_name='status')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('reason', models.TextField(verbose_name='reason')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(blank=True, max_length=128, verbose_name='request fingerprint')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('sales_day', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesday', verbose_name='sales day')),
            ],
            options={
                'verbose_name': 'historical sales adjustment',
                'verbose_name_plural': 'historical sales adjustments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('reason_kind', models.CharField(choices=[('CANCELLED_BEFORE_FULFILLMENT', 'إلغاء قبل التنفيذ'), ('RETURNED_AFTER_FULFILLMENT', 'إرجاع بعد التنفيذ'), ('FINANCIAL_CORRECTION', 'تصحيح مالي')], max_length=32, verbose_name='reason kind')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=12, verbose_name='status')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('reason', models.TextField(verbose_name='reason')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(blank=True, max_length=128, verbose_name='request fingerprint')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_adjustments', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_adjustments', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_adjustments_posted', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_adjustments_reversed', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('sales_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='sales.salesday', verbose_name='sales day')),
            ],
            options={
                'verbose_name': 'sales adjustment',
                'verbose_name_plural': 'sales adjustments',
                'ordering': ['-business_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesAdjustmentLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('adjusted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='adjusted quantity')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit price')),
                ('adjusted_gross', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='adjusted gross')),
                ('adjusted_restaurant_discount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted restaurant-funded discount')),
                ('adjusted_application_discount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted application-funded discount')),
                ('adjusted_commission', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted commission')),
                ('adjusted_other_fees', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted other application fees')),
                ('adjusted_customer_charge', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='adjusted customer charge')),
                ('adjusted_net_amount', models.DecimalField(decimal_places=3, help_text='Cash or card taken back, or the receivable credited.', max_digits=21, verbose_name='adjusted net amount')),
                ('line_reason', models.CharField(blank=True, max_length=300, verbose_name='line reason')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesdayline', verbose_name='original line')),
                ('adjustment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesadjustment', verbose_name='adjustment')),
            ],
            options={
                'verbose_name': 'historical sales adjustment line',
                'verbose_name_plural': 'historical sales adjustment lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('adjusted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='adjusted quantity')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit price')),
                ('adjusted_gross', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='adjusted gross')),
                ('adjusted_restaurant_discount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted restaurant-funded discount')),
                ('adjusted_application_discount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted application-funded discount')),
                ('adjusted_commission', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted commission')),
                ('adjusted_other_fees', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='adjusted other application fees')),
                ('adjusted_customer_charge', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='adjusted customer charge')),
                ('adjusted_net_amount', models.DecimalField(decimal_places=3, help_text='Cash or card taken back, or the receivable credited.', max_digits=21, verbose_name='adjusted net amount')),
                ('line_reason', models.CharField(blank=True, max_length=300, verbose_name='line reason')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesadjustment', verbose_name='adjustment')),
                ('original_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='sales.salesdayline', verbose_name='original line')),
            ],
            options={
                'verbose_name': 'sales adjustment line',
                'verbose_name_plural': 'sales adjustment lines',
                'ordering': ['adjustment', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('number', ''), ('status', 'DRAFT')), models.Q(('status__in', ['POSTED', 'REVERSED']), models.Q(('number', ''), _negated=True)), _connector='OR'), name='sales_adjustment_number_iff_posted'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='sales_adjustment_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('posted_by__isnull', True)), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False)), _connector='OR'), name='sales_adjustment_posting_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversed_at__isnull', False), ('status', 'REVERSED')), models.Q(models.Q(('status', 'REVERSED'), _negated=True), ('reversed_at__isnull', True)), _connector='OR'), name='sales_adjustment_reversal_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_reason', ''), _negated=True), _connector='OR'), name='sales_adjustment_reversal_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='sales_adjustment_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_reference', ''), _negated=True), name='sales_adjustment_has_evidence'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustmentline',
            constraint=models.UniqueConstraint(fields=('adjustment', 'sequence'), name='sales_adjustment_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustmentline',
            constraint=models.UniqueConstraint(fields=('adjustment', 'original_line'), name='sales_adjustment_line_one_row_per_original'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_quantity__gte', Decimal('0'))), name='sales_adjustment_line_quantity_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_gross__gt', Decimal('0'))), name='sales_adjustment_line_gross_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('adjusted_restaurant_discount__gte', Decimal('0')), ('adjusted_application_discount__gte', Decimal('0')), ('adjusted_commission__gte', Decimal('0')), ('adjusted_other_fees__gte', Decimal('0')), ('adjusted_customer_charge__gte', Decimal('0'))), name='sales_adjustment_line_amounts_are_not_negative'),
        ),
    ]
