# Generated by Django 5.2.17 on 2026-08-19 02:32

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('sales', '0008_sales_adjustment_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryApplicationSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('statement_reference', models.CharField(max_length=200, verbose_name='statement reference')),
                ('statement_date', models.DateField(verbose_name='statement date')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('RECONCILED', 'مطابق'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=12, verbose_name='status')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('expected_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='expected amount')),
                ('statement_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='statement amount')),
                ('remitted_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='remitted amount')),
                ('statement_commission_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Compared against the accrual made at the sale. Never expensed again.', max_digits=21, verbose_name='statement commission')),
                ('remittance_destination', models.CharField(choices=[('BANK', 'مصرف'), ('CASH', 'نقد')], default='BANK', max_length=8, verbose_name='remittance destination')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='reconciled at')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(blank=True, max_length=128, verbose_name='request fingerprint')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_settlements', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_settlements_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('delivery_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='sales.deliveryapplication', verbose_name='delivery application')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_settlements', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_settlements_posted', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_settlements_reconciled', to=settings.AUTH_USER_MODEL, verbose_name='reconciled by')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_settlements_reversed', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
            ],
            options={
                'verbose_name': 'delivery application settlement',
                'verbose_name_plural': 'delivery application settlements',
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryApplicationSettlementAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('leg', models.CharField(choices=[('STATEMENT', 'فرق كشف الحساب'), ('REMITTANCE', 'فرق التحويل')], max_length=12, verbose_name='leg')),
                ('reason', models.CharField(choices=[('COMMISSION_RATE_DIFFERENCE', 'فرق نسبة العمولة'), ('PROMOTION_FUNDING_DIFFERENCE', 'فرق تمويل العروض'), ('CANCELLED_ORDER_NOT_CREDITED', 'طلب ملغى غير مُعاد'), ('PENALTY_OR_CHARGEBACK', 'غرامة أو استرداد'), ('WITHHOLDING_OR_OFFSET', 'حجز أو مقاصة'), ('ROUNDING', 'تقريب'), ('UNEXPLAINED_APPROVED', 'فرق غير مفسّر معتمد')], max_length=40, verbose_name='reason')),
                ('amount', models.DecimalField(decimal_places=3, help_text='Signed: positive means the restaurant received less than promised.', max_digits=21, verbose_name='amount')),
                ('explanation', models.CharField(blank=True, max_length=300, verbose_name='explanation')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_adjustments_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='sales.deliveryapplicationsettlement', verbose_name='settlement')),
            ],
            options={
                'verbose_name': 'settlement adjustment',
                'verbose_name_plural': 'settlement adjustments',
                'ordering': ['settlement', 'leg', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryApplicationSettlementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated amount')),
                ('receivable_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='sales.applicationreceivableentry', verbose_name='receivable entry')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.deliveryapplicationsettlement', verbose_name='settlement')),
            ],
            options={
                'verbose_name': 'settlement allocation',
                'verbose_name_plural': 'settlement allocations',
                'ordering': ['settlement', 'receivable_entry__business_date', 'receivable_entry_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryApplicationSettlement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('statement_reference', models.CharField(max_length=200, verbose_name='statement reference')),
                ('statement_date', models.DateField(verbose_name='statement date')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('RECONCILED', 'مطابق'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=12, verbose_name='status')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('expected_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='expected amount')),
                ('statement_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='statement amount')),
                ('remitted_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='remitted amount')),
                ('statement_commission_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Compared against the accrual made at the sale. Never expensed again.', max_digits=21, verbose_name='statement commission')),
                ('remittance_destination', models.CharField(choices=[('BANK', 'مصرف'), ('CASH', 'نقد')], default='BANK', max_length=8, verbose_name='remittance destination')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='reconciled at')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(blank=True, max_length=128, verbose_name='request fingerprint')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('delivery_application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplication', verbose_name='delivery application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reconciled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reconciled by')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
            ],
            options={
                'verbose_name': 'historical delivery application settlement',
                'verbose_name_plural': 'historical delivery application settlements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryApplicationSettlementAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('leg', models.CharField(choices=[('STATEMENT', 'فرق كشف الحساب'), ('REMITTANCE', 'فرق التحويل')], max_length=12, verbose_name='leg')),
                ('reason', models.CharField(choices=[('COMMISSION_RATE_DIFFERENCE', 'فرق نسبة العمولة'), ('PROMOTION_FUNDING_DIFFERENCE', 'فرق تمويل العروض'), ('CANCELLED_ORDER_NOT_CREDITED', 'طلب ملغى غير مُعاد'), ('PENALTY_OR_CHARGEBACK', 'غرامة أو استرداد'), ('WITHHOLDING_OR_OFFSET', 'حجز أو مقاصة'), ('ROUNDING', 'تقريب'), ('UNEXPLAINED_APPROVED', 'فرق غير مفسّر معتمد')], max_length=40, verbose_name='reason')),
                ('amount', models.DecimalField(decimal_places=3, help_text='Signed: positive means the restaurant received less than promised.', max_digits=21, verbose_name='amount')),
                ('explanation', models.CharField(blank=True, max_length=300, verbose_name='explanation')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplicationsettlement', verbose_name='settlement')),
            ],
            options={
                'verbose_name': 'historical settlement adjustment',
                'verbose_name_plural': 'historical settlement adjustments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryApplicationSettlementAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivable_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.applicationreceivableentry', verbose_name='receivable entry')),
                ('settlement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.deliveryapplicationsettlement', verbose_name='settlement')),
            ],
            options={
                'verbose_name': 'historical settlement allocation',
                'verbose_name_plural': 'historical settlement allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='sales_settlement_period_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.UniqueConstraint(fields=('delivery_application', 'statement_reference'), name='sales_settlement_statement_unique_per_application'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('number', ''), ('status__in', ['DRAFT', 'RECONCILED'])), models.Q(('status__in', ['POSTED', 'REVERSED']), models.Q(('number', ''), _negated=True)), _connector='OR'), name='sales_settlement_number_iff_posted'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='sales_settlement_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gte', Decimal('0')), ('statement_amount__gte', Decimal('0')), ('remitted_amount__gte', Decimal('0')), ('statement_commission_amount__gte', Decimal('0'))), name='sales_settlement_amounts_are_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reconciled_at__isnull', True), ('reconciled_by__isnull', True)), models.Q(('reconciled_at__isnull', False), ('reconciled_by__isnull', False)), _connector='OR'), name='sales_settlement_reconciliation_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('posted_by__isnull', True)), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False)), _connector='OR'), name='sales_settlement_posting_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversed_at__isnull', False), ('status', 'REVERSED')), models.Q(models.Q(('status', 'REVERSED'), _negated=True), ('reversed_at__isnull', True)), _connector='OR'), name='sales_settlement_reversal_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_reason', ''), _negated=True), _connector='OR'), name='sales_settlement_reversal_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('statement_reference', ''), _negated=True), name='sales_settlement_has_a_statement_reference'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_reference', ''), _negated=True), name='sales_settlement_has_evidence'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlementadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('0')), _negated=True), name='sales_settlement_adjustment_is_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlementadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='sales_settlement_adjustment_approval_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlementadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', 'UNEXPLAINED_APPROVED'), _negated=True), models.Q(('explanation', ''), _negated=True), _connector='OR'), name='sales_settlement_adjustment_unexplained_needs_words'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlementadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reason', 'UNEXPLAINED_APPROVED'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='sales_settlement_adjustment_unexplained_needs_an_approver'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlementallocation',
            constraint=models.UniqueConstraint(fields=('settlement', 'receivable_entry'), name='sales_settlement_allocation_unique_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='deliveryapplicationsettlementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', Decimal('0'))), name='sales_settlement_allocation_is_positive'),
        ),
    ]
