# Generated by Django 5.2.17 on 2026-08-19 03:05

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('sales', '0010_application_settlement_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مُغلق'), ('APPROVED', 'معتمد'), ('REVERSED', 'معكوس')], default='OPEN', max_length=12, verbose_name='status')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('opening_float', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='opening float')),
                ('expected_cash', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='expected cash')),
                ('counted_cash', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='counted cash')),
                ('variance_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='variance')),
                ('opened_at', models.DateTimeField(verbose_name='opened at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(blank=True, max_length=128, verbose_name='request fingerprint')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='organizations.branch', verbose_name='branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL, verbose_name='cashier')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts_closed', to=settings.AUTH_USER_MODEL, verbose_name='closed by')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts_opened', to=settings.AUTH_USER_MODEL, verbose_name='opened by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='organizations.organization', verbose_name='organization')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts_reversed', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('sales_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='sales.salesday', verbose_name='sales day')),
            ],
            options={
                'verbose_name': 'cashier shift',
                'verbose_name_plural': 'cashier shifts',
                'ordering': ['-business_date', 'branch__code'],
            },
        ),
        migrations.CreateModel(
            name='CashierTenderCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tender', models.CharField(choices=[('CASH', 'نقد'), ('CARD', 'بطاقة'), ('APPLICATION_RECEIVABLE', 'ذمة تطبيق')], max_length=24, verbose_name='tender')),
                ('expected_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='expected amount')),
                ('counted_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='counted amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_counts', to='sales.cashiershift', verbose_name='shift')),
            ],
            options={
                'verbose_name': 'cashier tender count',
                'verbose_name_plural': 'cashier tender counts',
                'ordering': ['shift', 'tender'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCashierShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('CLOSED', 'مُغلق'), ('APPROVED', 'معتمد'), ('REVERSED', 'معكوس')], default='OPEN', max_length=12, verbose_name='status')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('opening_float', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='opening float')),
                ('expected_cash', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='expected cash')),
                ('counted_cash', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='counted cash')),
                ('variance_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='variance')),
                ('opened_at', models.DateTimeField(verbose_name='opened at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('idempotency_key', models.CharField(blank=True, max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(blank=True, max_length=128, verbose_name='request fingerprint')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('cashier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cashier')),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='closed by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='opened by')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('sales_day', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesday', verbose_name='sales day')),
            ],
            options={
                'verbose_name': 'historical cashier shift',
                'verbose_name_plural': 'historical cashier shifts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashierTenderCount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('tender', models.CharField(choices=[('CASH', 'نقد'), ('CARD', 'بطاقة'), ('APPLICATION_RECEIVABLE', 'ذمة تطبيق')], max_length=24, verbose_name='tender')),
                ('expected_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='expected amount')),
                ('counted_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='counted amount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.cashiershift', verbose_name='shift')),
            ],
            options={
                'verbose_name': 'historical cashier tender count',
                'verbose_name_plural': 'historical cashier tender counts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(fields=('branch', 'business_date'), name='sales_shift_unique_per_branch_and_date'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('closed_by')), _negated=True), _connector='OR'), name='sales_shift_approver_is_not_the_closer'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True)), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False)), _connector='OR'), name='sales_shift_closing_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='sales_shift_approval_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversed_at__isnull', False), ('status', 'REVERSED')), models.Q(models.Q(('status', 'REVERSED'), _negated=True), ('reversed_at__isnull', True)), _connector='OR'), name='sales_shift_reversal_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_reason', ''), _negated=True), _connector='OR'), name='sales_shift_reversal_has_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('number', ''), ('status__in', ['OPEN', 'CLOSED'])), models.Q(('status__in', ['APPROVED', 'REVERSED']), models.Q(('number', ''), _negated=True)), _connector='OR'), name='sales_shift_number_iff_approved'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='sales_shift_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_float__gte', Decimal('0')), ('expected_cash__gte', Decimal('0')), ('counted_cash__gte', Decimal('0'))), name='sales_shift_amounts_are_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'OPEN'), ('sales_day__isnull', False), _connector='OR'), name='sales_shift_closed_names_its_day'),
        ),
        migrations.AddConstraint(
            model_name='cashiertendercount',
            constraint=models.UniqueConstraint(fields=('shift', 'tender'), name='sales_shift_tender_unique_per_shift'),
        ),
        migrations.AddConstraint(
            model_name='cashiertendercount',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gte', Decimal('0')), ('counted_amount__gte', Decimal('0'))), name='sales_shift_tender_amounts_are_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashiertendercount',
            constraint=models.CheckConstraint(condition=models.Q(('tender', 'APPLICATION_RECEIVABLE'), _negated=True), name='sales_shift_tender_is_countable'),
        ),
    ]
