# Generated by Django 5.2.17 on 2026-08-20 23:43

from decimal import Decimal

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def backfill_recipe_fulfillment(apps, schema_editor):
    """Freeze the route used by every line that predates direct-stock sales."""

    SalesDayLine = apps.get_model("sales", "SalesDayLine")
    HistoricalSalesDayLine = apps.get_model("sales", "HistoricalSalesDayLine")

    SalesDayLine.objects.filter(fulfillment_source__isnull=True).update(
        fulfillment_source="RECIPE_SERVING"
    )
    HistoricalSalesDayLine.objects.filter(fulfillment_source__isnull=True).update(
        fulfillment_source="RECIPE_SERVING"
    )


MENU_BRANCH_SOURCE_GUARDS = """
CREATE OR REPLACE FUNCTION sales_menu_branch_source_is_consistent()
RETURNS TRIGGER AS $$
DECLARE
    item_route text;
    warehouse_branch_id bigint;
BEGIN
    SELECT fulfillment_source
      INTO STRICT item_route
      FROM sales_menuitem
     WHERE id = NEW.menu_item_id;

    IF item_route = 'DIRECT_STOCK' AND NEW.source_warehouse_id IS NULL THEN
        RAISE EXCEPTION
            'a direct-stock menu setting requires a source warehouse'
            USING ERRCODE = 'check_violation';
    ELSIF item_route = 'RECIPE_SERVING' AND NEW.source_warehouse_id IS NOT NULL THEN
        RAISE EXCEPTION
            'a recipe-served menu setting may not name a source warehouse'
            USING ERRCODE = 'check_violation';
    END IF;

    IF NEW.source_warehouse_id IS NOT NULL THEN
        SELECT branch_id
          INTO STRICT warehouse_branch_id
          FROM inventory_warehouse
         WHERE id = NEW.source_warehouse_id;

        IF warehouse_branch_id IS DISTINCT FROM NEW.branch_id THEN
            RAISE EXCEPTION
                'a direct-stock source warehouse must belong to the selling branch'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER sales_menu_branch_source_is_consistent
    AFTER INSERT OR UPDATE ON sales_menuitembranchsetting
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION sales_menu_branch_source_is_consistent();

CREATE OR REPLACE FUNCTION sales_menu_route_settings_are_consistent()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM sales_menuitembranchsetting AS setting
         WHERE setting.menu_item_id = NEW.id
           AND (
                (NEW.fulfillment_source = 'DIRECT_STOCK'
                 AND setting.source_warehouse_id IS NULL)
                OR
                (NEW.fulfillment_source = 'RECIPE_SERVING'
                 AND setting.source_warehouse_id IS NOT NULL)
           )
    ) THEN
        RAISE EXCEPTION
            'menu item fulfillment route conflicts with an existing branch setting'
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER sales_menu_route_settings_are_consistent
    AFTER INSERT OR UPDATE ON sales_menuitem
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION sales_menu_route_settings_are_consistent();

CREATE OR REPLACE FUNCTION sales_warehouse_branch_keeps_menu_sources_consistent()
RETURNS TRIGGER AS $$
DECLARE
    current_branch_id bigint;
BEGIN
    SELECT branch_id
      INTO STRICT current_branch_id
      FROM inventory_warehouse
     WHERE id = NEW.id;

    IF EXISTS (
        SELECT 1
          FROM sales_menuitembranchsetting AS setting
         WHERE setting.source_warehouse_id = NEW.id
           AND setting.branch_id IS DISTINCT FROM current_branch_id
    ) THEN
        RAISE EXCEPTION
            'a warehouse used by direct-stock menu settings may not move to another branch'
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER sales_warehouse_branch_keeps_menu_sources_consistent
    AFTER UPDATE ON inventory_warehouse
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION sales_warehouse_branch_keeps_menu_sources_consistent();
"""

DROP_MENU_BRANCH_SOURCE_GUARDS = """
DROP TRIGGER IF EXISTS sales_warehouse_branch_keeps_menu_sources_consistent
    ON inventory_warehouse;
DROP FUNCTION IF EXISTS sales_warehouse_branch_keeps_menu_sources_consistent();
DROP TRIGGER IF EXISTS sales_menu_route_settings_are_consistent
    ON sales_menuitem;
DROP FUNCTION IF EXISTS sales_menu_route_settings_are_consistent();
DROP TRIGGER IF EXISTS sales_menu_branch_source_is_consistent
    ON sales_menuitembranchsetting;
DROP FUNCTION IF EXISTS sales_menu_branch_source_is_consistent();
"""

DIRECT_STOCK_EVIDENCE_GUARDS = """
CREATE OR REPLACE FUNCTION sales_direct_stock_evidence_is_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        '% is posted direct-stock evidence and may not be updated or deleted',
        TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sales_day_stock_posting_is_append_only
    BEFORE UPDATE OR DELETE ON sales_salesdaystockposting
    FOR EACH ROW EXECUTE FUNCTION sales_direct_stock_evidence_is_append_only();

CREATE TRIGGER sales_direct_stock_fulfillment_is_append_only
    BEFORE UPDATE OR DELETE ON sales_salesdirectstockfulfillment
    FOR EACH ROW EXECUTE FUNCTION sales_direct_stock_evidence_is_append_only();

CREATE TRIGGER sales_adjustment_stock_posting_is_append_only
    BEFORE UPDATE OR DELETE ON sales_salesadjustmentstockposting
    FOR EACH ROW EXECUTE FUNCTION sales_direct_stock_evidence_is_append_only();

CREATE TRIGGER sales_direct_stock_return_is_append_only
    BEFORE UPDATE OR DELETE ON sales_salesdirectstockreturnfulfillment
    FOR EACH ROW EXECUTE FUNCTION sales_direct_stock_evidence_is_append_only();
"""

DROP_DIRECT_STOCK_EVIDENCE_GUARDS = """
DROP TRIGGER IF EXISTS sales_day_stock_posting_is_append_only
    ON sales_salesdaystockposting;
DROP TRIGGER IF EXISTS sales_direct_stock_fulfillment_is_append_only
    ON sales_salesdirectstockfulfillment;
DROP TRIGGER IF EXISTS sales_adjustment_stock_posting_is_append_only
    ON sales_salesadjustmentstockposting;
DROP TRIGGER IF EXISTS sales_direct_stock_return_is_append_only
    ON sales_salesdirectstockreturnfulfillment;
DROP FUNCTION IF EXISTS sales_direct_stock_evidence_is_append_only();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0022_alter_accountrole_domain_and_more"),
        ("inventory", "0020_procurement_import_kinds"),
        ("kitchen", "0023_batch_document_link_guards"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        ("sales", "0013_reversal_and_correction_exclusion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSalesAdjustmentStockPosting",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sales adjustment stock posting",
                "verbose_name_plural": "historical sales adjustment stock postings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSalesDayStockPosting",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sales day stock posting",
                "verbose_name_plural": "historical sales day stock postings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSalesDirectStockFulfillment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="base quantity"
                    ),
                ),
                (
                    "cogs_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="cost of goods sold"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical direct stock fulfillment",
                "verbose_name_plural": "historical direct stock fulfillments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSalesDirectStockReturnFulfillment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="returned base quantity"
                    ),
                ),
                (
                    "cogs_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="returned cost of goods sold"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical direct stock return fulfillment",
                "verbose_name_plural": "historical direct stock return fulfillments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SalesAdjustmentStockPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "sales adjustment stock posting",
                "verbose_name_plural": "sales adjustment stock postings",
                "ordering": ["adjustment_id"],
            },
        ),
        migrations.CreateModel(
            name="SalesDayStockPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "sales day stock posting",
                "verbose_name_plural": "sales day stock postings",
                "ordering": ["sales_day_id"],
            },
        ),
        migrations.CreateModel(
            name="SalesDirectStockFulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="base quantity"
                    ),
                ),
                (
                    "cogs_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="cost of goods sold"
                    ),
                ),
            ],
            options={
                "verbose_name": "direct stock fulfillment",
                "verbose_name_plural": "direct stock fulfillments",
                "ordering": ["sales_line_id"],
            },
        ),
        migrations.CreateModel(
            name="SalesDirectStockReturnFulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="returned base quantity"
                    ),
                ),
                (
                    "cogs_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="returned cost of goods sold"
                    ),
                ),
            ],
            options={
                "verbose_name": "direct stock return fulfillment",
                "verbose_name_plural": "direct stock return fulfillments",
                "ordering": ["adjustment_line_id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="menuitem",
            name="sales_menu_item_recipe_serving_is_complete",
        ),
        migrations.RemoveConstraint(
            model_name="menuitem",
            name="sales_menu_item_direct_stock_is_deferred",
        ),
        migrations.AddField(
            model_name="historicalmenuitem",
            name="direct_stock_base_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=21,
                null=True,
                verbose_name="direct stock base quantity",
            ),
        ),
        migrations.AddField(
            model_name="historicalmenuitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.inventoryitem",
                verbose_name="direct stock item",
            ),
        ),
        migrations.AddField(
            model_name="historicalmenuitembranchsetting",
            name="source_warehouse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.warehouse",
                verbose_name="source warehouse",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesadjustment",
            name="direct_stock_disposition",
            field=models.CharField(
                choices=[
                    ("NOT_APPLICABLE", "لا ينطبق"),
                    ("RESTOCK", "إرجاع إلى المخزون"),
                    ("NO_RESTOCK", "لا يعاد إلى المخزون"),
                ],
                default="NOT_APPLICABLE",
                max_length=16,
                verbose_name="direct stock disposition",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdayline",
            name="direct_stock_qty_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=21,
                null=True,
                verbose_name="direct stock quantity per sold unit",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdayline",
            name="direct_stock_total_base_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=18,
                null=True,
                verbose_name="direct stock total base quantity",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdayline",
            name="fulfillment_source",
            field=models.CharField(
                choices=[("RECIPE_SERVING", "حصة من وصفة"), ("DIRECT_STOCK", "صنف مخزني مباشر")],
                max_length=16,
                null=True,
                verbose_name="fulfillment source",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdayline",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.inventoryitem",
                verbose_name="direct stock item",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdayline",
            name="source_warehouse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.warehouse",
                verbose_name="source warehouse",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="direct_stock_base_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=21,
                null=True,
                verbose_name="direct stock base quantity",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_menu_items",
                to="inventory.inventoryitem",
                verbose_name="direct stock item",
            ),
        ),
        migrations.AddField(
            model_name="menuitembranchsetting",
            name="source_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_menu_settings",
                to="inventory.warehouse",
                verbose_name="source warehouse",
            ),
        ),
        migrations.AddField(
            model_name="salesadjustment",
            name="direct_stock_disposition",
            field=models.CharField(
                choices=[
                    ("NOT_APPLICABLE", "لا ينطبق"),
                    ("RESTOCK", "إرجاع إلى المخزون"),
                    ("NO_RESTOCK", "لا يعاد إلى المخزون"),
                ],
                default="NOT_APPLICABLE",
                max_length=16,
                verbose_name="direct stock disposition",
            ),
        ),
        migrations.AddField(
            model_name="salesdayline",
            name="direct_stock_qty_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=21,
                null=True,
                verbose_name="direct stock quantity per sold unit",
            ),
        ),
        migrations.AddField(
            model_name="salesdayline",
            name="direct_stock_total_base_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=18,
                null=True,
                verbose_name="direct stock total base quantity",
            ),
        ),
        migrations.AddField(
            model_name="salesdayline",
            name="fulfillment_source",
            field=models.CharField(
                choices=[("RECIPE_SERVING", "حصة من وصفة"), ("DIRECT_STOCK", "صنف مخزني مباشر")],
                max_length=16,
                null=True,
                verbose_name="fulfillment source",
            ),
        ),
        migrations.AddField(
            model_name="salesdayline",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_sales_lines",
                to="inventory.inventoryitem",
                verbose_name="direct stock item",
            ),
        ),
        migrations.AddField(
            model_name="salesdayline",
            name="source_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_sales_lines",
                to="inventory.warehouse",
                verbose_name="source warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="salesdayline",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_lines",
                to="kitchen.recipe",
                verbose_name="recipe",
            ),
        ),
        migrations.AlterField(
            model_name="salesdayline",
            name="recipe_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_lines",
                to="kitchen.recipeversion",
                verbose_name="recipe version",
            ),
        ),
        migrations.AlterField(
            model_name="salesdayline",
            name="serving",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_lines",
                to="kitchen.recipeserving",
                verbose_name="serving",
            ),
        ),
        migrations.RunPython(
            backfill_recipe_fulfillment,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="historicalsalesdayline",
            name="fulfillment_source",
            field=models.CharField(
                choices=[("RECIPE_SERVING", "حصة من وصفة"), ("DIRECT_STOCK", "صنف مخزني مباشر")],
                max_length=16,
                verbose_name="fulfillment source",
            ),
        ),
        migrations.AlterField(
            model_name="salesdayline",
            name="fulfillment_source",
            field=models.CharField(
                choices=[("RECIPE_SERVING", "حصة من وصفة"), ("DIRECT_STOCK", "صنف مخزني مباشر")],
                max_length=16,
                verbose_name="fulfillment source",
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direct_stock_base_quantity__isnull", True),
                        ("fulfillment_source", "RECIPE_SERVING"),
                        ("inventory_item__isnull", True),
                        ("recipe__isnull", False),
                        models.Q(("serving_code", ""), _negated=True),
                    ),
                    models.Q(
                        ("direct_stock_base_quantity__gt", Decimal("0")),
                        ("fulfillment_source", "DIRECT_STOCK"),
                        ("inventory_item__isnull", False),
                        ("recipe__isnull", True),
                        ("serving_code", ""),
                    ),
                    _connector="OR",
                ),
                name="sales_menu_item_fulfillment_route_is_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason_kind", "FINANCIAL_CORRECTION"), _negated=True),
                    ("direct_stock_disposition", "NOT_APPLICABLE"),
                    _connector="OR",
                ),
                name="sales_adjustment_financial_has_no_stock_disposition",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdayline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direct_stock_qty_per_unit__isnull", True),
                        ("direct_stock_total_base_qty__isnull", True),
                        ("fulfillment_source", "RECIPE_SERVING"),
                        ("inventory_item__isnull", True),
                        ("recipe__isnull", False),
                        ("recipe_version__isnull", False),
                        ("serving__isnull", False),
                        ("source_warehouse__isnull", True),
                    ),
                    models.Q(
                        ("direct_stock_qty_per_unit__gt", Decimal("0")),
                        ("direct_stock_total_base_qty__gt", Decimal("0")),
                        ("fulfillment_source", "DIRECT_STOCK"),
                        ("inventory_item__isnull", False),
                        ("recipe__isnull", True),
                        ("recipe_version__isnull", True),
                        ("serving__isnull", True),
                        ("source_warehouse__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sales_line_fulfillment_snapshot_is_complete",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesadjustmentstockposting",
            name="adjustment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sales.salesadjustment",
                verbose_name="sales adjustment",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesadjustmentstockposting",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesadjustmentstockposting",
            name="stock_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockledgerentry",
                verbose_name="stock ledger entry",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdaystockposting",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdaystockposting",
            name="sales_day",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sales.salesday",
                verbose_name="sales day",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdaystockposting",
            name="stock_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockledgerentry",
                verbose_name="stock ledger entry",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockfulfillment",
            name="consumption_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.account",
                verbose_name="consumption account",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockfulfillment",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.costcenter",
                verbose_name="cost center",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockfulfillment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockfulfillment",
            name="sales_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sales.salesdayline",
                verbose_name="sales line",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockfulfillment",
            name="stock_movement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockmovement",
                verbose_name="stock movement",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockreturnfulfillment",
            name="adjustment_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sales.salesadjustmentline",
                verbose_name="sales adjustment line",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockreturnfulfillment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockreturnfulfillment",
            name="stock_movement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockmovement",
                verbose_name="return stock movement",
            ),
        ),
        migrations.AddField(
            model_name="salesadjustmentstockposting",
            name="adjustment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_posting",
                to="sales.salesadjustment",
                verbose_name="sales adjustment",
            ),
        ),
        migrations.AddField(
            model_name="salesadjustmentstockposting",
            name="stock_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_adjustment_direct_stock_posting",
                to="inventory.stockledgerentry",
                verbose_name="stock ledger entry",
            ),
        ),
        migrations.AddField(
            model_name="salesdaystockposting",
            name="sales_day",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_posting",
                to="sales.salesday",
                verbose_name="sales day",
            ),
        ),
        migrations.AddField(
            model_name="salesdaystockposting",
            name="stock_entry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_day_direct_stock_posting",
                to="inventory.stockledgerentry",
                verbose_name="stock ledger entry",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockfulfillment",
            name="consumption_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_direct_stock_fulfillments",
                to="accounting.account",
                verbose_name="consumption account",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockfulfillment",
            name="cost_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_direct_stock_fulfillments",
                to="accounting.costcenter",
                verbose_name="cost center",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockfulfillment",
            name="sales_line",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_fulfillment",
                to="sales.salesdayline",
                verbose_name="sales line",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockfulfillment",
            name="stock_movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_direct_stock_fulfillment",
                to="inventory.stockmovement",
                verbose_name="stock movement",
            ),
        ),
        migrations.AddField(
            model_name="historicalsalesdirectstockreturnfulfillment",
            name="source_fulfillment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sales.salesdirectstockfulfillment",
                verbose_name="source fulfillment",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockreturnfulfillment",
            name="adjustment_line",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_stock_return_fulfillment",
                to="sales.salesadjustmentline",
                verbose_name="sales adjustment line",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockreturnfulfillment",
            name="source_fulfillment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_fulfillments",
                to="sales.salesdirectstockfulfillment",
                verbose_name="source fulfillment",
            ),
        ),
        migrations.AddField(
            model_name="salesdirectstockreturnfulfillment",
            name="stock_movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_direct_stock_return_fulfillment",
                to="inventory.stockmovement",
                verbose_name="return stock movement",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdirectstockfulfillment",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", Decimal("0"))),
                name="sales_direct_fulfillment_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdirectstockfulfillment",
            constraint=models.CheckConstraint(
                condition=models.Q(("cogs_value__gte", Decimal("0"))),
                name="sales_direct_fulfillment_cogs_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdirectstockreturnfulfillment",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity__gt", Decimal("0"))),
                name="sales_direct_return_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdirectstockreturnfulfillment",
            constraint=models.CheckConstraint(
                condition=models.Q(("cogs_value__gte", Decimal("0"))),
                name="sales_direct_return_cogs_nonnegative",
            ),
        ),
        migrations.RunSQL(
            sql=MENU_BRANCH_SOURCE_GUARDS,
            reverse_sql=DROP_MENU_BRANCH_SOURCE_GUARDS,
        ),
        migrations.RunSQL(
            sql=DIRECT_STOCK_EVIDENCE_GUARDS,
            reverse_sql=DROP_DIRECT_STOCK_EVIDENCE_GUARDS,
        ),
    ]
