# Generated by Django 5.2.17 on 2026-08-26 05:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


DAILY_CLOSE_GUARD = """
CREATE OR REPLACE FUNCTION sales_daily_financial_close_is_frozen()
RETURNS TRIGGER AS $$
DECLARE
    permitted sales_dailyfinancialclose%ROWTYPE;
BEGIN
    permitted := OLD;

    IF OLD.status IN ('BLOCKED', 'APPROVED') THEN
        IF NEW IS NOT DISTINCT FROM permitted THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION
            'a blocked or approved daily financial close is immutable; create a new attempt'
            USING ERRCODE = 'restrict_violation';
    END IF;

    -- A clean captured attempt may only record its independent review.  Every
    -- figure, exception and submitter remains the evidence the reviewer saw.
    permitted.status        := NEW.status;
    permitted.reviewed_by_id := NEW.reviewed_by_id;
    permitted.reviewed_at   := NEW.reviewed_at;
    permitted.updated_at    := NEW.updated_at;
    IF NEW.status <> 'APPROVED' THEN
        RAISE EXCEPTION
            'a submitted daily financial close may only become APPROVED'
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW IS NOT DISTINCT FROM permitted THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION
        'a submitted daily financial close is immutable except for its review evidence'
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sales_daily_financial_close_is_frozen
    BEFORE UPDATE ON sales_dailyfinancialclose
    FOR EACH ROW EXECUTE FUNCTION sales_daily_financial_close_is_frozen();

CREATE OR REPLACE FUNCTION sales_daily_financial_close_is_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'a daily financial close is audit evidence and may not be deleted'
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sales_daily_financial_close_is_append_only
    BEFORE DELETE ON sales_dailyfinancialclose
    FOR EACH ROW EXECUTE FUNCTION sales_daily_financial_close_is_append_only();
"""

DAILY_CLOSE_GUARD_DROP = """
DROP TRIGGER IF EXISTS sales_daily_financial_close_is_frozen ON sales_dailyfinancialclose;
DROP FUNCTION IF EXISTS sales_daily_financial_close_is_frozen();
DROP TRIGGER IF EXISTS sales_daily_financial_close_is_append_only ON sales_dailyfinancialclose;
DROP FUNCTION IF EXISTS sales_daily_financial_close_is_append_only();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_accesschangerequest'),
        ('sales', '0015_direct_stock_integrity_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFinancialClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='attempt number')),
                ('status', models.CharField(choices=[('SUBMITTED', 'بانتظار المراجعة'), ('BLOCKED', 'متوقف بسبب استثناءات'), ('APPROVED', 'معتمد')], max_length=12, verbose_name='status')),
                ('reconciliation_snapshot', models.JSONField(default=dict, verbose_name='reconciliation snapshot')),
                ('exception_count', models.PositiveSmallIntegerField(default=0, verbose_name='exception count')),
                ('submitted_at', models.DateTimeField(verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
            ],
            options={
                'verbose_name': 'daily financial close',
                'verbose_name_plural': 'daily financial closes',
                'ordering': ['-business_date', 'branch__code', '-attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDailyFinancialClose',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='attempt number')),
                ('status', models.CharField(choices=[('SUBMITTED', 'بانتظار المراجعة'), ('BLOCKED', 'متوقف بسبب استثناءات'), ('APPROVED', 'معتمد')], max_length=12, verbose_name='status')),
                ('reconciliation_snapshot', models.JSONField(default=dict, verbose_name='reconciliation snapshot')),
                ('exception_count', models.PositiveSmallIntegerField(default=0, verbose_name='exception count')),
                ('submitted_at', models.DateTimeField(verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical daily financial close',
                'verbose_name_plural': 'historical daily financial closes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='salesday',
            options={'ordering': ['-business_date', 'branch__code'], 'permissions': [('create_daily_sales', 'Can create and edit a draft sales day'), ('submit_daily_sales', 'Can submit a sales day for posting'), ('post_daily_sales', 'Can post a sales day to the ledger'), ('reverse_daily_sales', 'Can reverse a posted sales day'), ('manage_sales_adjustments', 'Can record returns and cancellations'), ('close_cashier_shift', 'Can open and close a cashier shift'), ('approve_cashier_closing', 'Can approve a cashier closing'), ('submit_daily_financial_close', 'Can submit a daily financial close for review'), ('approve_daily_financial_close', 'Can approve a daily financial close')], 'verbose_name': 'sales day', 'verbose_name_plural': 'sales days'},
        ),
        migrations.AddConstraint(
            model_name='salesday',
            constraint=models.CheckConstraint(condition=models.Q(('posted_by__isnull', True), ('submitted_by__isnull', True), models.Q(('posted_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='sales_day_poster_is_not_submitter'),
        ),
        migrations.AddField(
            model_name='dailyfinancialclose',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_financial_closes', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='dailyfinancialclose',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_financial_closes', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='dailyfinancialclose',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_financial_closes_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='dailyfinancialclose',
            name='sales_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_financial_closes', to='sales.salesday', verbose_name='sales day'),
        ),
        migrations.AddField(
            model_name='dailyfinancialclose',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_financial_closes_submitted', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='historicaldailyfinancialclose',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicaldailyfinancialclose',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldailyfinancialclose',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicaldailyfinancialclose',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='historicaldailyfinancialclose',
            name='sales_day',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesday', verbose_name='sales day'),
        ),
        migrations.AddField(
            model_name='historicaldailyfinancialclose',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddIndex(
            model_name='dailyfinancialclose',
            index=models.Index(fields=['branch', 'business_date'], name='sales_close_branch_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyfinancialclose',
            constraint=models.UniqueConstraint(fields=('sales_day', 'attempt_number'), name='sales_daily_close_attempt_unique_per_day'),
        ),
        migrations.AddConstraint(
            model_name='dailyfinancialclose',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='sales_daily_close_attempt_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='dailyfinancialclose',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='sales_daily_close_review_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='dailyfinancialclose',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='sales_daily_close_reviewer_is_not_submitter'),
        ),
        migrations.AddConstraint(
            model_name='dailyfinancialclose',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_by__isnull', False), ('status', 'APPROVED')), models.Q(('reviewed_by__isnull', True), ('status__in', ['SUBMITTED', 'BLOCKED'])), _connector='OR'), name='sales_daily_close_state_has_right_reviewer'),
        ),
        migrations.RunSQL(sql=DAILY_CLOSE_GUARD, reverse_sql=DAILY_CLOSE_GUARD_DROP),
    ]
