# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryapplication',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='discountprogram',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicaldeliveryapplication',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicaldiscountprogram',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalmenucategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalmenuitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalsaleschannel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='saleschannel',
            name='name_en',
        ),
    ]
