# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_alter_account_name_alter_accountrole_name_and_more'),
        ('inventory', '0029_remove_inventoryitem_inventory_item_name_ar_not_empty_and_more'),
        ('kitchen', '0027_remove_recipe_recipe_name_ar_not_empty_and_more'),
        ('organizations', '0011_alter_roledefinition_options'),
        ('sales', '0019_alter_deliveryapplication_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveryapplication',
            name='sales_delivery_application_name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='discountprogram',
            name='sales_discount_name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='menucategory',
            name='sales_menu_category_name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='sales_menu_item_name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='saleschannel',
            name='sales_channel_name_not_empty',
        ),
        migrations.AddConstraint(
            model_name='deliveryapplication',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='sales_delivery_application_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='discountprogram',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='sales_discount_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='sales_menu_category_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='sales_menu_item_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='saleschannel',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='sales_channel_name_not_empty'),
        ),
    ]
