# Generated by Django 5.2.17 on 2026-08-11 07:45

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='contact person')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, verbose_name='payment terms (days)')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='credit limit')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical supplier',
                'verbose_name_plural': 'historical suppliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='contact person')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, verbose_name='payment terms (days)')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='credit limit')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['organization__code', 'code'],
                'permissions': [('manage_suppliers', 'Can create, edit and archive suppliers'), ('view_supplier_cost', 'Can view supplier prices and amounts')],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='supplier_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='procurement_supplier_code_unique_per_organization'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9._-]*$')), name='procurement_supplier_code_format'), models.CheckConstraint(condition=models.Q(('name_ar', ''), _negated=True), name='procurement_supplier_name_ar_not_empty'), models.CheckConstraint(condition=models.Q(('credit_limit__isnull', True), ('credit_limit__gte', 0), _connector='OR'), name='procurement_supplier_credit_limit_not_negative')],
            },
        ),
    ]
