# Generated by Django 5.2.17 on 2026-08-11 15:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_task_1_7b_stock_locations'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('supplier_sku', models.CharField(blank=True, max_length=64, verbose_name='supplier reference')),
                ('supplier_description', models.CharField(blank=True, max_length=200, verbose_name='supplier description')),
                ('last_quoted_price', models.DecimalField(blank=True, decimal_places=6, help_text='Planning information only. Never used to value stock.', max_digits=21, null=True, verbose_name='last quoted price')),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='lead time (days)')),
                ('minimum_order_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='minimum order quantity')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='preferred')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('package_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.packageunit', verbose_name='purchase package')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'historical supplier item',
                'verbose_name_plural': 'historical supplier items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('supplier_sku', models.CharField(blank=True, max_length=64, verbose_name='supplier reference')),
                ('supplier_description', models.CharField(blank=True, max_length=200, verbose_name='supplier description')),
                ('last_quoted_price', models.DecimalField(blank=True, decimal_places=6, help_text='Planning information only. Never used to value stock.', max_digits=21, null=True, verbose_name='last quoted price')),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='lead time (days)')),
                ('minimum_order_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='minimum order quantity')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='preferred')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_catalogue', to='inventory.inventoryitem', verbose_name='item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='organizations.organization', verbose_name='organization')),
                ('package_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='inventory.packageunit', verbose_name='purchase package')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'supplier item',
                'verbose_name_plural': 'supplier items',
                'ordering': ['supplier__code', 'item__code', '-effective_from'],
                'permissions': [('manage_supplier_items', 'Can maintain the supplier item catalogue')],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='supplier_item_org_active_idx'), models.Index(fields=['item', 'is_active'], name='supplier_item_item_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='procurement_supplier_item_period_is_ordered'), models.CheckConstraint(condition=models.Q(('last_quoted_price__isnull', True), ('last_quoted_price__gte', 0), _connector='OR'), name='procurement_supplier_item_price_not_negative'), models.CheckConstraint(condition=models.Q(('minimum_order_quantity__isnull', True), ('minimum_order_quantity__gt', 0), _connector='OR'), name='procurement_supplier_item_minimum_is_positive'), models.UniqueConstraint(fields=('supplier', 'item', 'package_unit', 'version'), name='procurement_supplier_item_version_unique', nulls_distinct=False), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_preferred', True)), fields=('organization', 'item'), name='procurement_supplier_item_one_preferred_per_item')],
            },
        ),
    ]
