# Generated by Django 5.2.17 on 2026-08-11 15:43

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_task_1_7b_stock_locations'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0003_supplier_item_no_overlap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسل'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=10, verbose_name='status')),
                ('required_date', models.DateField(verbose_name='required by')),
                ('purpose', models.CharField(max_length=200, verbose_name='purpose')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_reason', models.TextField(blank=True, verbose_name='decision reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stocklocation', verbose_name='destination location')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='destination warehouse')),
            ],
            options={
                'verbose_name': 'historical purchase request',
                'verbose_name_plural': 'historical purchase requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسل'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=10, verbose_name='status')),
                ('required_date', models.DateField(verbose_name='required by')),
                ('purpose', models.CharField(max_length=200, verbose_name='purpose')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_reason', models.TextField(blank=True, verbose_name='decision reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='organizations.branch', verbose_name='branch')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.stocklocation', verbose_name='destination location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='organizations.organization', verbose_name='organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.warehouse', verbose_name='destination warehouse')),
            ],
            options={
                'verbose_name': 'purchase request',
                'verbose_name_plural': 'purchase requests',
                'ordering': ['-submitted_at', '-id'],
                'permissions': [('create_purchase_request', 'Can prepare and submit a purchase request'), ('approve_purchase_request', 'Can approve or reject a purchase request')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseRequestLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('conversion_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='conversion version')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True, verbose_name='factor to base')),
                ('entered_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conversion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.itempackageconversion', verbose_name='conversion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item')),
                ('package_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.packageunit', verbose_name='package')),
                ('preferred_supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='preferred supplier')),
                ('request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.purchaserequest', verbose_name='request')),
            ],
            options={
                'verbose_name': 'historical purchase request line',
                'verbose_name_plural': 'historical purchase request lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('conversion_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='conversion version')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True, verbose_name='factor to base')),
                ('entered_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='inventory.itempackageconversion', verbose_name='conversion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='inventory.inventoryitem', verbose_name='item')),
                ('package_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='inventory.packageunit', verbose_name='package')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_lines', to='procurement.supplier', verbose_name='preferred supplier')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaserequest', verbose_name='request')),
            ],
            options={
                'verbose_name': 'purchase request line',
                'verbose_name_plural': 'purchase request lines',
                'ordering': ['request', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=32, verbose_name='document type')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='last number')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_sequences', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'procurement document sequence',
                'verbose_name_plural': 'procurement document sequences',
                'constraints': [models.UniqueConstraint(fields=('organization', 'document_type', 'year'), name='procurement_sequence_unique_per_type_and_year')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['organization', 'status'], name='pr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['branch', 'status'], name='pr_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('decided_by__isnull', True), models.Q(('decided_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='procurement_request_approver_is_not_the_submitter'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True)), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='procurement_request_decision_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('submitted_at__isnull', False), ('submitted_by__isnull', False)), _connector='OR'), name='procurement_request_submission_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['REJECTED', 'CANCELLED']), _negated=True), models.Q(('decision_reason', ''), _negated=True), _connector='OR'), name='procurement_request_refusal_states_a_reason'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='procurement_request_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('entered_quantity__gt', 0)), name='procurement_request_line_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='procurement_request_line_base_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversion__isnull', True), ('package_unit__isnull', True)), models.Q(('conversion__isnull', False), ('package_unit__isnull', False)), _connector='OR'), name='procurement_request_line_package_carries_its_conversion'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.UniqueConstraint(fields=('request', 'sequence'), name='procurement_request_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.UniqueConstraint(fields=('request', 'item', 'package_unit'), name='procurement_request_line_item_appears_once', nulls_distinct=False),
        ),
    ]
