# Generated by Django 5.2.17 on 2026-08-11 16:00

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_task_1_7b_stock_locations'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0004_purchase_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierQuotation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('supplier_reference', models.CharField(blank=True, max_length=64, verbose_name='supplier reference')),
                ('quoted_at', models.DateField(verbose_name='quoted on')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('freight_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=21, verbose_name='freight')),
                ('other_charges', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=21, verbose_name='other charges')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُستلم'), ('AWARDED', 'مُرسى'), ('DECLINED', 'مستبعد'), ('EXPIRED', 'منتهي')], default='DRAFT', max_length=10, verbose_name='status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.purchaserequest', verbose_name='purchase request')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'historical supplier quotation',
                'verbose_name_plural': 'historical supplier quotations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('supplier_reference', models.CharField(blank=True, max_length=64, verbose_name='supplier reference')),
                ('quoted_at', models.DateField(verbose_name='quoted on')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('freight_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=21, verbose_name='freight')),
                ('other_charges', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=21, verbose_name='other charges')),
                ('evidence_reference', models.CharField(blank=True, max_length=200, verbose_name='evidence reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُستلم'), ('AWARDED', 'مُرسى'), ('DECLINED', 'مستبعد'), ('EXPIRED', 'منتهي')], default='DRAFT', max_length=10, verbose_name='status')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotations', to='organizations.organization', verbose_name='organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_quotations', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='procurement.purchaserequest', verbose_name='purchase request')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'supplier quotation',
                'verbose_name_plural': 'supplier quotations',
                'ordering': ['-quoted_at', '-id'],
                'permissions': [('manage_quotations', 'Can record and submit supplier quotations'), ('award_quotation', 'Can award a quotation and record the reason')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplierQuotationLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('conversion_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='conversion version')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True, verbose_name='factor to base')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit price')),
                ('line_total', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='line total')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('conversion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.itempackageconversion', verbose_name='conversion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item')),
                ('package_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.packageunit', verbose_name='package')),
                ('supplier_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplieritem', verbose_name='catalogue row')),
                ('quotation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierquotation', verbose_name='quotation')),
            ],
            options={
                'verbose_name': 'historical supplier quotation line',
                'verbose_name_plural': 'historical supplier quotation lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('conversion_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='conversion version')),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True, verbose_name='factor to base')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit price')),
                ('line_total', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='line total')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='inventory.itempackageconversion', verbose_name='conversion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='inventory.inventoryitem', verbose_name='item')),
                ('package_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='inventory.packageunit', verbose_name='package')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.supplierquotation', verbose_name='quotation')),
                ('supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='procurement.supplieritem', verbose_name='catalogue row')),
            ],
            options={
                'verbose_name': 'supplier quotation line',
                'verbose_name_plural': 'supplier quotation lines',
                'ordering': ['quotation', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['organization', 'status'], name='quotation_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['request'], name='quotation_request_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.CheckConstraint(condition=models.Q(('freight_amount__gte', 0), ('other_charges__gte', 0)), name='procurement_quotation_charges_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('quoted_at')), _connector='OR'), name='procurement_quotation_validity_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='procurement_quotation_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_reference', ''), _negated=True), fields=('supplier', 'supplier_reference'), name='procurement_quotation_reference_unique_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='procurement_quotation_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', 0)), name='procurement_quotation_line_base_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='procurement_quotation_line_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='procurement_quotation_line_total_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversion__isnull', True), ('package_unit__isnull', True)), models.Q(('conversion__isnull', False), ('package_unit__isnull', False)), _connector='OR'), name='procurement_quotation_line_package_carries_its_conversion'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.UniqueConstraint(fields=('quotation', 'sequence'), name='procurement_quotation_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.UniqueConstraint(fields=('quotation', 'item', 'package_unit'), name='procurement_quotation_line_item_appears_once', nulls_distinct=False),
        ),
    ]
