# Generated by Django 5.2.17 on 2026-08-11 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_task_1_7b_stock_locations'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0005_supplier_quotations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='award_reason',
            field=models.TextField(blank=True, verbose_name='award reason'),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='awarded at'),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='awarded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='awarded by'),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequest',
            name='awarded_quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierquotation', verbose_name='awarded quotation'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='award_reason',
            field=models.TextField(blank=True, verbose_name='award reason'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='awarded at'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='awarded by'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='awarded_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_for', to='procurement.supplierquotation', verbose_name='awarded quotation'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('award_reason', ''), ('awarded_at__isnull', True), ('awarded_by__isnull', True), ('awarded_quotation__isnull', True)), models.Q(('awarded_at__isnull', False), ('awarded_by__isnull', False), ('awarded_quotation__isnull', False), models.Q(('award_reason', ''), _negated=True)), _connector='OR'), name='procurement_request_award_is_complete_or_absent'),
        ),
    ]
