# Generated by Django 5.2.17 on 2026-08-11 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_purchase_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='revised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last revised at'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='revised_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last revised at'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('version', models.PositiveIntegerField(verbose_name='version')),
                ('header', models.JSONField(default=dict, verbose_name='header snapshot')),
                ('lines', models.JSONField(default=list, verbose_name='line snapshot')),
                ('reason', models.TextField(verbose_name='revision reason')),
                ('revised_at', models.DateTimeField(verbose_name='revised at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='procurement.purchaseorder', verbose_name='order')),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_revisions', to=settings.AUTH_USER_MODEL, verbose_name='revised by')),
            ],
            options={
                'verbose_name': 'purchase order version',
                'verbose_name_plural': 'purchase order versions',
                'ordering': ['order', '-version'],
                'constraints': [models.UniqueConstraint(fields=('order', 'version'), name='procurement_order_version_unique'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='procurement_order_version_states_a_reason')],
            },
        ),
    ]
