# Generated by Django 5.2.17 on 2026-08-12 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_inter_branch_clearing_role'),
        ('inventory', '0018_task_1_7b_stock_locations'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0009_goods_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='business_date_timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='business timezone'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='business_day_start',
            field=models.TimeField(blank=True, null=True, verbose_name='business day start'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='accounting.journalentry', verbose_name='journal entry'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='posted_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='posted value'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_goods_receipts', to='accounting.journalentry', verbose_name='reversal journal entry'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_goods_receipts', to=settings.AUTH_USER_MODEL, verbose_name='reversed by'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='stock_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='inventory.stockledgerentry', verbose_name='stock entry'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='contra_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_contra_lines', to='accounting.account', verbose_name='GRNI account'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='accounting.account', verbose_name='inventory account'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='journal_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='accounting.journalline', verbose_name='journal line'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.stockmovement', verbose_name='stock movement'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='posted_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True, verbose_name='posted unit cost'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='posted_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='posted value'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='resolved_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.inventoryaccountmapping', verbose_name='item mapping'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='resolved_organization_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='accounting.organizationaccountmapping', verbose_name='organization mapping'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='business_date_timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='business timezone'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='business_day_start',
            field=models.TimeField(blank=True, null=True, verbose_name='business day start'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='posted_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='posted value'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='reversed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceipt',
            name='stock_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockledgerentry', verbose_name='stock entry'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='contra_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='GRNI account'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='inventory_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='inventory account'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='journal_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalline', verbose_name='journal line'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='movement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockmovement', verbose_name='stock movement'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='posted_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True, verbose_name='posted unit cost'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='posted_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='posted value'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='resolved_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryaccountmapping', verbose_name='item mapping'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptline',
            name='resolved_organization_mapping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.organizationaccountmapping', verbose_name='organization mapping'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['POSTED', 'REVERSED']), _negated=True), models.Q(('business_date_timezone__gt', ''), ('business_day_start__isnull', False), ('journal_entry__isnull', False), ('posted_value__isnull', False), ('stock_entry__isnull', False)), _connector='OR'), name='procurement_receipt_posted_names_both_ledgers'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('journal_entry__isnull', True), ('stock_entry__isnull', True)), _connector='OR'), name='procurement_receipt_draft_reached_no_ledger'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_journal_entry__isnull', False), ('reversed_at__isnull', False), ('reversed_by__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='procurement_receipt_reversal_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'REVERSED'), models.Q(('reversal_journal_entry__isnull', True), ('reversal_reason', ''), ('reversed_at__isnull', True), ('reversed_by__isnull', True)), _connector='OR'), name='procurement_receipt_unreversed_carries_no_reversal'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('movement__isnull', True), ('posted_value__isnull', False), _connector='OR'), name='procurement_receipt_line_movement_states_its_value'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('posted_value__isnull', True), ('accepted_base_quantity', 0), ('movement__isnull', False), _connector='OR'), name='procurement_receipt_line_accepted_stock_has_a_movement'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contra_account__isnull', True), ('inventory_account__isnull', True)), models.Q(('contra_account__isnull', False), ('inventory_account__isnull', False)), _connector='OR'), name='procurement_receipt_line_names_both_accounts'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('movement__isnull', True), ('inventory_account__isnull', False), _connector='OR'), name='procurement_receipt_line_movement_names_its_account'),
        ),
    ]
