# Generated by Django 5.2.17 on 2026-08-13 13:06

import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0013_supplier_invoice_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchaseMatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('READY', 'جاهزة للترحيل المالي'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=12, verbose_name='status')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='ready at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('allocation_fingerprint', models.CharField(blank=True, max_length=64, verbose_name='allocation fingerprint')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('ready_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='marked ready by')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='supplier')),
                ('supplier_invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierinvoice', verbose_name='supplier invoice')),
            ],
            options={
                'verbose_name': 'historical purchase match',
                'verbose_name_plural': 'historical purchase matches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('READY', 'جاهزة للترحيل المالي'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=12, verbose_name='status')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='ready at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('allocation_fingerprint', models.CharField(blank=True, max_length=64, verbose_name='allocation fingerprint')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_purchase_matches', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_matches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_matches', to='organizations.organization', verbose_name='organization')),
                ('ready_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readied_purchase_matches', to=settings.AUTH_USER_MODEL, verbose_name='marked ready by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_matches', to='procurement.supplier', verbose_name='supplier')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='procurement.supplierinvoice', verbose_name='supplier invoice')),
            ],
            options={
                'verbose_name': 'purchase match',
                'verbose_name_plural': 'purchase matches',
                'ordering': ['-id'],
                'permissions': [('match_supplier_invoice', 'Can match a supplier invoice to its deliveries'), ('cancel_purchase_match', 'Can cancel a purchase match')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseMatchAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('allocation_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='allocation uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('purchase_order_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='order version')),
                ('matched_base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='matched quantity (base)')),
                ('receipt_allocated_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='receipt value')),
                ('invoice_allocated_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='invoice value')),
                ('price_variance', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='price variance')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('goods_receipt_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.goodsreceiptline', verbose_name='receipt line')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.purchaseorderline', verbose_name='order line')),
                ('supplier_invoice_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierinvoiceline', verbose_name='invoice line')),
                ('match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.purchasematch', verbose_name='match')),
            ],
            options={
                'verbose_name': 'historical purchase match allocation',
                'verbose_name_plural': 'historical purchase match allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseMatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('allocation_uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='allocation uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('purchase_order_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='order version')),
                ('matched_base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='matched quantity (base)')),
                ('receipt_allocated_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='receipt value')),
                ('invoice_allocated_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='invoice value')),
                ('price_variance', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='price variance')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_match_allocations', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('goods_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_allocations', to='procurement.goodsreceiptline', verbose_name='receipt line')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.purchasematch', verbose_name='match')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_allocations', to='procurement.purchaseorderline', verbose_name='order line')),
                ('supplier_invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_allocations', to='procurement.supplierinvoiceline', verbose_name='invoice line')),
            ],
            options={
                'verbose_name': 'purchase match allocation',
                'verbose_name_plural': 'purchase match allocations',
                'ordering': ['match', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasematch',
            index=models.Index(fields=['organization', 'status'], name='match_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasematch',
            index=models.Index(fields=['supplier_invoice'], name='match_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('supplier_invoice',), name='procurement_one_active_match_per_invoice'),
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='procurement_match_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'READY'), _negated=True), models.Q(('ready_at__isnull', False), ('ready_by__isnull', False), models.Q(('allocation_fingerprint', ''), _negated=True)), _connector='OR'), name='procurement_match_ready_says_who_and_what'),
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'READY'), models.Q(('ready_at__isnull', True), ('ready_by__isnull', True)), _connector='OR'), name='procurement_match_unready_carries_no_readiness'),
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='procurement_match_cancellation_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='procurement_match_uncancelled_carries_no_cancellation'),
        ),
        migrations.AddIndex(
            model_name='purchasematchallocation',
            index=models.Index(fields=['supplier_invoice_line'], name='match_alloc_invoice_line_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasematchallocation',
            index=models.Index(fields=['goods_receipt_line'], name='match_alloc_receipt_line_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasematchallocation',
            index=models.Index(fields=['purchase_order_line'], name='match_alloc_order_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasematchallocation',
            constraint=models.UniqueConstraint(fields=('match', 'sequence'), name='procurement_match_allocation_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchasematchallocation',
            constraint=models.UniqueConstraint(fields=('match', 'supplier_invoice_line', 'goods_receipt_line'), name='procurement_match_allocation_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchasematchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('matched_base_quantity__gt', 0)), name='procurement_match_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchasematchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_allocated_value__gte', 0), ('invoice_allocated_value__gte', 0)), name='procurement_match_allocation_values_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchasematchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('price_variance', django.db.models.expressions.CombinedExpression(models.F('invoice_allocated_value'), '-', models.F('receipt_allocated_value')))), name='procurement_match_allocation_variance_is_the_difference'),
        ),
        migrations.AddConstraint(
            model_name='purchasematchallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purchase_order_line__isnull', True), ('purchase_order_version__isnull', True)), models.Q(('purchase_order_line__isnull', False), ('purchase_order_version__isnull', False)), _connector='OR'), name='procurement_match_allocation_order_carries_its_version'),
        ),
    ]
