# Generated by Django 5.2.17 on 2026-08-13 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0015_purchase_match_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchasematch',
            name='procurement_match_unready_carries_no_readiness',
        ),
        migrations.AddConstraint(
            model_name='purchasematch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('ready_at__isnull', True), ('ready_by__isnull', True)), _connector='OR'), name='procurement_match_draft_carries_no_readiness'),
        ),
    ]
