# Generated by Django 5.2.17 on 2026-08-13 19:28

import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_purchase_price_variance_role'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0016_match_readiness_survives_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierInvoicePosting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='generation')),
                ('status', models.CharField(choices=[('LIVE', 'سارٍ'), ('REVERSED', 'معكوس')], default='LIVE', max_length=10, verbose_name='status')),
                ('allocation_fingerprint', models.CharField(max_length=64, verbose_name='allocation fingerprint')),
                ('goods_cleared_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='goods cleared from GRNI')),
                ('invoice_matched_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='invoiced value of matched goods')),
                ('price_variance', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='price variance')),
                ('direct_charge_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='direct charges')),
                ('payable_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='supplier payable')),
                ('posted_at', models.DateTimeField(verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('purchase_match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.purchasematch', verbose_name='purchase match')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('supplier_invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierinvoice', verbose_name='supplier invoice')),
            ],
            options={
                'verbose_name': 'historical supplier invoice posting',
                'verbose_name_plural': 'historical supplier invoice postings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierInvoicePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('generation', models.PositiveIntegerField(default=1, verbose_name='generation')),
                ('status', models.CharField(choices=[('LIVE', 'سارٍ'), ('REVERSED', 'معكوس')], default='LIVE', max_length=10, verbose_name='status')),
                ('allocation_fingerprint', models.CharField(max_length=64, verbose_name='allocation fingerprint')),
                ('goods_cleared_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='goods cleared from GRNI')),
                ('invoice_matched_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='invoiced value of matched goods')),
                ('price_variance', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='price variance')),
                ('direct_charge_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='direct charges')),
                ('payable_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='supplier payable')),
                ('posted_at', models.DateTimeField(verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_postings', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_postings', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_supplier_invoice_postings', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('purchase_match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='procurement.purchasematch', verbose_name='purchase match')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_invoice_postings', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_invoice_postings', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='procurement.supplierinvoice', verbose_name='supplier invoice')),
            ],
            options={
                'verbose_name': 'supplier invoice posting',
                'verbose_name_plural': 'supplier invoice postings',
                'ordering': ['supplier_invoice', 'generation'],
                'indexes': [models.Index(fields=['organization', 'status'], name='posting_org_status_idx'), models.Index(fields=['supplier_invoice', 'status'], name='posting_invoice_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier_invoice', 'generation'), name='procurement_posting_generation_unique'), models.UniqueConstraint(condition=models.Q(('status', 'LIVE')), fields=('supplier_invoice',), name='procurement_one_live_posting_per_invoice'), models.UniqueConstraint(condition=models.Q(('status', 'LIVE')), fields=('purchase_match',), name='procurement_one_live_posting_per_match'), models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='procurement_posting_generation_is_positive'), models.CheckConstraint(condition=models.Q(('price_variance', django.db.models.expressions.CombinedExpression(models.F('invoice_matched_value'), '-', models.F('goods_cleared_value')))), name='procurement_posting_variance_is_the_difference'), models.CheckConstraint(condition=models.Q(('payable_value', django.db.models.expressions.CombinedExpression(models.F('direct_charge_value'), '+', models.F('invoice_matched_value')))), name='procurement_posting_payable_is_the_whole_invoice'), models.CheckConstraint(condition=models.Q(('goods_cleared_value__gte', 0), ('invoice_matched_value__gte', 0), ('direct_charge_value__gte', 0), ('payable_value__gt', 0)), name='procurement_posting_values_are_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_journal_entry__isnull', False), ('reversed_at__isnull', False), ('reversed_by__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='procurement_posting_reversal_is_complete'), models.CheckConstraint(condition=models.Q(('status', 'REVERSED'), models.Q(('reversal_journal_entry__isnull', True), ('reversal_reason', ''), ('reversed_at__isnull', True), ('reversed_by__isnull', True)), _connector='OR'), name='procurement_posting_live_carries_no_reversal')],
            },
        ),
    ]
