# Generated by Django 5.2.17 on 2026-08-13 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_purchase_price_variance_role'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0019_invoice_may_be_posted_again'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierinvoiceposting',
            name='procurement_one_live_posting_per_match',
        ),
        migrations.AlterField(
            model_name='historicalsupplierinvoiceposting',
            name='allocation_fingerprint',
            field=models.CharField(blank=True, max_length=64, verbose_name='allocation fingerprint'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceposting',
            name='allocation_fingerprint',
            field=models.CharField(blank=True, max_length=64, verbose_name='allocation fingerprint'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceposting',
            name='purchase_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='procurement.purchasematch', verbose_name='purchase match'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceposting',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_match__isnull', False), ('status', 'LIVE')), fields=('purchase_match',), name='procurement_one_live_posting_per_match'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceposting',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_match__isnull', False), models.Q(('goods_cleared_value', 0), ('invoice_matched_value', 0), ('price_variance', 0)), _connector='OR'), name='procurement_posting_goods_need_a_match'),
        ),
    ]
