# Generated by Django 5.2.17 on 2026-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0023_supplier_return_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplierreturn',
            name='business_day_start',
            field=models.TimeField(blank=True, null=True, verbose_name='business day start'),
        ),
        migrations.AlterField(
            model_name='supplierreturn',
            name='business_day_start',
            field=models.TimeField(blank=True, null=True, verbose_name='business day start'),
        ),
    ]
