# Generated by Django 5.2.17 on 2026-08-14 20:44

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_supplier_return_roles'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0024_return_business_day_start_is_a_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierCreditNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('supplier_document_number', models.CharField(max_length=64, verbose_name='supplier document number')),
                ('supplier_document_number_key', models.CharField(editable=False, max_length=64, verbose_name='supplier document number (key)')),
                ('credit_date', models.DateField(verbose_name='credit date')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='amount')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='supplier')),
                ('supplier_return', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierreturn', verbose_name='supplier return')),
            ],
            options={
                'verbose_name': 'historical supplier credit note',
                'verbose_name_plural': 'historical supplier credit notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('supplier_document_number', models.CharField(max_length=64, verbose_name='supplier document number')),
                ('supplier_document_number_key', models.CharField(editable=False, max_length=64, verbose_name='supplier document number (key)')),
                ('credit_date', models.DateField(verbose_name='credit date')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='amount')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_notes', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_notes', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_notes', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_supplier_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_credit_notes', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_credit_notes', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='procurement.supplier', verbose_name='supplier')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='procurement.supplierreturn', verbose_name='supplier return')),
            ],
            options={
                'verbose_name': 'supplier credit note',
                'verbose_name_plural': 'supplier credit notes',
                'ordering': ['-id'],
                'permissions': [('create_supplier_credit_note', 'Can record a supplier credit note'), ('post_supplier_credit_note', 'Can post a supplier credit note'), ('reverse_supplier_credit_note', 'Can reverse a posted supplier credit note')],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated amount')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='procurement.supplierinvoice', verbose_name='invoice')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.suppliercreditnote', verbose_name='credit note')),
            ],
            options={
                'verbose_name': 'supplier credit allocation',
                'verbose_name_plural': 'supplier credit allocations',
                'ordering': ['credit_note', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplierCreditAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated amount')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierinvoice', verbose_name='invoice')),
                ('credit_note', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.suppliercreditnote', verbose_name='credit note')),
            ],
            options={
                'verbose_name': 'historical supplier credit allocation',
                'verbose_name_plural': 'historical supplier credit allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='suppliercreditnote',
            index=models.Index(fields=['organization', 'status'], name='scn_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditnote',
            index=models.Index(fields=['supplier', 'status'], name='scn_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditnote',
            index=models.Index(fields=['supplier_return'], name='scn_return_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='procurement_scn_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REVERSED'), _negated=True), fields=('organization', 'supplier', 'supplier_document_number_key'), name='procurement_scn_document_unique_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REVERSED'), _negated=True), fields=('supplier_return',), name='procurement_scn_one_standing_note_per_return'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='procurement_scn_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supplier_document_number', ''), _negated=True), models.Q(('supplier_document_number_key', ''), _negated=True)), name='procurement_scn_states_the_supplier_reference'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('posted_by__isnull', True)), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False)), _connector='OR'), name='procurement_scn_posting_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('journal_entry__isnull', True), ('posted_at__isnull', True)), _connector='OR'), name='procurement_scn_draft_has_posted_nothing'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['POSTED', 'REVERSED']), _negated=True), models.Q(('business_date_timezone__gt', ''), ('business_day_start__isnull', False), ('journal_entry__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='procurement_scn_posted_names_its_journal'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_journal_entry__isnull', False), ('reversed_at__isnull', False), ('reversed_by__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='procurement_scn_reversal_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'REVERSED'), models.Q(('reversal_journal_entry__isnull', True), ('reversal_reason', ''), ('reversed_at__isnull', True), ('reversed_by__isnull', True)), _connector='OR'), name='procurement_scn_unreversed_carries_no_reversal'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditallocation',
            index=models.Index(fields=['invoice'], name='scn_alloc_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditallocation',
            constraint=models.UniqueConstraint(fields=('credit_note', 'sequence'), name='procurement_scn_allocation_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditallocation',
            constraint=models.UniqueConstraint(fields=('credit_note', 'invoice'), name='procurement_scn_allocation_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='procurement_scn_allocation_positive'),
        ),
    ]
