# Generated by Django 5.2.17 on 2026-08-14 22:58
"""
Partial, line-level credit-note settlement.

The first cut of Task 2.14 settled a return whole — one standing note per
return, the journal's clearing credit taken from the return header. The
approved rule is finer: a note allocates **explicitly to return lines**, may
settle part of a line, and a line may be settled by several notes, bounded by
what it returned and what it posted. This migration adds the allocation
model, drops the one-note-per-return constraint, and **backfills** every
already-posted note with the allocations its journal implies — full quantity
per line, the line's book value settled, the note's amount spread over the
lines by settled value with the last line taking the exact remainder — so a
database that posted under the old rule reconciles identically under the new
verifier.
"""

import uuid
from decimal import ROUND_HALF_UP, Decimal

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

MONEY = Decimal("0.001")


def _backfill(apps, schema_editor):
    SupplierCreditNote = apps.get_model("procurement", "SupplierCreditNote")
    Allocation = apps.get_model("procurement", "SupplierCreditReturnAllocation")

    for note in SupplierCreditNote.objects.exclude(status="DRAFT").order_by("pk"):
        if note.return_allocations.exists():
            continue
        lines = list(note.supplier_return.lines.order_by("sequence"))
        total_book = sum((line.posted_value or Decimal("0") for line in lines), Decimal("0"))
        remaining_credit = note.amount
        for index, line in enumerate(lines, start=1):
            book = line.posted_value or Decimal("0")
            if index == len(lines):
                credit = remaining_credit
            elif total_book:
                credit = (note.amount * book / total_book).quantize(
                    MONEY, rounding=ROUND_HALF_UP
                )
            else:  # pragma: no cover - a posted return always carries value
                credit = Decimal("0.001")
            remaining_credit -= credit
            Allocation.objects.create(
                credit_note=note,
                sequence=index,
                supplier_return_line=line,
                credited_base_quantity=line.returned_base_quantity,
                allocated_credit_amount=credit,
                settled_book_value=book,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0026_supplier_credit_note_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierCreditReturnAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('allocation_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='allocation uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('credited_base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='credited quantity (base)')),
                ('allocated_credit_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated credit')),
                ('settled_book_value', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='settled book value')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical supplier credit return allocation',
                'verbose_name_plural': 'historical supplier credit return allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierCreditReturnAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('allocation_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='allocation uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('credited_base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='credited quantity (base)')),
                ('allocated_credit_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated credit')),
                ('settled_book_value', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='settled book value')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
            ],
            options={
                'verbose_name': 'supplier credit return allocation',
                'verbose_name_plural': 'supplier credit return allocations',
                'ordering': ['credit_note', 'sequence'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='suppliercreditnote',
            name='procurement_scn_one_standing_note_per_return',
        ),
        migrations.AddField(
            model_name='historicalsuppliercreditreturnallocation',
            name='credit_note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.suppliercreditnote', verbose_name='credit note'),
        ),
        migrations.AddField(
            model_name='historicalsuppliercreditreturnallocation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsuppliercreditreturnallocation',
            name='supplier_return_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierreturnline', verbose_name='return line'),
        ),
        migrations.AddField(
            model_name='suppliercreditreturnallocation',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_allocations', to='procurement.suppliercreditnote', verbose_name='credit note'),
        ),
        migrations.AddField(
            model_name='suppliercreditreturnallocation',
            name='supplier_return_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='procurement.supplierreturnline', verbose_name='return line'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditreturnallocation',
            index=models.Index(fields=['supplier_return_line'], name='scn_ralloc_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditreturnallocation',
            constraint=models.UniqueConstraint(fields=('credit_note', 'sequence'), name='procurement_scn_ralloc_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditreturnallocation',
            constraint=models.UniqueConstraint(fields=('credit_note', 'supplier_return_line'), name='procurement_scn_ralloc_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditreturnallocation',
            constraint=models.CheckConstraint(condition=models.Q(('credited_base_quantity__gt', 0)), name='procurement_scn_ralloc_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditreturnallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_credit_amount__gt', 0)), name='procurement_scn_ralloc_credit_positive'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditreturnallocation',
            constraint=models.CheckConstraint(condition=models.Q(('settled_book_value__isnull', True), ('settled_book_value__gte', 0), _connector='OR'), name='procurement_scn_ralloc_settled_not_negative'),
        ),
        # The old rule's rows become the new rule's: every posted note gains
        # the allocations its journal implies. Reverse is a no-op — deleting
        # them would orphan nothing but re-running forward recreates them.
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
