# Generated by Django 5.2.17 on 2026-08-15 00:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_supplier_payment_roles'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('procurement', '0028_credit_return_allocation_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('paid_at', models.DateField(verbose_name='paid at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'حوالة مصرفية')], max_length=8, verbose_name='method')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='amount')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'historical supplier payment',
                'verbose_name_plural': 'historical supplier payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='number')),
                ('paid_at', models.DateField(verbose_name='paid at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'حوالة مصرفية')], max_length=8, verbose_name='method')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='amount')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_payments', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'supplier payment',
                'verbose_name_plural': 'supplier payments',
                'ordering': ['-id'],
                'permissions': [('create_supplier_payment', 'Can record a supplier payment'), ('post_supplier_payment', 'Can post a supplier payment'), ('reverse_supplier_payment', 'Can reverse a posted supplier payment')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated amount')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='procurement.supplierinvoice', verbose_name='invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.supplierpayment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'payment allocation',
                'verbose_name_plural': 'payment allocations',
                'ordering': ['payment', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaymentAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('allocated_amount', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='allocated amount')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierinvoice', verbose_name='invoice')),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierpayment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'historical payment allocation',
                'verbose_name_plural': 'historical payment allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['organization', 'status'], name='spay_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['supplier', 'status'], name='spay_supplier_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='procurement_spay_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='procurement_spay_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('posted_by__isnull', True)), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False)), _connector='OR'), name='procurement_spay_posting_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('journal_entry__isnull', True), ('posted_at__isnull', True)), _connector='OR'), name='procurement_spay_draft_has_posted_nothing'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['POSTED', 'REVERSED']), _negated=True), models.Q(('business_date_timezone__gt', ''), ('business_day_start__isnull', False), ('journal_entry__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='procurement_spay_posted_names_its_journal'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversal_journal_entry__isnull', False), ('reversed_at__isnull', False), ('reversed_by__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='procurement_spay_reversal_is_complete'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'REVERSED'), models.Q(('reversal_journal_entry__isnull', True), ('reversal_reason', ''), ('reversed_at__isnull', True), ('reversed_by__isnull', True)), _connector='OR'), name='procurement_spay_unreversed_carries_no_reversal'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice'], name='spay_alloc_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'sequence'), name='procurement_spay_allocation_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='procurement_spay_allocation_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='procurement_spay_allocation_positive'),
        ),
    ]
