# Generated by Django 5.2.17 on 2026-08-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0030_supplier_payment_guards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('manage_suppliers', 'Can create, edit and archive suppliers'), ('view_supplier_cost', 'Can view supplier prices and amounts'), ('view_procurement_report', 'Can view procurement reports')], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
    ]
