# Generated by Django 5.2.17 on 2026-08-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0031_report_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('manage_suppliers', 'Can create, edit and archive suppliers'), ('view_supplier_cost', 'Can view supplier prices and amounts'), ('view_procurement_report', 'Can view procurement reports'), ('import_supplier', 'Can import suppliers'), ('import_supplier_item', 'Can import the supplier catalogue')], 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
    ]
