# Generated by Django 5.2.17 on 2026-08-19 16:51

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

LEGACY_EFFECTIVE_FROM = "1900-01-01"


def _term_name_ar(days):
    return "عند الاستلام" if days == 0 else f"{days} يوم"


def _term_name_en(days):
    return "Due on receipt" if days == 0 else f"Net {days}"


def backfill_credit_terms(apps, schema_editor):
    Supplier = apps.get_model("procurement", "Supplier")
    term_model = apps.get_model("procurement", "SupplierCreditTerm")
    invoice_model = apps.get_model("procurement", "SupplierInvoice")
    historical_invoice_model = apps.get_model("procurement", "HistoricalSupplierInvoice")

    for supplier in Supplier.objects.order_by("pk").iterator():
        invoice_days = set(
            invoice_model.objects.filter(supplier_id=supplier.pk).values_list(
                "payment_terms_days", flat=True
            )
        )
        invoice_days.add(supplier.payment_terms_days)
        terms_by_days = {}
        ordered_days = sorted(invoice_days)
        for version, days in enumerate(ordered_days, start=1):
            is_current = days == supplier.payment_terms_days
            term = term_model.objects.create(
                organization_id=supplier.organization_id,
                supplier_id=supplier.pk,
                version=version,
                status="ACTIVE" if is_current else "SUPERSEDED",
                name_ar=_term_name_ar(days),
                name_en=_term_name_en(days),
                net_days=days,
                effective_from=LEGACY_EFFECTIVE_FROM,
                # A legacy invoice-specific value is preserved only as that
                # invoice's snapshot identity. It was never an effective
                # master-data period, so do not let it resolve for later dates.
                effective_to=None if is_current else LEGACY_EFFECTIVE_FROM,
                notes="Migrated from the pre-versioned supplier/invoice snapshot.",
            )
            terms_by_days[days] = term

        for invoice in invoice_model.objects.filter(supplier_id=supplier.pk).iterator():
            term = terms_by_days[invoice.payment_terms_days]
            invoice_model.objects.filter(pk=invoice.pk).update(
                credit_term_id=term.pk,
                credit_term_public_id=term.public_id,
                credit_term_version=term.version,
                credit_term_name=term.name_ar,
                credit_term_net_days=invoice.payment_terms_days,
            )
        for historical in historical_invoice_model.objects.filter(
            supplier_id=supplier.pk
        ).iterator():
            term = terms_by_days.get(historical.payment_terms_days)
            if term is not None:
                historical_invoice_model.objects.filter(history_id=historical.history_id).update(
                    credit_term_id=term.pk,
                    credit_term_public_id=term.public_id,
                    credit_term_version=term.version,
                    credit_term_name=term.name_ar,
                    credit_term_net_days=historical.payment_terms_days,
                )


def noop_reverse(apps, schema_editor):
    # The tables and columns are removed by the schema reversal that follows.
    pass


DROP_INVOICE_GUARD = """
DROP TRIGGER IF EXISTS procurement_supplier_invoice_immutable
    ON procurement_supplierinvoice;
"""

RESTORE_INVOICE_GUARD = """
CREATE TRIGGER procurement_supplier_invoice_immutable
    BEFORE UPDATE OR DELETE ON procurement_supplierinvoice
    FOR EACH ROW EXECUTE FUNCTION procurement_supplier_invoice_is_immutable();
"""


ACTIVE_NO_OVERLAP = """
ALTER TABLE procurement_suppliercreditterm
    ADD CONSTRAINT procurement_credit_term_no_active_overlap
    EXCLUDE USING gist (
        supplier_id WITH =,
        daterange(effective_from, effective_to, '[]') WITH &&
    )
    WHERE (status = 'ACTIVE');
"""

DROP_ACTIVE_NO_OVERLAP = """
ALTER TABLE procurement_suppliercreditterm
    DROP CONSTRAINT IF EXISTS procurement_credit_term_no_active_overlap;
"""

TERM_GUARD = """
CREATE OR REPLACE FUNCTION procurement_credit_term_is_guarded()
RETURNS TRIGGER AS $$
DECLARE
    supplier_organization bigint;
    supersession_columns text[] := ARRAY['status', 'effective_to', 'updated_at'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION
                'supplier credit term % has been activated and cannot be deleted', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;

    SELECT organization_id INTO supplier_organization
      FROM procurement_supplier
     WHERE id = NEW.supplier_id;
    IF supplier_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION
            'supplier credit term % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.status = 'SUPERSEDED' THEN
        RAISE EXCEPTION
            'superseded supplier credit term % is immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status = 'ACTIVE' THEN
        IF NEW.status <> 'SUPERSEDED'
           OR NEW.effective_to IS NULL
           OR (to_jsonb(NEW) - supersession_columns)
              <> (to_jsonb(OLD) - supersession_columns) THEN
            RAISE EXCEPTION
                'active supplier credit term % is immutable except for supersession', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER procurement_credit_term_guard
    BEFORE INSERT OR UPDATE OR DELETE ON procurement_suppliercreditterm
    FOR EACH ROW EXECUTE FUNCTION procurement_credit_term_is_guarded();
"""

DROP_TERM_GUARD = """
DROP TRIGGER IF EXISTS procurement_credit_term_guard ON procurement_suppliercreditterm;
DROP FUNCTION IF EXISTS procurement_credit_term_is_guarded();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0021_expenses_deferrals_and_year_end"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        ("procurement", "0032_import_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="credit_term_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="credit term name"),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="credit_term_net_days",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="credit term net days"),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="credit_term_public_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="credit term public id"),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="credit_term_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="credit term version"
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="credit_term_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="credit term name"),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="credit_term_net_days",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="credit term net days"),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="credit_term_public_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="credit term public id"),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="credit_term_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="credit term version"
            ),
        ),
        migrations.CreateModel(
            name="SupplierCreditTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="public id"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="version")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "مسودة"), ("ACTIVE", "فعّال"), ("SUPERSEDED", "مستبدل")],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("name_ar", models.CharField(max_length=200, verbose_name="name (Arabic)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=200, verbose_name="name (English)"),
                ),
                ("net_days", models.PositiveSmallIntegerField(default=0, verbose_name="net days")),
                ("effective_from", models.DateField(verbose_name="effective from")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="effective to"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="approved at"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_supplier_credit_terms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_supplier_credit_terms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_credit_terms",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement",
                        to="procurement.suppliercreditterm",
                        verbose_name="supersedes",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_terms",
                        to="procurement.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier credit term",
                "verbose_name_plural": "supplier credit terms",
                "ordering": ["supplier__code", "-version"],
                "permissions": [
                    ("create_supplier_credit_term", "Can draft supplier credit terms"),
                    ("approve_supplier_credit_term", "Can activate supplier credit terms"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSupplierCreditTerm",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, verbose_name="public id"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="version")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "مسودة"), ("ACTIVE", "فعّال"), ("SUPERSEDED", "مستبدل")],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("name_ar", models.CharField(max_length=200, verbose_name="name (Arabic)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=200, verbose_name="name (English)"),
                ),
                ("net_days", models.PositiveSmallIntegerField(default=0, verbose_name="net days")),
                ("effective_from", models.DateField(verbose_name="effective from")),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="effective to"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="approved at"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="procurement.supplier",
                        verbose_name="supplier",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="procurement.suppliercreditterm",
                        verbose_name="supersedes",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical supplier credit term",
                "verbose_name_plural": "historical supplier credit terms",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="credit_term",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.suppliercreditterm",
                verbose_name="credit term",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="credit_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="procurement.suppliercreditterm",
                verbose_name="credit term",
            ),
        ),
        # The guard intentionally freezes approved/posted/reversed invoices. The
        # new columns did not exist when those rows crossed their decision
        # boundary, so suspend only the trigger while filling their snapshots.
        migrations.RunSQL(
            sql=DROP_INVOICE_GUARD,
            reverse_sql=RESTORE_INVOICE_GUARD,
        ),
        migrations.RunPython(backfill_credit_terms, noop_reverse),
        migrations.RunSQL(
            sql=RESTORE_INVOICE_GUARD,
            reverse_sql=DROP_INVOICE_GUARD,
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("credit_term__isnull", True),
                    models.Q(
                        ("credit_term_name__gt", ""),
                        ("credit_term_net_days", models.F("payment_terms_days")),
                        ("credit_term_public_id__isnull", False),
                        ("credit_term_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="procurement_invoice_credit_term_snapshot_complete",
            ),
        ),
        migrations.AddIndex(
            model_name="suppliercreditterm",
            index=models.Index(
                fields=["organization", "status", "effective_from"],
                name="credit_term_org_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="suppliercreditterm",
            index=models.Index(
                fields=["supplier", "effective_from", "effective_to"],
                name="credit_term_supplier_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercreditterm",
            constraint=models.UniqueConstraint(
                fields=("supplier", "version"), name="procurement_credit_term_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercreditterm",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "DRAFT")),
                fields=("supplier",),
                name="procurement_credit_term_one_draft_per_supplier",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercreditterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_ar", ""), _negated=True),
                name="procurement_credit_term_name_ar_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercreditterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="procurement_credit_term_period_is_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercreditterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("approved_at__isnull", True), ("approved_by__isnull", True)),
                    models.Q(("approved_at__isnull", False), ("approved_by__isnull", False)),
                    _connector="OR",
                ),
                name="procurement_credit_term_approval_is_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppliercreditterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("created_by__isnull", True),
                    ("approved_by__isnull", True),
                    models.Q(("created_by", models.F("approved_by")), _negated=True),
                    _connector="OR",
                ),
                name="procurement_credit_term_maker_checker",
            ),
        ),
        migrations.RunSQL(sql=ACTIVE_NO_OVERLAP, reverse_sql=DROP_ACTIVE_NO_OVERLAP),
        migrations.RunSQL(sql=TERM_GUARD, reverse_sql=DROP_TERM_GUARD),
    ]
