# Generated by Django 5.2.17 on 2026-08-19 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0021_expenses_deferrals_and_year_end"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        ("procurement", "0033_supplier_credit_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="currency_code",
            field=models.CharField(
                choices=[("IQD", "IQD")], default="IQD", max_length=3, verbose_name="currency"
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="currency_code",
            field=models.CharField(
                choices=[("IQD", "IQD")], default="IQD", max_length=3, verbose_name="currency"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency_code", "IQD")),
                name="procurement_invoice_currency_is_iqd",
            ),
        ),
    ]
