# Generated by Django 5.2.17 on 2026-08-19 18:34

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
from django.conf import settings
from django.db import migrations, models

CHARGE_GUARDS = r"""
CREATE OR REPLACE FUNCTION procurement_invoice_charge_follows_invoice()
RETURNS TRIGGER AS $$
DECLARE
    invoice_status text;
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.invoice_id IS DISTINCT FROM OLD.invoice_id THEN
        RAISE EXCEPTION 'supplier invoice charge cannot move to another invoice'
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF TG_OP = 'DELETE' THEN
        SELECT status INTO invoice_status FROM procurement_supplierinvoice WHERE id = OLD.invoice_id;
    ELSE
        SELECT status INTO invoice_status FROM procurement_supplierinvoice WHERE id = NEW.invoice_id;
    END IF;
    IF invoice_status <> 'DRAFT' THEN
        RAISE EXCEPTION 'supplier invoice is % and its charges are frozen', invoice_status
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER procurement_invoice_charge_frozen
    BEFORE INSERT OR UPDATE OR DELETE ON procurement_supplierinvoicecharge
    FOR EACH ROW EXECUTE FUNCTION procurement_invoice_charge_follows_invoice();

CREATE OR REPLACE FUNCTION procurement_landed_allocation_is_immutable()
RETURNS TRIGGER AS $$
DECLARE
    posting_invoice bigint;
    posting_status text;
    charge_invoice bigint;
    match_invoice bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'a posted landed-cost allocation is immutable'
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT supplier_invoice_id, status INTO posting_invoice, posting_status
        FROM procurement_supplierinvoiceposting WHERE id = NEW.posting_id;
    SELECT invoice_id INTO charge_invoice
        FROM procurement_supplierinvoicecharge WHERE id = NEW.charge_id;
    SELECT match.supplier_invoice_id INTO match_invoice
        FROM procurement_purchasematchallocation allocation
        JOIN procurement_purchasematch match ON match.id = allocation.match_id
        WHERE allocation.id = NEW.match_allocation_id;
    IF posting_status <> 'LIVE'
       OR posting_invoice IS DISTINCT FROM charge_invoice
       OR posting_invoice IS DISTINCT FROM match_invoice THEN
        RAISE EXCEPTION 'landed-cost allocation evidence does not belong to its live posting'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER procurement_landed_allocation_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON procurement_supplierinvoicechargeallocation
    FOR EACH ROW EXECUTE FUNCTION procurement_landed_allocation_is_immutable();

CREATE OR REPLACE FUNCTION procurement_manual_charge_share_is_guarded()
RETURNS TRIGGER AS $$
DECLARE
    invoice_id bigint;
    invoice_status text;
    basis text;
    treatment text;
    match_invoice bigint;
    match_status text;
    live_postings integer;
    selected_charge bigint;
    selected_match_allocation bigint;
BEGIN
    selected_charge := CASE WHEN TG_OP = 'DELETE' THEN OLD.charge_id ELSE NEW.charge_id END;
    selected_match_allocation := CASE
        WHEN TG_OP = 'DELETE' THEN OLD.match_allocation_id ELSE NEW.match_allocation_id
    END;
    SELECT charge.invoice_id, charge.allocation_basis, charge.treatment, invoice.status
        INTO invoice_id, basis, treatment, invoice_status
        FROM procurement_supplierinvoicecharge charge
        JOIN procurement_supplierinvoice invoice ON invoice.id = charge.invoice_id
        WHERE charge.id = selected_charge;
    SELECT match.supplier_invoice_id, match.status INTO match_invoice, match_status
        FROM procurement_purchasematchallocation allocation
        JOIN procurement_purchasematch match ON match.id = allocation.match_id
        WHERE allocation.id = selected_match_allocation;
    SELECT count(*) INTO live_postings
        FROM procurement_supplierinvoiceposting
        WHERE supplier_invoice_id = invoice_id AND status = 'LIVE';
    IF TG_OP = 'DELETE' AND invoice_status IN ('DRAFT', 'APPROVED') AND live_postings = 0 THEN
        RETURN OLD;
    END IF;
    IF invoice_status <> 'APPROVED' OR basis <> 'MANUAL' OR treatment <> 'LANDED_COST'
       OR match_status <> 'READY' OR match_invoice IS DISTINCT FROM invoice_id
       OR live_postings <> 0 THEN
        RAISE EXCEPTION 'manual landed-cost shares require an approved unposted invoice and its ready match'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER procurement_manual_charge_share_guarded
    BEFORE INSERT OR UPDATE OR DELETE ON procurement_supplierinvoicechargemanualshare
    FOR EACH ROW EXECUTE FUNCTION procurement_manual_charge_share_is_guarded();
"""

DROP_CHARGE_GUARDS = r"""
DROP TRIGGER IF EXISTS procurement_manual_charge_share_guarded
    ON procurement_supplierinvoicechargemanualshare;
DROP FUNCTION IF EXISTS procurement_manual_charge_share_is_guarded();
DROP TRIGGER IF EXISTS procurement_landed_allocation_immutable
    ON procurement_supplierinvoicechargeallocation;
DROP FUNCTION IF EXISTS procurement_landed_allocation_is_immutable();
DROP TRIGGER IF EXISTS procurement_invoice_charge_frozen
    ON procurement_supplierinvoicecharge;
DROP FUNCTION IF EXISTS procurement_invoice_charge_follows_invoice();
"""

POSTING_GUARD_WITH_STOCK = r"""
CREATE OR REPLACE FUNCTION procurement_invoice_posting_is_immutable()
RETURNS TRIGGER AS $$
DECLARE
    reversal_columns text[] := ARRAY[
        'status', 'reversal_journal_entry_id', 'reversal_stock_entry_id',
        'reversed_by_id', 'reversed_at', 'reversal_reason', 'updated_at'
    ];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'supplier invoice posting % is a ledger record and cannot be deleted', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF OLD.status = 'REVERSED' THEN
        RAISE EXCEPTION 'supplier invoice posting % is reversed and immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.status <> 'REVERSED'
       OR (to_jsonb(NEW) - reversal_columns) <> (to_jsonb(OLD) - reversal_columns) THEN
        RAISE EXCEPTION 'supplier invoice posting % is live; only exact reversal is permitted', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

POSTING_GUARD_WITHOUT_STOCK = r"""
CREATE OR REPLACE FUNCTION procurement_invoice_posting_is_immutable()
RETURNS TRIGGER AS $$
DECLARE
    reversal_columns text[] := ARRAY[
        'status', 'reversal_journal_entry_id', 'reversed_by_id', 'reversed_at',
        'reversal_reason', 'updated_at'
    ];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'supplier invoice posting % is a ledger record and cannot be deleted', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF OLD.status = 'REVERSED' THEN
        RAISE EXCEPTION 'supplier invoice posting % is reversed and immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.status <> 'REVERSED'
       OR (to_jsonb(NEW) - reversal_columns) <> (to_jsonb(OLD) - reversal_columns) THEN
        RAISE EXCEPTION 'supplier invoice posting % is live; the only permitted change is its reversal', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0021_expenses_deferrals_and_year_end"),
        ("inventory", "0020_procurement_import_kinds"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        ("procurement", "0034_supplier_invoice_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalSupplierInvoiceCharge",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, verbose_name="public id"
                    ),
                ),
                ("line_order", models.PositiveIntegerField(verbose_name="line order")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FREIGHT", "شحن"),
                            ("DELIVERY", "توصيل"),
                            ("HANDLING", "مناولة"),
                            ("INSURANCE", "تأمين"),
                            ("CUSTOMS", "جمارك"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=16,
                        verbose_name="category",
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("DIRECT_EXPENSE", "تكلفة مباشرة"),
                            ("LANDED_COST", "تكلفة واصلة للمخزون"),
                        ],
                        max_length=16,
                        verbose_name="treatment",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="description")),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, max_digits=21, verbose_name="amount"),
                ),
                (
                    "allocation_basis",
                    models.CharField(
                        choices=[
                            ("RECEIPT_VALUE", "قيمة الاستلام"),
                            ("BASE_QUANTITY", "الكمية الأساسية"),
                            ("MANUAL", "توزيع يدوي"),
                        ],
                        default="RECEIPT_VALUE",
                        max_length=16,
                        verbose_name="allocation basis",
                    ),
                ),
                (
                    "evidence_reference",
                    models.CharField(blank=True, max_length=200, verbose_name="evidence reference"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical supplier invoice charge",
                "verbose_name_plural": "historical supplier invoice charges",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupplierInvoiceChargeAllocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="sequence")),
                (
                    "match_allocation_uid",
                    models.UUIDField(editable=False, verbose_name="match allocation uid"),
                ),
                (
                    "receipt_line_uid",
                    models.UUIDField(editable=False, verbose_name="receipt line uid"),
                ),
                (
                    "matched_base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="matched quantity snapshot"
                    ),
                ),
                (
                    "receipt_allocated_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="receipt value snapshot"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="allocated landed cost"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical supplier invoice charge allocation",
                "verbose_name_plural": "historical supplier invoice charge allocations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupplierInvoiceChargeManualShare",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, max_digits=21, verbose_name="amount"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical supplier invoice charge manual share",
                "verbose_name_plural": "historical supplier invoice charge manual shares",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SupplierInvoiceCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="public id"
                    ),
                ),
                ("line_order", models.PositiveIntegerField(verbose_name="line order")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FREIGHT", "شحن"),
                            ("DELIVERY", "توصيل"),
                            ("HANDLING", "مناولة"),
                            ("INSURANCE", "تأمين"),
                            ("CUSTOMS", "جمارك"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=16,
                        verbose_name="category",
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("DIRECT_EXPENSE", "تكلفة مباشرة"),
                            ("LANDED_COST", "تكلفة واصلة للمخزون"),
                        ],
                        max_length=16,
                        verbose_name="treatment",
                    ),
                ),
                ("description", models.CharField(max_length=200, verbose_name="description")),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, max_digits=21, verbose_name="amount"),
                ),
                (
                    "allocation_basis",
                    models.CharField(
                        choices=[
                            ("RECEIPT_VALUE", "قيمة الاستلام"),
                            ("BASE_QUANTITY", "الكمية الأساسية"),
                            ("MANUAL", "توزيع يدوي"),
                        ],
                        default="RECEIPT_VALUE",
                        max_length=16,
                        verbose_name="allocation basis",
                    ),
                ),
                (
                    "evidence_reference",
                    models.CharField(blank=True, max_length=200, verbose_name="evidence reference"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "supplier invoice charge",
                "verbose_name_plural": "supplier invoice charges",
                "ordering": ["invoice", "line_order"],
                "permissions": [
                    ("manage_supplier_invoice_charges", "Can manage supplier invoice charges")
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceChargeAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("sequence", models.PositiveIntegerField(verbose_name="sequence")),
                (
                    "match_allocation_uid",
                    models.UUIDField(editable=False, verbose_name="match allocation uid"),
                ),
                (
                    "receipt_line_uid",
                    models.UUIDField(editable=False, verbose_name="receipt line uid"),
                ),
                (
                    "matched_base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="matched quantity snapshot"
                    ),
                ),
                (
                    "receipt_allocated_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="receipt value snapshot"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=3, max_digits=21, verbose_name="allocated landed cost"
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier invoice charge allocation",
                "verbose_name_plural": "supplier invoice charge allocations",
                "ordering": ["posting", "charge__line_order", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceChargeManualShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "amount",
                    models.DecimalField(decimal_places=3, max_digits=21, verbose_name="amount"),
                ),
            ],
            options={
                "verbose_name": "supplier invoice charge manual share",
                "verbose_name_plural": "supplier invoice charge manual shares",
                "ordering": ["charge", "match_allocation__sequence"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="supplierinvoice",
            name="procurement_invoice_charges_not_negative",
        ),
        migrations.RemoveConstraint(
            model_name="supplierinvoiceposting",
            name="procurement_posting_payable_is_the_whole_invoice",
        ),
        migrations.RemoveConstraint(
            model_name="supplierinvoiceposting",
            name="procurement_posting_values_are_not_negative",
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoice",
            name="charges_total",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=21,
                verbose_name="additional costs",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoiceposting",
            name="landed_cost_value",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=21,
                verbose_name="landed costs",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoiceposting",
            name="reversal_stock_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockledgerentry",
                verbose_name="landed-cost reversal stock entry",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoiceposting",
            name="stock_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockledgerentry",
                verbose_name="landed-cost stock entry",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoice",
            name="charges_total",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=21,
                verbose_name="additional costs",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoiceposting",
            name="landed_cost_value",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                max_digits=21,
                verbose_name="landed costs",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoiceposting",
            name="reversal_stock_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_supplier_invoice_postings",
                to="inventory.stockledgerentry",
                verbose_name="landed-cost reversal stock entry",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoiceposting",
            name="stock_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_invoice_postings",
                to="inventory.stockledgerentry",
                verbose_name="landed-cost stock entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("freight_amount__gte", 0),
                    ("discount_amount__gte", 0),
                    ("charges_total__gte", 0),
                ),
                name="procurement_invoice_charges_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoiceposting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payable_value",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("direct_charge_value"),
                                "+",
                                models.F("invoice_matched_value"),
                            ),
                            "+",
                            models.F("landed_cost_value"),
                        ),
                    )
                ),
                name="procurement_posting_payable_is_the_whole_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoiceposting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("goods_cleared_value__gte", 0),
                    ("invoice_matched_value__gte", 0),
                    ("direct_charge_value__gte", 0),
                    ("landed_cost_value__gte", 0),
                    ("payable_value__gt", 0),
                ),
                name="procurement_posting_values_are_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoiceposting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("landed_cost_value", 0), ("stock_entry__isnull", True)),
                    models.Q(("landed_cost_value__gt", 0), ("stock_entry__isnull", False)),
                    _connector="OR",
                ),
                name="procurement_posting_landed_cost_names_stock_entry",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoiceposting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reversal_stock_entry__isnull", True),
                    models.Q(("status", "REVERSED"), ("stock_entry__isnull", False)),
                    _connector="OR",
                ),
                name="procurement_posting_reversal_stock_entry_is_reversed",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicecharge",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.costcenter",
                verbose_name="cost center",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicecharge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicecharge",
            name="direct_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.account",
                verbose_name="direct account",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicecharge",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicecharge",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.supplierinvoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="control_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.account",
                verbose_name="inventory control account",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="inventory_movement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.stockmovement",
                verbose_name="inventory movement",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.inventoryitem",
                verbose_name="item",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.inventorylot",
                verbose_name="lot",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="match_allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.purchasematchallocation",
                verbose_name="match allocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="posting",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.supplierinvoiceposting",
                verbose_name="invoice posting",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="receipt_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.goodsreceiptline",
                verbose_name="receipt line",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.warehouse",
                verbose_name="warehouse",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargemanualshare",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargemanualshare",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargemanualshare",
            name="match_allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.purchasematchallocation",
                verbose_name="match allocation",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicecharge",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_invoice_charges",
                to="accounting.costcenter",
                verbose_name="cost center",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicecharge",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_supplier_invoice_charges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicecharge",
            name="direct_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_invoice_charges",
                to="accounting.account",
                verbose_name="direct account",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicecharge",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="procurement.supplierinvoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargemanualshare",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.supplierinvoicecharge",
                verbose_name="charge",
            ),
        ),
        migrations.AddField(
            model_name="historicalsupplierinvoicechargeallocation",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="procurement.supplierinvoicecharge",
                verbose_name="charge",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="procurement.supplierinvoicecharge",
                verbose_name="charge",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="control_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_landed_cost_allocations",
                to="accounting.account",
                verbose_name="inventory control account",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="inventory_movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_landed_cost_allocation",
                to="inventory.stockmovement",
                verbose_name="inventory movement",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_landed_cost_allocations",
                to="inventory.inventoryitem",
                verbose_name="item",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_landed_cost_allocations",
                to="inventory.inventorylot",
                verbose_name="lot",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="match_allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge_allocations",
                to="procurement.purchasematchallocation",
                verbose_name="match allocation",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="landed_cost_allocations",
                to="procurement.supplierinvoiceposting",
                verbose_name="invoice posting",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="receipt_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge_allocations",
                to="procurement.goodsreceiptline",
                verbose_name="receipt line",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargeallocation",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_landed_cost_allocations",
                to="inventory.warehouse",
                verbose_name="warehouse",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargemanualshare",
            name="charge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_shares",
                to="procurement.supplierinvoicecharge",
                verbose_name="charge",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargemanualshare",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_supplier_invoice_charge_shares",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoicechargemanualshare",
            name="match_allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charge_manual_shares",
                to="procurement.purchasematchallocation",
                verbose_name="match allocation",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierinvoicecharge",
            index=models.Index(fields=["invoice", "treatment"], name="sinv_charge_treatment_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicecharge",
            constraint=models.UniqueConstraint(
                fields=("invoice", "line_order"), name="procurement_invoice_charge_order_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicecharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="procurement_invoice_charge_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicecharge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cost_center__isnull", False),
                        ("direct_account__isnull", False),
                        ("treatment", "DIRECT_EXPENSE"),
                    ),
                    models.Q(
                        ("cost_center__isnull", True),
                        ("direct_account__isnull", True),
                        ("treatment", "LANDED_COST"),
                    ),
                    _connector="OR",
                ),
                name="procurement_invoice_charge_treatment_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicechargeallocation",
            constraint=models.UniqueConstraint(
                fields=("posting", "charge", "sequence"),
                name="procurement_landed_allocation_sequence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicechargeallocation",
            constraint=models.UniqueConstraint(
                fields=("posting", "charge", "match_allocation"),
                name="procurement_landed_allocation_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicechargeallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("matched_base_quantity__gt", 0),
                    ("receipt_allocated_value__gte", 0),
                    ("allocated_amount__gt", 0),
                ),
                name="procurement_landed_allocation_values_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicechargemanualshare",
            constraint=models.UniqueConstraint(
                fields=("charge", "match_allocation"),
                name="procurement_charge_manual_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoicechargemanualshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="procurement_charge_manual_share_positive",
            ),
        ),
        migrations.RunSQL(
            sql=CHARGE_GUARDS + POSTING_GUARD_WITH_STOCK,
            reverse_sql=DROP_CHARGE_GUARDS + POSTING_GUARD_WITHOUT_STOCK,
        ),
    ]
