# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0039_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsupplier',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalsuppliercreditterm',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='suppliercreditterm',
            name='name_en',
        ),
    ]
