# Generated by Django 5.2.17 on 2026-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0040_remove_historicalsupplier_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalsuppliercreditterm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='suppliercreditterm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
