# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_roledefinition_options'),
        ('procurement', '0041_alter_historicalsupplier_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplier',
            name='procurement_supplier_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='suppliercreditterm',
            name='procurement_credit_term_name_ar_not_empty',
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='procurement_supplier_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditterm',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='procurement_credit_term_name_ar_not_empty'),
        ),
    ]
