"""
Two supplier terms the reports needed and the model did not carry.

`minimum_settlement_percent` is how much of an invoice must be paid by the day
it falls due. Nullable, because most arrangements state no such floor and a
default of zero would claim they had agreed to one. Two constraints keep it
honest: between 0 and 100, and only where a payment term gives it a due date
to be measured against.

`balance_reset_date` is the day the account starts again. It changes what the
statement *shows*, never what the ledger *holds*: everything before the date is
summed into one opening line, and every document stays exactly where it is.

Both are additive and nullable, so every existing supplier keeps working with
nothing said about either.
"""

# Generated by Django 5.2.17 on 2026-08-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_roledefinition_options'),
        ('procurement', '0042_remove_supplier_procurement_supplier_name_ar_not_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='balance_reset_date',
            field=models.DateField(blank=True, null=True, verbose_name='balance reset date'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='minimum_settlement_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='minimum settlement percent'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance_reset_date',
            field=models.DateField(blank=True, null=True, verbose_name='balance reset date'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_settlement_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='minimum settlement percent'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_settlement_percent__isnull', True), models.Q(('minimum_settlement_percent__gte', 0), ('minimum_settlement_percent__lte', 100)), _connector='OR'), name='procurement_supplier_settlement_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_settlement_percent__isnull', True), ('payment_terms_days__gt', 0), _connector='OR'), name='procurement_supplier_settlement_needs_terms'),
        ),
    ]
