"""
The supplier payment cycle, and the invoice's link to it.

A supplier is bought from continuously and settled periodically, so a due date
computed per invoice described nobody's arrangement. The cycle is the window:
opened by the first invoice, due that invoice's date plus the terms, and shared
by every invoice raised into it — an invoice a week later is due on the same
day with a week less to run.

`SupplierInvoice.cycle` is nullable because the invoices that predate this
migration have no cycle and must not be given one retroactively. Their
`due_date` was computed per invoice and stays exactly as it was: assigning them
to cycles would restate what was late, which is the one thing a due date may
never do.
"""

# Generated by Django 5.2.17 on 2026-08-27 23:39

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_roledefinition_options'),
        ('procurement', '0043_supplier_settlement_floor_and_reset_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplierPaymentCycle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('SETTLED', 'مسدَّدة')], default='OPEN', max_length=16, verbose_name='status')),
                ('opened_on', models.DateField(verbose_name='opened on')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('payment_terms_days', models.PositiveSmallIntegerField(verbose_name='payment terms (days)')),
                ('minimum_settlement_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='minimum settlement percent')),
                ('settled_on', models.DateField(blank=True, null=True, verbose_name='settled on')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'historical supplier payment cycle',
                'verbose_name_plural': 'historical supplier payment cycles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SupplierPaymentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوحة'), ('SETTLED', 'مسدَّدة')], default='OPEN', max_length=16, verbose_name='status')),
                ('opened_on', models.DateField(verbose_name='opened on')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('payment_terms_days', models.PositiveSmallIntegerField(verbose_name='payment terms (days)')),
                ('minimum_settlement_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='minimum settlement percent')),
                ('settled_on', models.DateField(blank=True, null=True, verbose_name='settled on')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_cycles', to='organizations.organization', verbose_name='organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_cycles', to='procurement.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'supplier payment cycle',
                'verbose_name_plural': 'supplier payment cycles',
                'ordering': ['supplier__code', '-sequence'],
            },
        ),
        migrations.AddField(
            model_name='historicalsupplierinvoice',
            name='cycle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procurement.supplierpaymentcycle', verbose_name='payment cycle'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.supplierpaymentcycle', verbose_name='payment cycle'),
        ),
        migrations.AddIndex(
            model_name='supplierpaymentcycle',
            index=models.Index(fields=['organization', 'status', 'due_date'], name='supplier_cycle_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.UniqueConstraint(fields=('supplier', 'sequence'), name='procurement_cycle_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('supplier',), name='procurement_cycle_one_open_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('opened_on'))), name='procurement_cycle_period_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('settled_on__isnull', True), ('status', 'OPEN')), models.Q(('settled_on__isnull', False), ('status', 'SETTLED')), _connector='OR'), name='procurement_cycle_settled_iff_dated'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_settlement_percent__isnull', True), models.Q(('minimum_settlement_percent__gte', 0), ('minimum_settlement_percent__lte', 100)), _connector='OR'), name='procurement_cycle_settlement_percent_range'),
        ),
    ]
