"""
The cycle gains its middle state.

`0044` gave a cycle two states — open or settled — and a unique index allowing
one open cycle per supplier. Both were right on their own and wrong together:
a window that passes its due date must *stop taking invoices* without
*closing*, because the unpaid balance is exactly what the reports exist to
show. Two states forced those into one flag, and the first invoice raised after
a due date hit the index.

So: `COLLECTING` is the window new invoices join, `DUE` is one that has stopped
taking them and has not been paid, `SETTLED` is paid. The uniqueness moves to
`COLLECTING`, where it belongs — a supplier whose account has run late for
months has one `DUE` window per month, and a rule against that would hide the
debt rather than prevent it.

No data migration: `0044` shipped nowhere, and a status of `OPEN` therefore
exists in no database. Were one to exist it would mean `COLLECTING`.
"""

# Generated by Django 5.2.17 on 2026-08-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_roledefinition_options'),
        ('procurement', '0044_supplier_payment_cycles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierpaymentcycle',
            name='procurement_cycle_one_open_per_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='supplierpaymentcycle',
            name='procurement_cycle_settled_iff_dated',
        ),
        migrations.AlterField(
            model_name='historicalsupplierpaymentcycle',
            name='status',
            field=models.CharField(choices=[('COLLECTING', 'مفتوحة للفواتير'), ('DUE', 'مستحقة'), ('SETTLED', 'مسدَّدة')], default='COLLECTING', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='supplierpaymentcycle',
            name='status',
            field=models.CharField(choices=[('COLLECTING', 'مفتوحة للفواتير'), ('DUE', 'مستحقة'), ('SETTLED', 'مسدَّدة')], default='COLLECTING', max_length=16, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'COLLECTING')), fields=('supplier',), name='procurement_cycle_one_collecting_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierpaymentcycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('settled_on__isnull', False), ('status', 'SETTLED')), models.Q(models.Q(('status', 'SETTLED'), _negated=True), ('settled_on__isnull', True)), _connector='OR'), name='procurement_cycle_settled_iff_dated'),
        ),
    ]
