# Generated by Django 5.2.17 on 2026-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecipe',
            name='last_version_number',
            field=models.PositiveIntegerField(default=0, verbose_name='last version number'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_version_number',
            field=models.PositiveIntegerField(default=0, verbose_name='last version number'),
        ),
    ]
