# Generated by Django 5.2.17 on 2026-08-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_procurement_import_kinds'),
        ('kitchen', '0002_historicalrecipe_last_version_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipelinesubstitute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('line', 'priority'), name='recipe_substitute_priority_unique_per_line'),
        ),
        migrations.AddConstraint(
            model_name='recipelinesubstitute',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gt', 0)), name='recipe_substitute_priority_is_positive'),
        ),
    ]
