# Generated by Django 5.2.17 on 2026-08-16 10:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_recipelinesubstitute_recipe_substitute_priority_unique_per_line_and_more'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('units', '0002_historicalunitofmeasure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecipeVersionBranchScope',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('is_organization_wide', models.BooleanField(default=False, verbose_name='organization-wide')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical recipe version branch scope',
                'verbose_name_plural': 'historical recipe version branch scopes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecipeVersionReview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('review_type', models.CharField(choices=[('KITCHEN', 'مراجعة المطبخ'), ('STOREKEEPER', 'مراجعة المخزن'), ('ACCOUNTING', 'مراجعة الكلفة'), ('FINAL', 'الاعتماد النهائي')], max_length=12, verbose_name='review')),
                ('decision', models.CharField(choices=[('APPROVED', 'موافقة'), ('REJECTED', 'رفض')], max_length=8, verbose_name='decision')),
                ('reviewed_at', models.DateTimeField(verbose_name='reviewed at')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('evidence_reference', models.CharField(blank=True, max_length=120, verbose_name='evidence reference')),
                ('evidence_kind', models.CharField(blank=True, choices=[('SIGNED_FORM', 'نموذج اعتماد موقّع'), ('DEMO_FICTIONAL', 'دليل تجريبي — غير حقيقي')], max_length=16, verbose_name='evidence kind')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical recipe version review',
                'verbose_name_plural': 'historical recipe version reviews',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecipeVersionBranchScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('is_organization_wide', models.BooleanField(default=False, verbose_name='organization-wide')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
            ],
            options={
                'verbose_name': 'recipe version branch scope',
                'verbose_name_plural': 'recipe version branch scopes',
                'ordering': ['recipe', 'branch', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('review_type', models.CharField(choices=[('KITCHEN', 'مراجعة المطبخ'), ('STOREKEEPER', 'مراجعة المخزن'), ('ACCOUNTING', 'مراجعة الكلفة'), ('FINAL', 'الاعتماد النهائي')], max_length=12, verbose_name='review')),
                ('decision', models.CharField(choices=[('APPROVED', 'موافقة'), ('REJECTED', 'رفض')], max_length=8, verbose_name='decision')),
                ('reviewed_at', models.DateTimeField(verbose_name='reviewed at')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('evidence_reference', models.CharField(blank=True, max_length=120, verbose_name='evidence reference')),
                ('evidence_kind', models.CharField(blank=True, choices=[('SIGNED_FORM', 'نموذج اعتماد موقّع'), ('DEMO_FICTIONAL', 'دليل تجريبي — غير حقيقي')], max_length=16, verbose_name='evidence kind')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
            ],
            options={
                'verbose_name': 'recipe version review',
                'verbose_name_plural': 'recipe version reviews',
                'ordering': ['version', 'review_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('manage_recipe', 'Can create, edit and archive recipes'), ('view_recipe_cost', 'Can view recipe cost columns'), ('submit_recipe_version', 'Can submit a draft version for review'), ('review_recipe_version', 'Can record a review signoff on a submitted version'), ('approve_recipe_version', 'Can give the final approval of a version'), ('reject_recipe_version', 'Can refuse a submitted version'), ('activate_recipe_version', 'Can put an approved version into effect')], 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
        migrations.RemoveConstraint(
            model_name='recipeversion',
            name='recipe_version_task_3_1_draft_only',
        ),
        migrations.RemoveConstraint(
            model_name='recipeversion',
            name='recipe_version_one_draft_per_recipe',
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activated at'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='activated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='activated by'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='approval_evidence_kind',
            field=models.CharField(blank=True, choices=[('SIGNED_FORM', 'نموذج اعتماد موقّع'), ('DEMO_FICTIONAL', 'دليل تجريبي — غير حقيقي')], max_length=16, verbose_name='approval evidence'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='approval_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='approval reference'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='effective from'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='effective to'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rejected at'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='rejected by'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='superseded at'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversion',
            name='superseded_by_version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeversion', verbose_name='superseded by'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activated at'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions_activated', to=settings.AUTH_USER_MODEL, verbose_name='activated by'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approval_evidence_kind',
            field=models.CharField(blank=True, choices=[('SIGNED_FORM', 'نموذج اعتماد موقّع'), ('DEMO_FICTIONAL', 'دليل تجريبي — غير حقيقي')], max_length=16, verbose_name='approval evidence'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approval_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='approval reference'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='effective from'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='effective to'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rejected at'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions_rejected', to=settings.AUTH_USER_MODEL, verbose_name='rejected by'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='rejection reason'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_versions_submitted', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='superseded at'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='superseded_by_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='kitchen.recipeversion', verbose_name='superseded by'),
        ),
        migrations.AlterField(
            model_name='historicalrecipeversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسلة للمراجعة'), ('APPROVED', 'معتمدة'), ('ACTIVE', 'سارية'), ('REJECTED', 'مرفوضة'), ('SUPERSEDED', 'مستبدلة')], default='DRAFT', max_length=12, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='recipeversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مُرسلة للمراجعة'), ('APPROVED', 'معتمدة'), ('ACTIVE', 'سارية'), ('REJECTED', 'مرفوضة'), ('SUPERSEDED', 'مستبدلة')], default='DRAFT', max_length=12, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['recipe', 'status'], name='recipe_version_status_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeversion',
            index=models.Index(fields=['status', 'effective_from'], name='recipe_version_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED'])), fields=('recipe',), name='recipe_version_one_open_per_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), ('created_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='recipe_version_approver_is_not_the_author'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), ('submitted_by__isnull', True), models.Q(('approved_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='recipe_version_approver_is_not_the_submitter'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['ACTIVE', 'APPROVED', 'SUPERSEDED']), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False), models.Q(('approval_reference', ''), _negated=True), models.Q(('approval_evidence_kind', ''), _negated=True)), _connector='OR'), name='recipe_version_approval_carries_its_evidence'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUBMITTED'), _negated=True), models.Q(('submitted_by__isnull', False), ('submitted_at__isnull', False)), _connector='OR'), name='recipe_version_submission_names_its_actor'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejected_by__isnull', False), ('rejected_at__isnull', False), models.Q(('rejection_reason', ''), _negated=True)), _connector='OR'), name='recipe_version_rejection_carries_its_reason'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['ACTIVE', 'SUPERSEDED']), _negated=True), models.Q(('effective_from__isnull', False), ('activated_by__isnull', False), ('activated_at__isnull', False)), _connector='OR'), name='recipe_version_effective_range_starts_at_activation'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('effective_from__isnull', False), ('effective_to__gte', models.F('effective_from'))), _connector='OR'), name='recipe_version_effective_range_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'SUPERSEDED'), _negated=True), models.Q(('superseded_at__isnull', False), ('superseded_by_version__isnull', False), ('effective_to__isnull', False)), _connector='OR'), name='recipe_version_supersession_names_its_replacement'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.CheckConstraint(condition=models.Q(('superseded_by_version__isnull', True), models.Q(('superseded_by_version', models.F('id')), _negated=True), _connector='OR'), name='recipe_version_is_not_its_own_replacement'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionbranchscope',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionbranchscope',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionbranchscope',
            name='recipe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipe', verbose_name='recipe'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionbranchscope',
            name='version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeversion', verbose_name='version'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionreview',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AddField(
            model_name='historicalrecipeversionreview',
            name='version',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeversion', verbose_name='version'),
        ),
        migrations.AddField(
            model_name='recipeversionbranchscope',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_version_scopes', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='recipeversionbranchscope',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_scopes', to='kitchen.recipe', verbose_name='recipe'),
        ),
        migrations.AddField(
            model_name='recipeversionbranchscope',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_scopes', to='kitchen.recipeversion', verbose_name='version'),
        ),
        migrations.AddField(
            model_name='recipeversionreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_version_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
        ),
        migrations.AddField(
            model_name='recipeversionreview',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='kitchen.recipeversion', verbose_name='version'),
        ),
        migrations.AddIndex(
            model_name='recipeversionbranchscope',
            index=models.Index(fields=['recipe', 'branch', 'effective_from'], name='recipe_scope_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionbranchscope',
            constraint=models.UniqueConstraint(fields=('version', 'branch'), name='recipe_scope_one_row_per_version_and_branch'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionbranchscope',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='recipe_scope_range_is_ordered'),
        ),
        migrations.AddIndex(
            model_name='recipeversionreview',
            index=models.Index(fields=['version', 'decision'], name='recipe_review_decision_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionreview',
            constraint=models.UniqueConstraint(fields=('version', 'review_type'), name='recipe_review_one_per_type_per_version'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'REJECTED'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='recipe_review_refusal_carries_its_reason'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'APPROVED'), ('review_type', 'ACCOUNTING'), _negated=True), models.Q(models.Q(('evidence_reference', ''), _negated=True), models.Q(('evidence_kind', ''), _negated=True)), _connector='OR'), name='recipe_review_costing_names_its_evidence'),
        ),
    ]
