# Generated by Django 5.2.17 on 2026-08-16 15:58

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_recipe_version_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecipeComponent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('source_document', models.CharField(blank=True, max_length=200, verbose_name='source document')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='source page')),
                ('source_sha256', models.CharField(blank=True, max_length=64, verbose_name='source SHA-256')),
                ('source_reference', models.CharField(blank=True, max_length=120, verbose_name='source reference')),
                ('source_note', models.TextField(blank=True, verbose_name='source note')),
                ('line_order', models.PositiveIntegerField(verbose_name='line order')),
                ('multiplier', models.DecimalField(decimal_places=12, max_digits=24, verbose_name='multiplier')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('component_recipe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipe', verbose_name='component recipe')),
                ('component_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeversion', verbose_name='component version')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipe', verbose_name='recipe')),
                ('version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'historical recipe component',
                'verbose_name_plural': 'historical recipe components',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source_document', models.CharField(blank=True, max_length=200, verbose_name='source document')),
                ('source_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='source page')),
                ('source_sha256', models.CharField(blank=True, max_length=64, verbose_name='source SHA-256')),
                ('source_reference', models.CharField(blank=True, max_length=120, verbose_name='source reference')),
                ('source_note', models.TextField(blank=True, verbose_name='source note')),
                ('line_order', models.PositiveIntegerField(verbose_name='line order')),
                ('multiplier', models.DecimalField(decimal_places=12, max_digits=24, verbose_name='multiplier')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('component_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_as_component', to='kitchen.recipe', verbose_name='component recipe')),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_by_components', to='kitchen.recipeversion', verbose_name='component version')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_components_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_uses', to='kitchen.recipe', verbose_name='recipe')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='kitchen.recipeversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'recipe component',
                'verbose_name_plural': 'recipe components',
                'ordering': ['version', 'line_order'],
                'indexes': [models.Index(fields=['component_version'], name='recipe_component_child_idx'), models.Index(fields=['component_recipe'], name='recipe_component_child_rcp_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'line_order'), name='recipe_component_order_unique_per_version'), models.UniqueConstraint(fields=('version', 'component_recipe'), name='recipe_component_child_recipe_unique_per_version'), models.CheckConstraint(condition=models.Q(('multiplier__gt', Decimal('0'))), name='recipe_component_multiplier_is_positive'), models.CheckConstraint(condition=models.Q(('line_order__gt', 0)), name='recipe_component_order_is_positive'), models.CheckConstraint(condition=models.Q(('component_version', models.F('version')), _negated=True), name='recipe_component_is_not_its_own_parent'), models.CheckConstraint(condition=models.Q(('component_recipe', models.F('recipe')), _negated=True), name='recipe_component_recipe_is_not_its_own_parent'), models.CheckConstraint(condition=models.Q(models.Q(('source_document', ''), ('source_page__isnull', True)), models.Q(models.Q(('source_document', ''), _negated=True), ('source_page__isnull', False)), _connector='OR'), name='recipe_component_provenance_is_complete')],
            },
        ),
    ]
