# Generated by Django 5.2.17 on 2026-08-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_production_batch_guards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionbatch',
            options={'ordering': ['-planned_business_date', '-id'], 'permissions': [('create_production_batch', 'Can draft and edit production batches')], 'verbose_name': 'production batch', 'verbose_name_plural': 'production batches'},
        ),
    ]
