# Generated by Django 5.2.17 on 2026-08-17 16:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_procurement_import_kinds'),
        ('kitchen', '0012_production_batch_permissions'),
        ('units', '0002_historicalunitofmeasure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionbatchactualline',
            name='production_actual_package_carries_its_factor',
        ),
        migrations.AddConstraint(
            model_name='productionbatchactualline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__isnull', False)), name='production_actual_carries_its_factor'),
        ),
        migrations.AddConstraint(
            model_name='productionbatchactualline',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gt', Decimal('0'))), name='production_actual_factor_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionbatchactualline',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'PRIMARY')), fields=('line',), name='production_actual_one_primary_per_line'),
        ),
        migrations.AddConstraint(
            model_name='productionbatchactualline',
            constraint=models.UniqueConstraint(condition=models.Q(('substitute__isnull', False)), fields=('line', 'substitute'), name='production_actual_one_row_per_substitute'),
        ),
    ]
