# Generated by Django 5.2.17 on 2026-08-18 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0018_production_posting_guards'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=32, verbose_name='document type')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='last number')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_sequences', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'kitchen document sequence',
                'verbose_name_plural': 'kitchen document sequences',
                'constraints': [models.UniqueConstraint(fields=('organization', 'document_type', 'year'), name='kitchen_sequence_unique_per_type_and_year')],
            },
        ),
    ]
