# Generated by Django 5.2.17 on 2026-08-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0019_kitchen_document_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('manage_recipe', 'Can create, edit and archive recipes'), ('view_recipe_cost', 'Can view recipe cost columns'), ('view_kitchen_report', 'Can view the kitchen report family'), ('submit_recipe_version', 'Can submit a draft version for review'), ('review_recipe_version', 'Can record a review signoff on a submitted version'), ('approve_recipe_version', 'Can give the final approval of a version'), ('reject_recipe_version', 'Can refuse a submitted version'), ('activate_recipe_version', 'Can put an approved version into effect')], 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
    ]
