# Generated by Django 5.2.17 on 2026-08-18 15:27

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0020_kitchen_report_permission'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('meal_type', models.CharField(choices=[('STAFF', 'وجبة موظفين'), ('COMPLIMENTARY', 'وجبة مجانية')], max_length=16, verbose_name='meal type')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='quantity')),
                ('output_base_quantity', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='output quantity')),
                ('output_unit_code', models.CharField(max_length=16, verbose_name='output unit')),
                ('consumed_on', models.DateField(verbose_name='consumed on')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='beneficiary or shift')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('RECORDED', 'مسجلة'), ('CANCELLED', 'ملغاة')], default='RECORDED', max_length=12, verbose_name='status')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(max_length=64, verbose_name='request fingerprint')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_records', to='organizations.branch', verbose_name='branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_records_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_records', to='organizations.organization', verbose_name='organization')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_records', to='kitchen.recipe', verbose_name='recipe')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_records', to='kitchen.recipeversion', verbose_name='recipe version')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_records_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='kitchen.mealrecord', verbose_name='replaces')),
                ('serving', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_records', to='kitchen.recipeserving', verbose_name='serving')),
            ],
            options={
                'verbose_name': 'meal record',
                'verbose_name_plural': 'meal records',
                'ordering': ['-consumed_on', '-id'],
                'permissions': [('record_meal', 'Can record and cancel staff and complimentary meals')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMealRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('meal_type', models.CharField(choices=[('STAFF', 'وجبة موظفين'), ('COMPLIMENTARY', 'وجبة مجانية')], max_length=16, verbose_name='meal type')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='quantity')),
                ('output_base_quantity', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='output quantity')),
                ('output_unit_code', models.CharField(max_length=16, verbose_name='output unit')),
                ('consumed_on', models.DateField(verbose_name='consumed on')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='beneficiary or shift')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('RECORDED', 'مسجلة'), ('CANCELLED', 'ملغاة')], default='RECORDED', max_length=12, verbose_name='status')),
                ('recorded_at', models.DateTimeField(blank=True, editable=False, verbose_name='recorded at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(max_length=64, verbose_name='request fingerprint')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('recipe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipe', verbose_name='recipe')),
                ('recipe_version', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeversion', verbose_name='recipe version')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('serving', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.recipeserving', verbose_name='serving')),
                ('replaces', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.mealrecord', verbose_name='replaces')),
            ],
            options={
                'verbose_name': 'historical meal record',
                'verbose_name_plural': 'historical meal records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='mealrecord',
            index=models.Index(fields=['organization', 'consumed_on'], name='meal_record_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mealrecord',
            index=models.Index(fields=['branch', 'meal_type'], name='meal_record_branch_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealrecord',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='meal_record_key_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='mealrecord',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='meal_record_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='mealrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='meal_record_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='mealrecord',
            constraint=models.CheckConstraint(condition=models.Q(('output_base_quantity__gt', Decimal('0'))), name='meal_record_output_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='mealrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(('status', 'RECORDED'), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='meal_record_cancellation_evidence_is_complete'),
        ),
    ]
