# Generated by Django 5.2.17 on 2026-08-18 16:11

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_procurement_import_kinds'),
        ('kitchen', '0021_meal_records'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBatchDocumentLink',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('link_type', models.CharField(choices=[('CUSTODY_RETURN_CONTEXT', 'سياق إرجاع عهدة'), ('ABNORMAL_WASTE_CONTEXT', 'سياق هالك غير طبيعي')], max_length=24, verbose_name='link type')),
                ('attributed_quantity', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='attributed quantity')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('status', models.CharField(choices=[('ACTIVE', 'سارٍ'), ('CANCELLED', 'ملغى')], default='ACTIVE', max_length=12, verbose_name='status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('actual_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.productionbatchactualline', verbose_name='actual line')),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.productionbatch', verbose_name='production batch')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('cancelled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item')),
                ('line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kitchen.productionbatchline', verbose_name='requirement')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('transfer_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stocktransferline', verbose_name='transfer line')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='kitchen warehouse')),
                ('waste_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorymovementdocumentline', verbose_name='waste line')),
            ],
            options={
                'verbose_name': 'historical batch document link',
                'verbose_name_plural': 'historical batch document links',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BatchDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('link_type', models.CharField(choices=[('CUSTODY_RETURN_CONTEXT', 'سياق إرجاع عهدة'), ('ABNORMAL_WASTE_CONTEXT', 'سياق هالك غير طبيعي')], max_length=24, verbose_name='link type')),
                ('attributed_quantity', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='attributed quantity')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('status', models.CharField(choices=[('ACTIVE', 'سارٍ'), ('CANCELLED', 'ملغى')], default='ACTIVE', max_length=12, verbose_name='status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.CharField(blank=True, max_length=200, verbose_name='cancellation reason')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('actual_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='kitchen.productionbatchactualline', verbose_name='actual line')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='kitchen.productionbatch', verbose_name='production batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_document_links', to='organizations.branch', verbose_name='branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_document_links_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_document_links_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_batch_links', to='inventory.inventoryitem', verbose_name='item')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_links', to='kitchen.productionbatchline', verbose_name='requirement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_document_links', to='organizations.organization', verbose_name='organization')),
                ('transfer_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_batch_links', to='inventory.stocktransferline', verbose_name='transfer line')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_batch_document_links', to='inventory.warehouse', verbose_name='kitchen warehouse')),
                ('waste_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_batch_links', to='inventory.inventorymovementdocumentline', verbose_name='waste line')),
            ],
            options={
                'verbose_name': 'batch document link',
                'verbose_name_plural': 'batch document links',
                'ordering': ['-created_at', '-id'],
                'permissions': [('link_batch_document', 'Can attribute an inventory document to a production batch')],
                'indexes': [models.Index(fields=['warehouse', 'link_type'], name='batch_link_wh_type_idx'), models.Index(fields=['batch', 'status'], name='batch_link_batch_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('link_type', 'CUSTODY_RETURN_CONTEXT'), ('transfer_line__isnull', False), ('waste_line__isnull', True)), models.Q(('link_type', 'ABNORMAL_WASTE_CONTEXT'), ('transfer_line__isnull', True), ('waste_line__isnull', False)), _connector='OR'), name='batch_document_link_source_matches_type'), models.CheckConstraint(condition=models.Q(('line__isnull', True), ('actual_line__isnull', True), _connector='OR'), name='batch_document_link_batch_target_is_single'), models.CheckConstraint(condition=models.Q(('attributed_quantity__gt', Decimal('0'))), name='batch_document_link_quantity_is_positive'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='batch_document_link_reason_is_given'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(('status', 'ACTIVE'), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='batch_document_link_cancellation_evidence_is_complete'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('batch', 'transfer_line'), name='batch_document_link_transfer_once_per_batch'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('batch', 'waste_line'), name='batch_document_link_waste_once_per_batch')],
            },
        ),
    ]
