# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0024_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecipe',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalrecipecategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalrecipeserving',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipecostsnapshotserving',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipeserving',
            name='name_en',
        ),
    ]
