# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_inventoryitem_inventory_item_name_ar_not_empty_and_more'),
        ('kitchen', '0026_alter_historicalrecipe_name_and_more'),
        ('organizations', '0011_alter_roledefinition_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='recipecategory',
            name='recipe_category_name_ar_not_empty',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='recipe_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='recipecategory',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='recipe_category_name_ar_not_empty'),
        ),
    ]
