# Generated by Django 5.2.17 on 2026-08-08 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_historicalbranch_historicalbranchmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='occurred at')),
                ('action', models.CharField(choices=[('CREATED', 'إنشاء'), ('UPDATED', 'تعديل'), ('DEACTIVATED', 'إيقاف'), ('SUBMITTED', 'إرسال'), ('APPROVED', 'اعتماد'), ('REJECTED', 'رفض'), ('POSTED', 'ترحيل'), ('POSTING_FAILED', 'فشل الترحيل'), ('REVERSED', 'عكس القيد'), ('PERIOD_CLOSED', 'إقفال فترة'), ('PERIOD_REOPENED', 'إعادة فتح فترة'), ('ACCESS_GRANTED', 'منح صلاحية'), ('ACCESS_REVOKED', 'سحب صلاحية'), ('IMPORTED', 'استيراد'), ('PERMISSION_OVERRIDE', 'تجاوز صلاحية')], max_length=32, verbose_name='action')),
                ('actor_label', models.CharField(blank=True, help_text='Who the actor was at the time, kept even if they are later renamed.', max_length=200, verbose_name='actor label')),
                ('correlation_id', models.UUIDField(db_index=True, help_text='Groups every event produced by one request or job.', verbose_name='correlation id')),
                ('target_type', models.CharField(help_text='app_label.ModelName of the thing acted upon.', max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='target id')),
                ('previous_state', models.JSONField(blank=True, null=True, verbose_name='previous state')),
                ('new_state', models.JSONField(blank=True, null=True, verbose_name='new state')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('source_document_type', models.CharField(blank=True, max_length=100, verbose_name='source document type')),
                ('source_document_id', models.CharField(blank=True, max_length=64, verbose_name='source document id')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system actions such as a scheduled job.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_action_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_type', ''), _negated=True), name='audit_target_type_not_empty')],
            },
        ),
    ]
