# Generated by Django 5.2.17 on 2026-08-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditevent_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'إنشاء'), ('UPDATED', 'تعديل'), ('DELETED', 'حذف'), ('DEACTIVATED', 'إيقاف'), ('SUBMITTED', 'إرسال'), ('APPROVED', 'اعتماد'), ('REJECTED', 'رفض'), ('POSTED', 'ترحيل'), ('POSTING_FAILED', 'فشل الترحيل'), ('REVERSED', 'عكس القيد'), ('PERIOD_CLOSED', 'إقفال فترة'), ('PERIOD_REOPENED', 'إعادة فتح فترة'), ('ACCESS_GRANTED', 'منح صلاحية'), ('ACCESS_REVOKED', 'سحب صلاحية'), ('IMPORTED', 'استيراد'), ('PERMISSION_OVERRIDE', 'تجاوز صلاحية')], max_length=32, verbose_name='action'),
        ),
    ]
