# Generated by Django 5.2.17 on 2026-08-26 06:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_audit_action_document_downloaded'),
        ('organizations', '0007_accesschangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_type', models.CharField(max_length=100, verbose_name='event type')),
                ('idempotency_key', models.CharField(max_length=200, verbose_name='idempotency key')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='payload hash')),
                ('correlation_id', models.UUIDField(db_index=True, verbose_name='correlation id')),
                ('source_type', models.CharField(blank=True, max_length=100, verbose_name='source type')),
                ('source_id', models.CharField(blank=True, max_length=64, verbose_name='source id')),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار المعالجة'), ('PROCESSING', 'قيد المعالجة'), ('RETRY', 'إعادة محاولة'), ('COMPLETED', 'مكتملة'), ('DEAD_LETTER', 'فشلت نهائياً')], db_index=True, default='PENDING', max_length=16, verbose_name='status')),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='available at')),
                ('claimed_by', models.UUIDField(blank=True, null=True, verbose_name='claimed by worker')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='claimed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='attempt count')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_outbox_events', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_automation_outbox_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_outbox_events', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'automation outbox event',
                'verbose_name_plural': 'automation outbox events',
                'ordering': ('available_at', 'id'),
                'permissions': [('view_automation_outbox', 'Can view automation outbox and dead letters'), ('replay_automation_outbox', 'Can replay a dead-letter automation event')],
            },
        ),
        migrations.CreateModel(
            name='AutomationOutboxAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='attempt number')),
                ('worker_id', models.UUIDField(default=uuid.uuid4, verbose_name='worker id')),
                ('status', models.CharField(choices=[('PROCESSING', 'قيد المعالجة'), ('SUCCEEDED', 'نجحت'), ('FAILED', 'فشلت'), ('ABANDONED', 'توقفت بعد انقطاع العامل')], max_length=16, verbose_name='status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.automationoutboxevent', verbose_name='outbox event')),
            ],
            options={
                'verbose_name': 'automation outbox attempt',
                'verbose_name_plural': 'automation outbox attempts',
                'ordering': ('event', 'attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='AutomationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('scope_key', models.CharField(max_length=32, verbose_name='scope key')),
                ('code', models.CharField(max_length=100, verbose_name='exception code')),
                ('target_type', models.CharField(max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(max_length=64, verbose_name='target id')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='amount')),
                ('severity', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('CRITICAL', 'حرجة')], max_length=12, verbose_name='severity')),
                ('is_blocking', models.BooleanField(default=False, verbose_name='blocks controlled posting or close')),
                ('sensitivity', models.CharField(choices=[('OPERATIONAL', 'تشغيلية'), ('FINANCIAL', 'مالية'), ('HR_RESTRICTED', 'موارد بشرية مقيدة')], default='OPERATIONAL', max_length=16, verbose_name='data sensitivity')),
                ('owner_role', models.CharField(blank=True, max_length=64, verbose_name='owner role')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('status', models.CharField(choices=[('OPEN', 'مفتوح'), ('RESOLVED', 'محلول')], db_index=True, default='OPEN', max_length=12, verbose_name='status')),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='first detected at')),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last detected at')),
                ('seen_count', models.PositiveIntegerField(default=1, verbose_name='times detected')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution', models.TextField(blank=True, verbose_name='resolution')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_exceptions', to='organizations.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_exceptions', to='organizations.organization', verbose_name='organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_automation_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='owner user')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='core.automationoutboxevent', verbose_name='source event')),
            ],
            options={
                'verbose_name': 'automation exception',
                'verbose_name_plural': 'automation exceptions',
                'ordering': ('-is_blocking', '-last_detected_at', '-id'),
                'permissions': [('view_automation_exception', 'Can view automation exceptions')],
            },
        ),
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('task_type', models.CharField(max_length=100, verbose_name='task type')),
                ('deduplication_key', models.CharField(max_length=240, verbose_name='deduplication key')),
                ('target_type', models.CharField(max_length=100, verbose_name='target type')),
                ('target_id', models.CharField(max_length=64, verbose_name='target id')),
                ('severity', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('CRITICAL', 'حرجة')], max_length=12, verbose_name='severity')),
                ('sensitivity', models.CharField(choices=[('OPERATIONAL', 'تشغيلية'), ('FINANCIAL', 'مالية'), ('HR_RESTRICTED', 'موارد بشرية مقيدة')], default='OPERATIONAL', max_length=16, verbose_name='data sensitivity')),
                ('title', models.CharField(max_length=240, verbose_name='title')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('assignee_role', models.CharField(blank=True, max_length=64, verbose_name='assignee role')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='due at')),
                ('status', models.CharField(choices=[('OPEN', 'جديدة'), ('ACKNOWLEDGED', 'تم الاستلام'), ('RESOLVED', 'محلولة'), ('CANCELLED', 'ملغاة')], db_index=True, default='OPEN', max_length=16, verbose_name='status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution', models.TextField(blank=True, verbose_name='resolution')),
                ('escalation_count', models.PositiveSmallIntegerField(default=0, verbose_name='escalation count')),
                ('last_escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='last escalated at')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_automation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged by')),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_automation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assignee user')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_tasks', to='organizations.branch', verbose_name='branch')),
                ('exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.automationexception', verbose_name='exception')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_tasks', to='organizations.organization', verbose_name='organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_automation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.automationoutboxevent', verbose_name='source event')),
            ],
            options={
                'verbose_name': 'automation task',
                'verbose_name_plural': 'automation tasks',
                'ordering': ('-severity', 'due_at', '-created_at'),
                'permissions': [('view_automation_task', 'Can view automation task inbox'), ('acknowledge_automation_task', 'Can acknowledge automation tasks')],
            },
        ),
        migrations.AddIndex(
            model_name='automationoutboxevent',
            index=models.Index(fields=['status', 'available_at'], name='outbox_due_message_idx'),
        ),
        migrations.AddIndex(
            model_name='automationoutboxevent',
            index=models.Index(fields=['organization', 'status', 'available_at'], name='outbox_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='automationoutboxevent',
            index=models.Index(fields=['source_type', 'source_id'], name='outbox_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationoutboxevent',
            constraint=models.UniqueConstraint(fields=('organization', 'event_type', 'idempotency_key'), name='outbox_event_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='automationoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', ''), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), name='outbox_event_identity_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='automationoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='outbox_completed_records_time'),
        ),
        migrations.AddConstraint(
            model_name='automationoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DEAD_LETTER'), _negated=True), models.Q(('last_error', ''), _negated=True), _connector='OR'), name='outbox_dead_letter_records_error'),
        ),
        migrations.AddConstraint(
            model_name='automationoutboxattempt',
            constraint=models.UniqueConstraint(fields=('event', 'attempt_number'), name='outbox_attempt_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='automationoutboxattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['SUCCEEDED', 'FAILED']), _negated=True), ('finished_at__isnull', False), _connector='OR'), name='outbox_finished_attempt_records_time'),
        ),
        migrations.AddIndex(
            model_name='automationexception',
            index=models.Index(fields=['organization', 'status', 'severity'], name='automation_exception_state_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexception',
            index=models.Index(fields=['target_type', 'target_id'], name='autom_exc_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationexception',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('organization', 'scope_key', 'code', 'target_type', 'target_id'), name='automation_open_exception_deduped'),
        ),
        migrations.AddConstraint(
            model_name='automationexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('target_type', ''), _negated=True), models.Q(('target_id', ''), _negated=True)), name='automation_exception_identity_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='automationexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RESOLVED'), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='automation_resolved_exception_records_time'),
        ),
        migrations.AddIndex(
            model_name='automationtask',
            index=models.Index(fields=['organization', 'status', 'severity'], name='automation_task_state_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtask',
            index=models.Index(fields=['assignee_user', 'status'], name='automation_task_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'ACKNOWLEDGED'])), fields=('organization', 'deduplication_key'), name='automation_open_task_deduped'),
        ),
        migrations.AddConstraint(
            model_name='automationtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACKNOWLEDGED'), _negated=True), models.Q(('acknowledged_by__isnull', False), ('acknowledged_at__isnull', False)), _connector='OR'), name='automation_acknowledged_task_records_actor'),
        ),
        migrations.AddConstraint(
            model_name='automationtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RESOLVED'), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='automation_resolved_task_records_time'),
        ),
        migrations.AddConstraint(
            model_name='automationtask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task_type', ''), _negated=True), models.Q(('deduplication_key', ''), _negated=True)), name='automation_task_identity_not_empty'),
        ),
    ]
