# Generated by Django 5.2.17 on 2026-08-08 19:32

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_historicalbranch_historicalbranchmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('account_class', models.CharField(choices=[('1', 'الأصول'), ('2', 'الالتزامات'), ('3', 'حقوق الملكية'), ('4', 'الإيرادات'), ('5', 'كلفة المبيعات'), ('6', 'المصروفات التشغيلية'), ('7', 'إيرادات ومصروفات أخرى'), ('8', 'حسابات وسيطة ورقابية'), ('9', 'إحصائية')], max_length=1, verbose_name='class')),
                ('is_postable', models.BooleanField(default=False, help_text='True only for detail accounts. Parents are reporting rollups.', verbose_name='accepts journal lines')),
                ('requires_cost_center', models.BooleanField(default=False, help_text='Revenue, COGS, and operating expenses; not balance-sheet accounts.', verbose_name='requires a cost center')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('external_accounting_system', models.CharField(blank=True, max_length=50, verbose_name='external accounting system')),
                ('external_account_code', models.CharField(blank=True, max_length=50, verbose_name='external account code')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='organizations.organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='parent account')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['organization__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='Changing this re-buckets every posted entry. See ADR-013.', verbose_name='fiscal year start month')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_settings', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'accounting settings',
                'verbose_name_plural': 'accounting settings',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'cost center',
                'verbose_name_plural': 'cost centers',
                'ordering': ['organization__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_years', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'fiscal year',
                'verbose_name_plural': 'fiscal years',
                'ordering': ['organization__code', '-year'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period_number', models.PositiveSmallIntegerField(verbose_name='period number')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('state', models.CharField(choices=[('OPEN', 'مفتوحة'), ('SOFT_CLOSED', 'مغلقة مبدئياً'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=16, verbose_name='state')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='accounting.fiscalyear', verbose_name='fiscal year')),
            ],
            options={
                'verbose_name': 'accounting period',
                'verbose_name_plural': 'accounting periods',
                'ordering': ['fiscal_year__year', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('account_class', models.CharField(choices=[('1', 'الأصول'), ('2', 'الالتزامات'), ('3', 'حقوق الملكية'), ('4', 'الإيرادات'), ('5', 'كلفة المبيعات'), ('6', 'المصروفات التشغيلية'), ('7', 'إيرادات ومصروفات أخرى'), ('8', 'حسابات وسيطة ورقابية'), ('9', 'إحصائية')], max_length=1, verbose_name='class')),
                ('is_postable', models.BooleanField(default=False, help_text='True only for detail accounts. Parents are reporting rollups.', verbose_name='accepts journal lines')),
                ('requires_cost_center', models.BooleanField(default=False, help_text='Revenue, COGS, and operating expenses; not balance-sheet accounts.', verbose_name='requires a cost center')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('external_accounting_system', models.CharField(blank=True, max_length=50, verbose_name='external accounting system')),
                ('external_account_code', models.CharField(blank=True, max_length=50, verbose_name='external account code')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='parent account')),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccountingPeriod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('period_number', models.PositiveSmallIntegerField(verbose_name='period number')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('state', models.CharField(choices=[('OPEN', 'مفتوحة'), ('SOFT_CLOSED', 'مغلقة مبدئياً'), ('CLOSED', 'مغلقة')], default='OPEN', max_length=16, verbose_name='state')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fiscal_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.fiscalyear', verbose_name='fiscal year')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical accounting period',
                'verbose_name_plural': 'historical accounting periods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccountingSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='Changing this re-buckets every posted entry. See ADR-013.', verbose_name='fiscal year start month')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical accounting settings',
                'verbose_name_plural': 'historical accounting settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCostCenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical cost center',
                'verbose_name_plural': 'historical cost centers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFiscalYear',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical fiscal year',
                'verbose_name_plural': 'historical fiscal years',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('entry_number', models.CharField(max_length=32, verbose_name='entry number')),
                ('accounting_date', models.DateField(db_index=True, verbose_name='accounting date')),
                ('document_date', models.DateField(verbose_name='document date')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('is_adjustment', models.BooleanField(default=False, help_text='Posted on the fiscal year-end date instead of a thirteenth period.', verbose_name='year-end adjustment')),
                ('source_document_type', models.CharField(blank=True, max_length=100, verbose_name='source document type')),
                ('source_document_id', models.CharField(blank=True, max_length=64, verbose_name='source document id')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='idempotency key')),
                ('posting_rule_version', models.CharField(blank=True, max_length=32, verbose_name='posting rule version')),
                ('narration', models.TextField(blank=True, verbose_name='narration')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.organization', verbose_name='organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod', verbose_name='accounting period')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.journalentry', verbose_name='reverses entry')),
            ],
            options={
                'verbose_name': 'journal entry',
                'verbose_name_plural': 'journal entries',
                'ordering': ['-accounting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='line number')),
                ('debit', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='debit')),
                ('credit', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='credit')),
                ('narration', models.CharField(blank=True, max_length=255, verbose_name='narration')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account', verbose_name='account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='organizations.branch', verbose_name='branch')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.costcenter', verbose_name='cost center')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='journal entry')),
            ],
            options={
                'verbose_name': 'journal line',
                'verbose_name_plural': 'journal lines',
                'ordering': ['entry_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_sequences', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'journal number sequence',
                'verbose_name_plural': 'journal number sequences',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='account_code_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[1-9](-[0-9]{2}(-[0-9]{2}(-[0-9]{3})?)?)?$')), name='account_code_format'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_postable', True), ('code__regex', '^[1-9]-[0-9]{2}-[0-9]{2}-[0-9]{3}$')), models.Q(('is_postable', False), models.Q(('code__regex', '^[1-9]-[0-9]{2}-[0-9]{2}-[0-9]{3}$'), _negated=True)), _connector='OR'), name='account_postable_iff_detail_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='account_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('requires_cost_center', False), ('is_postable', True), _connector='OR'), name='account_only_postable_requires_cost_center'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_account_code', ''), ('external_accounting_system', '')), models.Q(models.Q(('external_accounting_system', ''), _negated=True), models.Q(('external_account_code', ''), _negated=True)), _connector='OR'), name='account_external_mapping_is_complete_or_absent'),
        ),
        migrations.AddConstraint(
            model_name='accountingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_year_start_month__gte', 1), ('fiscal_year_start_month__lte', 12)), name='accounting_settings_month_in_range'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='cost_center_code_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]*$')), name='cost_center_code_format'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='cost_center_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='fiscal_year_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='fiscal_year_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('fiscal_year', 'period_number'), name='period_unique_per_fiscal_year'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_number__gte', 1), ('period_number__lte', 12)), name='period_number_in_range'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='period_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status'], name='journal_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_document_type', 'source_document_id'], name='journal_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('organization', 'entry_number'), name='journal_entry_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'POSTED'), _negated=True), ('posted_at__isnull', False), _connector='OR'), name='journal_entry_posted_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'branch'], name='journal_line_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('entry', 'line_number'), name='journal_line_number_unique_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', Decimal('0'))), name='journal_line_debit_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', Decimal('0'))), name='journal_line_credit_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', Decimal('0')), ('credit', Decimal('0'))), models.Q(('credit__gt', Decimal('0')), ('debit', Decimal('0'))), _connector='OR'), name='journal_line_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='journalnumbersequence',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='journal_sequence_unique_scope'),
        ),
    ]
