# Generated by Django 5.2.17 on 2026-08-08 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_ledger_integrity_triggers'),
        ('organizations', '0003_task_0_7_permissions_and_source_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('manage_accounts', 'Can create and archive accounts')], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountingperiod',
            options={'ordering': ['fiscal_year__year', 'period_number'], 'permissions': [('soft_close_period', 'Can soft-close an accounting period'), ('close_period', 'Can close an accounting period'), ('reopen_period', 'Can reopen a closed accounting period')], 'verbose_name': 'accounting period', 'verbose_name_plural': 'accounting periods'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('manage_cost_centers', 'Can create and archive cost centers')], 'verbose_name': 'cost center', 'verbose_name_plural': 'cost centers'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-accounting_date', '-id'], 'permissions': [('view_journal', 'Can read journal entries and lines'), ('create_draft', 'Can create a draft journal entry'), ('edit_draft', 'Can amend a draft journal entry'), ('post_journal', 'Can post a journal entry to the ledger'), ('reverse_journal', 'Can reverse a posted journal entry'), ('post_soft_closed_adjustment', 'Can post an adjustment into a soft-closed period'), ('reverse_in_soft_closed_period', 'Can reverse into a soft-closed period')], 'verbose_name': 'journal entry', 'verbose_name_plural': 'journal entries'},
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='journal_entry_number_unique_per_organization',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_event',
            field=models.CharField(blank=True, choices=[('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], help_text='Blank for a manual journal, which has no upstream document.', max_length=16, verbose_name='source event'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_number', ''), _negated=True), fields=('organization', 'entry_number'), name='journal_entry_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('entry_number', ''), _negated=True), _connector='OR'), name='journal_entry_numbered_once_posted'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('source_event__in', ['', 'POSTED', 'REVERSED'])), name='journal_entry_source_event_is_known'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_document_id', ''), ('source_document_type', ''), ('source_event', '')), models.Q(models.Q(('source_document_type', ''), _negated=True), models.Q(('source_document_id', ''), _negated=True), models.Q(('source_event', ''), _negated=True)), _connector='OR'), name='journal_entry_source_identity_complete_or_absent'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event', ''), _negated=True), fields=('organization', 'source_document_type', 'source_document_id', 'source_event'), name='journal_entry_source_event_unique_per_organization'),
        ),
    ]
