# Generated by Django 5.2.17 on 2026-08-08 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_posted_entry_immutability_is_an_allowlist'),
        ('organizations', '0003_task_0_7_permissions_and_source_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, max_length=64, verbose_name='idempotency fingerprint'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='idempotency key'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='journal_entry_idempotency_key_unique_per_organization'),
        ),
    ]
