# Generated by Django 5.2.17 on 2026-08-09 10:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_organization_scoped_idempotency'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('domain', models.CharField(choices=[('INVENTORY', 'المخزون')], max_length=20, verbose_name='domain')),
                ('mapping_scope', models.CharField(choices=[('ORGANIZATION', 'افتراضي المؤسسة فقط'), ('ITEM', 'قابل للتخصيص حسب الصنف')], default='ORGANIZATION', max_length=16, verbose_name='mapping scope')),
                ('is_system', models.BooleanField(default=False, verbose_name='system role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'account role',
                'verbose_name_plural': 'account roles',
                'ordering': ['domain', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]*$')), name='account_role_code_format'), models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='account_role_names_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccountRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('domain', models.CharField(choices=[('INVENTORY', 'المخزون')], max_length=20, verbose_name='domain')),
                ('mapping_scope', models.CharField(choices=[('ORGANIZATION', 'افتراضي المؤسسة فقط'), ('ITEM', 'قابل للتخصيص حسب الصنف')], default='ORGANIZATION', max_length=16, verbose_name='mapping scope')),
                ('is_system', models.BooleanField(default=False, verbose_name='system role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account role',
                'verbose_name_plural': 'historical account roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrganizationAccountMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='account')),
                ('account_role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.accountrole', verbose_name='account role')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical organization account mapping',
                'verbose_name_plural': 'historical organization account mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_mappings', to='accounting.account', verbose_name='account')),
                ('account_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_mappings', to='accounting.accountrole', verbose_name='account role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'organization account mapping',
                'verbose_name_plural': 'organization account mappings',
                'ordering': ['organization__code', 'account_role__code', '-effective_from'],
                'permissions': [('manage_account_mappings', 'Can manage account role mappings')],
                'indexes': [models.Index(fields=['organization', 'account_role', 'is_active'], name='org_mapping_role_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='org_account_mapping_period_is_ordered'), models.UniqueConstraint(fields=('organization', 'account_role', 'version'), name='org_account_mapping_version_unique')],
            },
        ),
    ]
