# Generated by Django 5.2.17 on 2026-08-19 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_chart_metadata_and_report_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-accounting_date', '-id'], 'permissions': [('view_journal', 'Can read journal entries and lines'), ('create_draft', 'Can create a draft journal entry'), ('edit_draft', 'Can amend a draft journal entry'), ('post_journal', 'Can post a journal entry to the ledger'), ('reverse_journal', 'Can reverse a posted journal entry'), ('post_restricted_manual_journal', 'Can post a manual line to a RESTRICTED control account'), ('post_soft_closed_adjustment', 'Can post an adjustment into a soft-closed period'), ('reverse_in_soft_closed_period', 'Can reverse into a soft-closed period')], 'verbose_name': 'journal entry', 'verbose_name_plural': 'journal entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
