# Generated by Django 5.2.17 on 2026-08-19 12:17

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_journal_creator_and_restricted_posting'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('last_reconciled_on', models.DateField(blank=True, null=True, verbose_name='last reconciled on')),
                ('bank_name', models.CharField(max_length=200, verbose_name='bank')),
                ('masked_account_number', models.CharField(help_text='آخر أربعة أرقام فقط.', max_length=40, verbose_name='account number (masked)')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='bank account')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical bank account',
                'verbose_name_plural': 'historical bank accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashbox',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('last_reconciled_on', models.DateField(blank=True, null=True, verbose_name='last reconciled on')),
                ('opened_on', models.DateField(verbose_name='in use from')),
                ('responsible_note', models.CharField(blank=True, max_length=200, verbose_name='responsible person')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='cash account')),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical cashbox',
                'verbose_name_plural': 'historical cashboxes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('last_reconciled_on', models.DateField(blank=True, null=True, verbose_name='last reconciled on')),
                ('bank_name', models.CharField(max_length=200, verbose_name='bank')),
                ('masked_account_number', models.CharField(help_text='آخر أربعة أرقام فقط.', max_length=40, verbose_name='account number (masked)')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.account', verbose_name='bank account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='organizations.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
                'ordering': ['organization__code', 'code'],
                'permissions': [('manage_bank_accounts', 'Can create and archive bank accounts')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='bank_account_code_unique_per_organization'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]*$')), name='bank_account_code_format'), models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True), models.Q(('bank_name', ''), _negated=True)), name='bank_account_names_not_empty'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'account'), name='bank_account_account_unique_while_active'), models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('archived_at__isnull', True)), models.Q(('is_active', False), ('archived_at__isnull', False)), _connector='OR'), name='bank_account_archived_at_matches_state')],
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archived at')),
                ('last_reconciled_on', models.DateField(blank=True, null=True, verbose_name='last reconciled on')),
                ('opened_on', models.DateField(verbose_name='in use from')),
                ('responsible_note', models.CharField(blank=True, max_length=200, verbose_name='responsible person')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes', to='accounting.account', verbose_name='cash account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes', to='organizations.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'cashbox',
                'verbose_name_plural': 'cashboxes',
                'ordering': ['organization__code', 'code'],
                'permissions': [('manage_cashboxes', 'Can create and archive cashboxes')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='cashbox_code_unique_per_organization'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]*$')), name='cashbox_code_format'), models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='cashbox_names_not_empty'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'account'), name='cashbox_account_unique_while_active'), models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('archived_at__isnull', True)), models.Q(('is_active', False), ('archived_at__isnull', False)), _connector='OR'), name='cashbox_archived_at_matches_state')],
            },
        ),
    ]
