# Generated by Django 5.2.17 on 2026-08-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_cashbox_and_bank_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingsettings',
            options={'permissions': [('view_supplier_liabilities', 'Can read the supplier liability reconciliation workspace'), ('view_application_receivables', 'Can read the delivery-application receivable workspace')], 'verbose_name': 'accounting settings', 'verbose_name_plural': 'accounting settings'},
        ),
    ]
