# Generated by Django 5.2.17 on 2026-08-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_expenses_deferrals_and_year_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrole',
            name='domain',
            field=models.CharField(choices=[('INVENTORY', 'المخزون'), ('PURCHASING', 'المشتريات'), ('SALES', 'المبيعات'), ('ACCOUNTING', 'المحاسبة'), ('PAYROLL', 'الرواتب')], max_length=20, verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='historicalaccountrole',
            name='domain',
            field=models.CharField(choices=[('INVENTORY', 'المخزون'), ('PURCHASING', 'المشتريات'), ('SALES', 'المبيعات'), ('ACCOUNTING', 'المحاسبة'), ('PAYROLL', 'الرواتب')], max_length=20, verbose_name='domain'),
        ),
    ]
