# Generated by Django 5.2.17 on 2026-08-26 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_accountrole_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='daily_close_enforced_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='daily close enforced from'),
        ),
        migrations.AddField(
            model_name='historicalaccountingsettings',
            name='daily_close_enforced_from',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='daily close enforced from'),
        ),
    ]
