# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_rename_legacy_name_ar_columns'),
        ('organizations', '0009_remove_branch_branch_names_not_empty_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='account_names_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='accountrole',
            name='account_role_names_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='bank_account_names_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='cashbox',
            name='cashbox_names_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='costcenter',
            name='cost_center_names_not_empty',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='accountrole',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='cashbox',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalaccountrole',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalbankaccount',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalcashbox',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalcostcenter',
            name='name_en',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='account_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='accountrole',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='account_role_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True), models.Q(('bank_name', ''), _negated=True)), name='bank_account_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='cashbox',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='cashbox_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='cost_center_names_not_empty'),
        ),
    ]
