# Generated by Django 5.2.17 on 2026-08-29 03:01

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0026_alter_account_name_alter_accountrole_name_and_more"),
        ("organizations", "0011_alter_roledefinition_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedChartAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("source_system", models.CharField(max_length=80, verbose_name="source system")),
                (
                    "source_code",
                    models.CharField(max_length=50, verbose_name="source account code"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "statement_name",
                    models.CharField(blank=True, max_length=100, verbose_name="statement"),
                ),
                ("category", models.CharField(blank=True, max_length=100, verbose_name="category")),
                ("currency", models.CharField(blank=True, max_length=8, verbose_name="currency")),
                (
                    "source_debit",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0"),
                        max_digits=24,
                        verbose_name="source debit",
                    ),
                ),
                (
                    "source_credit",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0"),
                        max_digits=24,
                        verbose_name="source credit",
                    ),
                ),
                (
                    "source_balance",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0"),
                        max_digits=24,
                        verbose_name="source balance",
                    ),
                ),
                (
                    "organizer",
                    models.CharField(blank=True, max_length=100, verbose_name="organizer"),
                ),
                ("is_leaf", models.BooleanField(default=False, verbose_name="source leaf")),
                (
                    "imported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="imported at"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imported_chart_accounts",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.importedchartaccount",
                        verbose_name="source parent account",
                    ),
                ),
            ],
            options={
                "verbose_name": "imported chart account",
                "verbose_name_plural": "imported chart accounts",
                "ordering": ["organization__code", "source_system", "source_code"],
                "indexes": [
                    models.Index(
                        fields=["organization", "source_system", "parent"],
                        name="imported_chart_tree_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_system", "source_code"),
                        name="imported_chart_code_unique_per_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("source_code", ""), _negated=True),
                            models.Q(("name", ""), _negated=True),
                        ),
                        name="imported_chart_identity_not_empty",
                    ),
                ],
            },
        ),
    ]
