# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0028_zero_imported_chart_information"),
        ("organizations", "0012_drop_access_change_requests"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="account_code_format",
        ),
        migrations.RemoveConstraint(
            model_name="account",
            name="account_postable_iff_detail_code",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__regex", "^(?:[1-9](-[0-9]{2}(-[0-9]{2}(-[0-9]{3})?)?)?|[1-9][0-9]{5})$")
                ),
                name="account_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("code__regex", "^[1-9][0-9]{5}$"),
                    models.Q(
                        ("is_postable", True),
                        ("code__regex", "^[1-9]-[0-9]{2}-[0-9]{2}-[0-9]{3}$"),
                    ),
                    models.Q(
                        ("is_postable", False),
                        models.Q(
                            ("code__regex", "^[1-9]-[0-9]{2}-[0-9]{2}-[0-9]{3}$"),
                            _negated=True,
                        ),
                    ),
                    _connector="OR",
                ),
                name="account_postable_iff_detail_code",
            ),
        ),
    ]
