# Generated by Django 5.2.17 on 2026-08-08 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('dimension', models.CharField(choices=[('MASS', 'كتلة'), ('VOLUME', 'حجم'), ('COUNT', 'عدد')], max_length=10, verbose_name='dimension')),
                ('factor_to_base', models.DecimalField(decimal_places=12, help_text='How many base units are in one of this unit. One gram is 0.001 kg.', max_digits=24, verbose_name='factor to base unit')),
                ('is_base', models.BooleanField(default=False, help_text='The unit every other unit in this dimension converts through.', verbose_name='is base unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'unit of measure',
                'verbose_name_plural': 'units of measure',
                'ordering': ['dimension', '-is_base', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z][A-Z0-9_]*$')), name='unit_code_format'), models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='unit_names_not_empty'), models.CheckConstraint(condition=models.Q(('factor_to_base__gt', Decimal('0'))), name='unit_factor_is_positive'), models.CheckConstraint(condition=models.Q(('is_base', False), ('factor_to_base', Decimal('1')), _connector='OR'), name='unit_base_factor_is_one'), models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('dimension',), name='unit_one_base_per_dimension')],
            },
        ),
    ]
