# Generated by Django 5.2.17 on 2026-08-08 08:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUnitOfMeasure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='name (English)')),
                ('dimension', models.CharField(choices=[('MASS', 'كتلة'), ('VOLUME', 'حجم'), ('COUNT', 'عدد')], max_length=10, verbose_name='dimension')),
                ('factor_to_base', models.DecimalField(decimal_places=12, help_text='How many base units are in one of this unit. One gram is 0.001 kg.', max_digits=24, verbose_name='factor to base unit')),
                ('is_base', models.BooleanField(default=False, help_text='The unit every other unit in this dimension converts through.', verbose_name='is base unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical unit of measure',
                'verbose_name_plural': 'historical units of measure',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
