# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unitofmeasure',
            name='unit_names_not_empty',
        ),
        migrations.RemoveField(
            model_name='historicalunitofmeasure',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='name_en',
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='unit_names_not_empty'),
        ),
    ]
