# Generated by Django 5.2.17 on 2026-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_remove_unitofmeasure_unit_names_not_empty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunitofmeasure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
