"""
The catalogue's entries: one per permission, in the order the matrix shows.

Presentation only (see `permission_catalog.py`). The codenames are the
contract; the labels are what the owner reads. Written from each module's
own `permissions.py` documentation, reviewed for one verb per kind of act.
"""

from __future__ import annotations

from apps.organizations.permission_catalog import Entry

CATALOGUE: tuple[Entry, ...] = (
    Entry(
        "inventory.view_item",
        "عرض الأصناف",
        section_ar="البيانات الأساسية",
        kind="view",
    ),
    Entry(
        "inventory.manage_items",
        "إدارة الأصناف",
        section_ar="البيانات الأساسية",
        kind="manage",
        note_ar="الأرشفة وإعادة التفعيل وتصحيح وحدة الأساس على مستوى المنشأة؛ الإنشاء والتعديل صلاحيتان منفصلتان (إنشاء صنف جديد / تعديل صنف قائم)",
    ),
    Entry(
        "inventory.manage_categories",
        "إدارة مجموعات الأصناف",
        section_ar="البيانات الأساسية",
        kind="manage",
    ),
    Entry(
        "inventory.manage_package_units",
        "إدارة وحدات التعبئة",
        section_ar="البيانات الأساسية",
        kind="manage",
    ),
    Entry(
        "inventory.manage_conversions",
        "إدارة تحويلات وحدات الصنف",
        section_ar="البيانات الأساسية",
        kind="manage",
        note_ar="معاملات التحويل بين وحدة التعبئة ووحدة التخزين",
    ),
    Entry(
        "inventory.manage_warehouses",
        "إدارة المخازن",
        section_ar="البيانات الأساسية",
        kind="manage",
    ),
    Entry(
        "inventory.manage_locations",
        "إدارة مواقع التخزين",
        section_ar="البيانات الأساسية",
        kind="manage",
        note_ar="الأرفف والخلايا داخل المخزن الواحد",
    ),
    Entry(
        "inventory.view_stock",
        "عرض المخزون المتوفر",
        section_ar="الرصيد والحركة",
        kind="view",
        note_ar="الكميات فقط دون الكلفة",
    ),
    Entry(
        "inventory.view_valuation",
        "عرض كلفة المخزون وتقييمه",
        section_ar="الرصيد والحركة",
        kind="view",
        sensitive=True,
        note_ar="يكشف الكلفة في الأرصدة وبطاقة الصنف وتقرير التقييم؛ شاشة مطابقة المخزون والأستاذ تحتاجها مع صلاحية عرض قيود اليومية في المحاسبة",
    ),
    Entry(
        "inventory.reverse_movement",
        "عكس حركة مخزنية",
        section_ar="الرصيد والحركة",
        kind="reverse",
        sensitive=True,
        note_ar="يعكس أي حركة مرحّلة: افتتاحي، استلام، صرف، تحويل، جرد، تسوية",
    ),
    Entry(
        "inventory.move_location_stock",
        "نقل المخزون بين مواقع التخزين",
        section_ar="الرصيد والحركة",
        kind="other",
        note_ar="نقل داخل المخزن نفسه؛ لا يغيّر الكمية الإجمالية ولا الكلفة",
    ),
    Entry(
        "inventory.create_draft_movement",
        "إنشاء مسودة حركة مخزنية",
        section_ar="الحركات المخزنية",
        kind="create",
        note_ar="مسودة فقط؛ الترحيل صلاحية منفصلة",
    ),
    Entry(
        "inventory.create_opening_stock",
        "إنشاء مستند الأرصدة الافتتاحية",
        section_ar="الحركات المخزنية",
        kind="create",
        note_ar="إعداد قائمة الفرع وتقديمها فقط؛ الترحيل صلاحية منفصلة",
    ),
    Entry(
        "inventory.post_opening_stock",
        "ترحيل الأرصدة الافتتاحية",
        section_ar="الحركات المخزنية",
        kind="post",
        sensitive=True,
        note_ar="يحدد نقطة بداية الأستاذ؛ لا يرحّل من أعدّ المستند نفسه",
    ),
    Entry(
        "inventory.post_receipt",
        "ترحيل استلام مخزني غير مفوتر",
        section_ar="الحركات المخزنية",
        kind="post",
        sensitive=True,
        note_ar="استلام غير مفوتر إلى المخزن؛ الاستلام مقابل أمر شراء يمرّ عبر استلام البضاعة في المشتريات",
    ),
    Entry(
        "inventory.post_issue",
        "ترحيل صرف مخزني",
        section_ar="الحركات المخزنية",
        kind="post",
        sensitive=True,
        note_ar="صرف للاستهلاك من المخزن",
    ),
    Entry(
        "inventory.post_return_in",
        "ترحيل إرجاع من صرف سابق",
        section_ar="الحركات المخزنية",
        kind="post",
        sensitive=True,
        note_ar="يُقيَّم بكلفة الصرف الذي يعكسه؛ لا قرار كلفة فيه",
    ),
    Entry(
        "inventory.post_transfer",
        "ترحيل تحويل مخزني",
        section_ar="الحركات المخزنية",
        kind="post",
        sensitive=True,
        note_ar="إرسال التحويل من المخزن المصدر واستلامه في المخزن الوجهة",
    ),
    Entry(
        "inventory.close_transfer_shortage",
        "إغلاق نقص التحويل كخسارة",
        section_ar="الحركات المخزنية",
        kind="other",
        sensitive=True,
        note_ar="يحوّل الكمية المفقودة بالطريق إلى مصروف خسارة؛ الأكثر حساسية في الوحدة",
    ),
    Entry(
        "inventory.post_waste",
        "ترحيل إتلاف مخزني",
        section_ar="الحركات المخزنية",
        kind="post",
        sensitive=True,
    ),
    Entry(
        "inventory.override_negative_stock",
        "تجاوز منع الرصيد السالب",
        section_ar="الحركات المخزنية",
        kind="other",
        sensitive=True,
        note_ar="محجوزة؛ غير مفعّلة في هذا الإصدار ولا تُمنح لأي دور",
    ),
    Entry(
        "inventory.conduct_stock_count",
        "إجراء جرد فعلي",
        section_ar="الجرد والتسويات",
        kind="other",
        note_ar="فتح الجرد والعدّ الأعمى وإدخال الكميات؛ لا يعتمده",
    ),
    Entry(
        "inventory.approve_stock_count",
        "اعتماد جرد فعلي",
        section_ar="الجرد والتسويات",
        kind="approve",
        sensitive=True,
        note_ar="يرحّل فروقات الجرد؛ لا يجوز اعتماد جرد أجراه المستخدم نفسه",
    ),
    Entry(
        "inventory.post_adjustment",
        "ترحيل تسوية مخزنية",
        section_ar="الجرد والتسويات",
        kind="post",
        sensitive=True,
    ),
    Entry(
        "inventory.manage_reason_codes",
        "إدارة أسباب الحركات",
        section_ar="الضبط والمطابقة",
        kind="manage",
        note_ar="أسباب الإتلاف والتسويات المشتركة على مستوى المنشأة",
    ),
    Entry(
        "inventory.import_master_data",
        "استيراد البيانات الأساسية للمخزون",
        section_ar="الضبط والمطابقة",
        kind="import",
        note_ar="الأصناف والمجموعات ووحدات التعبئة والتحويلات من ملف؛ لا يرحّل مخزونًا",
    ),
    Entry(
        "inventory.import_opening_draft",
        "استيراد مسودة الأرصدة الافتتاحية",
        section_ar="الضبط والمطابقة",
        kind="import",
        note_ar="محجوزة؛ غير مفعّلة في هذا الإصدار ولا تُمنح لأي دور",
    ),
    Entry(
        "inventory.view_import_history",
        "عرض سجل الاستيراد",
        section_ar="الضبط والمطابقة",
        kind="view",
        note_ar="قراءة ما استُورد ومن استورده دون صلاحية التطبيق",
    ),
    Entry(
        "inventory.create_item",
        "إنشاء صنف جديد",
        section_ar="البيانات الأساسية",
        kind="create",
        note_ar="تسجيل صنف جديد في سجل الأصناف على مستوى المنشأة؛ لا يعدّل صنفًا قائمًا ولا يؤرشفه",
    ),
    Entry(
        "inventory.edit_item",
        "تعديل صنف قائم",
        section_ar="البيانات الأساسية",
        kind="edit",
        note_ar="تغيير بيانات صنف مسجّل (الاسم والمجموعة والنوع ومدة الصلاحية والملاحظات)؛ الأرشفة وإعادة التفعيل وتصحيح وحدة الأساس تبقى مع إدارة الأصناف",
    ),
    Entry(
        "procurement.view_supplier",
        "عرض الموردين",
        section_ar="الموردون",
        kind="view",
        note_ar="يشمل ملخّص شروط الائتمان، دون الأسعار والمبالغ",
    ),
    Entry(
        "procurement.manage_suppliers",
        "إدارة الموردين",
        section_ar="الموردون",
        kind="manage",
        note_ar="إنشاء سجل المورد وتعديله وأرشفته",
    ),
    Entry(
        "procurement.view_supplier_cost",
        "عرض أسعار الموردين والمبالغ",
        section_ar="الموردون",
        kind="view",
        sensitive=True,
        note_ar="بدونها تُحذف أعمدة السعر والمبلغ من كل شاشات المشتريات وتقاريرها",
    ),
    Entry(
        "procurement.import_supplier",
        "استيراد الموردين",
        section_ar="الموردون",
        kind="import",
        note_ar="من ملف جداول عبر سجل الاستيراد",
    ),
    Entry(
        "procurement.view_supplieritem",
        "عرض كتالوج الموردين",
        section_ar="كتالوج الموردين",
        kind="view",
        note_ar="من يورّد ماذا وبأي عبوة، دون السعر",
    ),
    Entry(
        "procurement.manage_supplier_items",
        "إدارة كتالوج الموردين",
        section_ar="كتالوج الموردين",
        kind="manage",
    ),
    Entry(
        "procurement.import_supplier_item",
        "استيراد كتالوج الموردين",
        section_ar="كتالوج الموردين",
        kind="import",
        note_ar="من ملف جداول عبر سجل الاستيراد",
    ),
    Entry(
        "procurement.view_purchaserequest",
        "عرض طلبات الشراء",
        section_ar="طلبات الشراء",
        kind="view",
    ),
    Entry(
        "procurement.create_purchase_request",
        "إنشاء طلب شراء",
        section_ar="طلبات الشراء",
        kind="create",
        note_ar="الإعداد والتقديم، ويشمل استيراد مسودة طلب شراء",
    ),
    Entry(
        "procurement.approve_purchase_request",
        "اعتماد طلب شراء",
        section_ar="طلبات الشراء",
        kind="approve",
        note_ar="الموافقة أو الرفض، ولا يعتمد الطلب من قدّمه",
    ),
    Entry(
        "procurement.view_supplierquotation",
        "عرض عروض الموردين",
        section_ar="عروض الموردين",
        kind="view",
    ),
    Entry(
        "procurement.manage_quotations",
        "إدارة عروض الموردين",
        section_ar="عروض الموردين",
        kind="manage",
        note_ar="تسجيل العرض وتقديمه للمقارنة، دون ترسيته",
    ),
    Entry(
        "procurement.award_quotation",
        "ترسية عرض مورد",
        section_ar="عروض الموردين",
        kind="other",
        sensitive=True,
        note_ar="اختيار العرض الفائز وتسجيل سبب الترسية",
    ),
    Entry(
        "procurement.view_purchaseorder",
        "عرض أوامر الشراء",
        section_ar="أوامر الشراء",
        kind="view",
    ),
    Entry(
        "procurement.create_purchase_order",
        "إنشاء أمر شراء",
        section_ar="أوامر الشراء",
        kind="create",
    ),
    Entry(
        "procurement.approve_purchase_order",
        "اعتماد أمر شراء",
        section_ar="أوامر الشراء",
        kind="approve",
        sensitive=True,
        note_ar="الموافقة على الإنفاق، ولا يعتمد الأمر من أعدّه",
    ),
    Entry(
        "procurement.issue_purchase_order",
        "إصدار أمر شراء للمورد",
        section_ar="أوامر الشراء",
        kind="other",
        sensitive=True,
        note_ar="إرسال الأمر المعتمد إلى المورد",
    ),
    Entry(
        "procurement.cancel_purchase_order",
        "إلغاء أمر شراء",
        section_ar="أوامر الشراء",
        kind="other",
        sensitive=True,
    ),
    Entry(
        "procurement.view_goodsreceipt",
        "عرض استلام البضاعة",
        section_ar="استلام البضاعة",
        kind="view",
    ),
    Entry(
        "procurement.create_goods_receipt",
        "إنشاء استلام بضاعة",
        section_ar="استلام البضاعة",
        kind="create",
        note_ar="تسجيل ما وصل فعلاً مقابل إشعار تسليم المورد",
    ),
    Entry(
        "procurement.inspect_goods_receipt",
        "فحص استلام بضاعة",
        section_ar="استلام البضاعة",
        kind="other",
        note_ar="قبول البضاعة المستلمة أو رفضها سطراً سطراً",
    ),
    Entry(
        "procurement.post_goods_receipt",
        "ترحيل استلام بضاعة",
        section_ar="استلام البضاعة",
        kind="post",
        sensitive=True,
        note_ar="يُدخل الكمية إلى المخزون ويُنشئ قيد البضاعة المستلمة غير المفوترة",
    ),
    Entry(
        "procurement.reverse_goods_receipt",
        "عكس استلام بضاعة مرحّل",
        section_ar="استلام البضاعة",
        kind="reverse",
        sensitive=True,
        note_ar="يعكس حركة المخزون والقيد معاً",
    ),
    Entry(
        "procurement.view_supplierinvoice",
        "عرض فواتير الموردين",
        section_ar="فواتير الموردين",
        kind="view",
        note_ar="تفتح أيضاً نظرة عامة على المشتريات وقوائم التكاليف الإضافية وسطورها",
    ),
    Entry(
        "procurement.create_supplier_invoice",
        "إنشاء فاتورة مورد",
        section_ar="فواتير الموردين",
        kind="create",
        note_ar="تسجيل الفاتورة وتعديل مسودتها",
    ),
    Entry(
        "procurement.approve_supplier_invoice",
        "اعتماد فاتورة مورد",
        section_ar="فواتير الموردين",
        kind="approve",
        sensitive=True,
        note_ar="الإقرار بصحة المطالبة، ولا يعتمد الفاتورة من أدخلها",
    ),
    Entry(
        "procurement.post_supplier_invoice",
        "ترحيل فاتورة مورد",
        section_ar="فواتير الموردين",
        kind="post",
        sensitive=True,
        note_ar="يُثبت الذمة الدائنة في دفتر الأستاذ",
    ),
    Entry(
        "procurement.reverse_supplier_invoice",
        "عكس فاتورة مورد مرحّلة",
        section_ar="فواتير الموردين",
        kind="reverse",
        sensitive=True,
    ),
    Entry(
        "procurement.view_purchasematch",
        "عرض مطابقة المشتريات",
        section_ar="فواتير الموردين",
        kind="view",
        note_ar="أي تسليم يقابل أي فاتورة وما الفرق بينهما",
    ),
    Entry(
        "procurement.match_supplier_invoice",
        "مطابقة فاتورة مورد",
        section_ar="فواتير الموردين",
        kind="other",
        note_ar="ربط الفاتورة بأوامر الشراء والاستلامات؛ لا تُنشئ قيداً",
    ),
    Entry(
        "procurement.cancel_purchase_match",
        "إلغاء مطابقة مشتريات",
        section_ar="فواتير الموردين",
        kind="other",
        sensitive=True,
        note_ar="سحب مطابقة متفق عليها قد يكون الترحيل بُني عليها",
    ),
    Entry(
        "procurement.manage_supplier_invoice_charges",
        "إدارة التكاليف الإضافية للفاتورة",
        section_ar="التكاليف الإضافية",
        kind="manage",
        note_ar="إضافة تكاليف الشحن وغيرها وتعديلها وحذفها وتوزيعها على سطور الاستلام",
    ),
    Entry(
        "procurement.view_supplierreturn",
        "عرض مرتجعات الموردين",
        section_ar="مرتجعات الموردين",
        kind="view",
    ),
    Entry(
        "procurement.create_supplier_return",
        "إنشاء مرتجع مورد",
        section_ar="مرتجعات الموردين",
        kind="create",
    ),
    Entry(
        "procurement.post_supplier_return",
        "ترحيل مرتجع مورد",
        section_ar="مرتجعات الموردين",
        kind="post",
        sensitive=True,
        note_ar="يُخرج الكمية من المخزون",
    ),
    Entry(
        "procurement.reverse_supplier_return",
        "عكس مرتجع مورد مرحّل",
        section_ar="مرتجعات الموردين",
        kind="reverse",
        sensitive=True,
    ),
    Entry(
        "procurement.view_suppliercreditnote",
        "عرض إشعارات الموردين الدائنة",
        section_ar="إشعارات الموردين الدائنة",
        kind="view",
    ),
    Entry(
        "procurement.create_supplier_credit_note",
        "إنشاء إشعار دائن من مورد",
        section_ar="إشعارات الموردين الدائنة",
        kind="create",
        note_ar="تسجيل ردّ المورد على مرتجع أو مطالبة",
    ),
    Entry(
        "procurement.post_supplier_credit_note",
        "ترحيل إشعار دائن من مورد",
        section_ar="إشعارات الموردين الدائنة",
        kind="post",
        sensitive=True,
        note_ar="يُخفّض ذمة المورد، ولا يرحّل الإشعار من أدخله",
    ),
    Entry(
        "procurement.reverse_supplier_credit_note",
        "عكس إشعار دائن مرحّل",
        section_ar="إشعارات الموردين الدائنة",
        kind="reverse",
        sensitive=True,
    ),
    Entry(
        "procurement.view_supplierpayment",
        "عرض دفعات الموردين",
        section_ar="دفعات الموردين",
        kind="view",
    ),
    Entry(
        "procurement.create_supplier_payment",
        "إنشاء دفعة لمورد",
        section_ar="دفعات الموردين",
        kind="create",
        note_ar="إعداد الدفعة وتخصيصها على الفواتير دون صرفها",
    ),
    Entry(
        "procurement.post_supplier_payment",
        "ترحيل دفعة لمورد",
        section_ar="دفعات الموردين",
        kind="post",
        sensitive=True,
        note_ar="يُخرج النقد فعلياً، ولا يرحّل الدفعة من أدخلها",
    ),
    Entry(
        "procurement.reverse_supplier_payment",
        "عكس دفعة مورد مرحّلة",
        section_ar="دفعات الموردين",
        kind="reverse",
        sensitive=True,
    ),
    Entry(
        "procurement.view_procurement_report",
        "عرض تقارير المشتريات",
        section_ar="أرصدة الموردين",
        kind="view",
        note_ar="التقارير الاثنا عشر كلها بما فيها أعمار الذمم؛ أعمدة الكلفة تتبع صلاحية عرض الأسعار",
    ),
    Entry(
        "procurement.view_suppliercreditterm",
        "عرض شروط ائتمان الموردين",
        section_ar="شروط الائتمان",
        kind="view",
    ),
    Entry(
        "procurement.create_supplier_credit_term",
        "إنشاء شروط ائتمان لمورد",
        section_ar="شروط الائتمان",
        kind="create",
        note_ar="إعداد مسودة الشروط بتاريخ سريان",
    ),
    Entry(
        "procurement.approve_supplier_credit_term",
        "اعتماد شروط ائتمان مورد",
        section_ar="شروط الائتمان",
        kind="approve",
        sensitive=True,
        note_ar="تفعيل الشروط وبدء سريانها على تواريخ الاستحقاق",
    ),
    Entry(
        "kitchen.view_recipe",
        "عرض الوصفات",
        section_ar="الوصفات",
        kind="view",
        note_ar="صلاحية Django الافتراضية على نموذج الوصفة؛ تفتح نظرة عامة المطبخ وقائمة الوصفات وبطاقة الوصفة دون أي عمود كلفة",
    ),
    Entry(
        "kitchen.manage_recipe",
        "إدارة الوصفات",
        section_ar="الوصفات",
        kind="manage",
        note_ar="إنشاء وتعديل وأرشفة الوصفات ومجموعاتها، ومسودات النسخ بسطورها وبدائلها وخطواتها وحصصها ومكوّناتها",
    ),
    Entry(
        "kitchen.view_recipe_cost",
        "عرض كلفة الوصفة",
        section_ar="كلفة الوصفة والطبق",
        kind="view",
        sensitive=True,
        note_ar="يكشف أعمدة الكلفة وبطاقة الكلفة ولقطات الكلفة وتقرير كلفة الوصفات؛ بدونه تُحذف أعمدة الكلفة لا تُفرَّغ",
    ),
    Entry(
        "kitchen.view_kitchen_report",
        "عرض تقارير المطبخ",
        section_ar="الإنتاجية والفاقد",
        kind="view",
        note_ar="صلاحية واحدة لكل عائلة التقارير: الإنتاجية والفاقد، الصرف والمرتجع والهالك، الاستهلاك الفعلي والنظري وانحرافه، تدفق مخزن المطبخ، متطلبات الإنتاج القياسية، وقوائم الوجبات",
    ),
    Entry(
        "kitchen.submit_recipe_version",
        "تقديم نسخة وصفة للمراجعة",
        section_ar="نسخ الوصفات",
        kind="other",
        note_ar="المُعِدّ يعلن أن المسودة جاهزة للقراءة؛ لا يمنح أي صلاحية مراجعة أو اعتماد",
    ),
    Entry(
        "kitchen.review_recipe_version",
        "مراجعة نسخة وصفة",
        section_ar="نسخ الوصفات",
        kind="other",
        note_ar="توقيع عمود واحد من المراجعة (الكميات والوحدات، أو دليل الكلفة، أو الطريقة) دون صلاحية تعديل الوصفة أو اعتمادها",
    ),
    Entry(
        "kitchen.approve_recipe_version",
        "اعتماد نسخة وصفة",
        section_ar="نسخ الوصفات",
        kind="approve",
        sensitive=True,
        note_ar="توقيع المدير النهائي على النسخة؛ لا يمكن لمن قدّم النسخة اعتمادها بنفسه (فصل المهام على الشخص لا على الصلاحية)",
    ),
    Entry(
        "kitchen.reject_recipe_version",
        "رفض نسخة وصفة",
        section_ar="نسخ الوصفات",
        kind="other",
        note_ar="إنهاء نسخة مقدَّمة للمراجعة؛ سلطة مستقلة عن الاعتماد",
    ),
    Entry(
        "kitchen.activate_recipe_version",
        "تفعيل نسخة وصفة",
        section_ar="نسخ الوصفات",
        kind="other",
        sensitive=True,
        note_ar="تحديد تاريخ سريان النسخة المعتمدة لتحكم التكليف، ويشمل استبدال النسخة السارية؛ هذا القرار يحرّك المال",
    ),
    Entry(
        "kitchen.view_productionbatch",
        "عرض أوامر الإنتاج",
        section_ar="أوامر الإنتاج",
        kind="view",
        note_ar="صلاحية Django الافتراضية على نموذج دفعة الإنتاج، بنطاق المخزن؛ لا تكشف أي كلفة أو تقييم",
    ),
    Entry(
        "kitchen.create_production_batch",
        "إنشاء أمر إنتاج",
        section_ar="أوامر الإنتاج",
        kind="create",
        note_ar="يشمل تعديل المسودة (الكميات الفعلية والبدائل وإعادة القياس والمخرجات والملاحظات) وإلغاءها قبل الترحيل؛ لا يحرّك مخزوناً",
    ),
    Entry(
        "kitchen.post_production_batch",
        "ترحيل أمر إنتاج",
        section_ar="أوامر الإنتاج",
        kind="post",
        sensitive=True,
        note_ar="يحرّك المخزون ويكتب قيداً محاسبياً؛ تصحيحه يكون بالعكس فقط",
    ),
    Entry(
        "kitchen.reverse_production_batch",
        "عكس أمر إنتاج مرحّل",
        section_ar="أوامر الإنتاج",
        kind="reverse",
        sensitive=True,
        note_ar="صلاحية إشرافية تبقى مع المدير لا أمين المخزن؛ العكس يبقى على السجل",
    ),
    Entry(
        "kitchen.record_meal",
        "تسجيل وجبات الموظفين والمجانية",
        section_ar="وجبات الموظفين",
        kind="other",
        note_ar="بنطاق الفرع؛ يشمل إلغاء الوجبة؛ لا يحرّك مخزوناً ولا يكتب قيداً",
    ),
    Entry(
        "kitchen.link_batch_document",
        "ربط مستند مخزني بأمر إنتاج",
        section_ar="أوامر الإنتاج",
        kind="other",
        note_ar="نسبة مستند هالك أو تحويل عهدة إلى دفعة إنتاج، ويشمل إلغاء الربط؛ بنطاق المخزن ولا يحرّك مخزوناً",
    ),
    Entry(
        "sales.view_sales",
        "عرض بيانات المبيعات",
        section_ar="المبيعات اليومية",
        kind="view",
        note_ar="يفتح كل قوائم الوحدة وتفاصيل المستندات؛ لا يكشف الكلفة ولا الهامش",
    ),
    Entry(
        "sales.manage_menu",
        "إدارة أصناف المنيو وأسعارها",
        section_ar="أصناف المنيو",
        kind="manage",
        note_ar="يشمل مجموعات المنيو والأسعار وتواريخ سريانها وأرشفة الأصناف",
    ),
    Entry(
        "sales.view_sales_reports",
        "عرض تقارير المبيعات",
        section_ar="لوحة المبيعات",
        kind="view",
        note_ar="يشمل لوحة المبيعات والمطابقة اليومية؛ لا يسجّل شيئاً",
    ),
    Entry(
        "sales.view_sales_cost",
        "عرض كلفة الطعام وهامش الربح",
        section_ar="لوحة المبيعات",
        kind="view",
        sensitive=True,
        note_ar="يُظهر أعمدة الكلفة والهامش في المنيو ولوحة المبيعات؛ سعر البيع والعمولة والذمم لا تحتاجه",
    ),
    Entry(
        "sales.manage_sales_channels",
        "إدارة قنوات البيع",
        section_ar="قنوات البيع",
        kind="manage",
        note_ar="إنشاء القنوات وتعديلها وأرشفتها",
    ),
    Entry(
        "sales.manage_delivery_applications",
        "إدارة تطبيقات التوصيل",
        section_ar="تطبيقات التوصيل",
        kind="manage",
        note_ar="تسجيل التطبيق وتعديله وأرشفته؛ لا يحدد العمولة",
    ),
    Entry(
        "sales.manage_sales_agreements",
        "إدارة اتفاقيات العمولة",
        section_ar="العمولات والاتفاقيات",
        kind="manage",
        sensitive=True,
        note_ar="إنشاء الاتفاقية وإنهاؤها؛ تحدد ما يساويه كل طلب قادم من التطبيق للمطعم",
    ),
    Entry(
        "sales.manage_sales_discounts",
        "إدارة برامج الخصم",
        section_ar="الخصومات",
        kind="manage",
        sensitive=True,
        note_ar="إنشاء برنامج الخصم وإنهاؤه؛ الخصم اليدوي على سطر البيع لا يحتاجه",
    ),
    Entry(
        "sales.create_daily_sales",
        "إنشاء مسودة يوم المبيعات",
        section_ar="المبيعات اليومية",
        kind="create",
        note_ar="إنشاء المسودة وتعديلها؛ المسودة لا تحرك أي مبلغ",
    ),
    Entry(
        "sales.submit_daily_sales",
        "تقديم يوم المبيعات للترحيل",
        section_ar="المبيعات اليومية",
        kind="other",
        note_ar="يرفع اليوم من مسودة إلى بانتظار الترحيل دون أن يصل إلى الدفاتر",
    ),
    Entry(
        "sales.post_daily_sales",
        "ترحيل يوم المبيعات",
        section_ar="المبيعات اليومية",
        kind="post",
        sensitive=True,
        note_ar="يكتب القيد وذمة التطبيق والاستهلاك النظري؛ لا يُمنح للكاشير",
    ),
    Entry(
        "sales.reverse_daily_sales",
        "عكس يوم مبيعات مرحّل",
        section_ar="المبيعات اليومية",
        kind="reverse",
        sensitive=True,
        note_ar="يعكس أيضاً المرتجعات المرحّلة وإقفالات الكاشير المعتمدة؛ صلاحية إشرافية على مستوى المنشأة",
    ),
    Entry(
        "sales.manage_sales_adjustments",
        "إدارة المرتجعات والإلغاءات",
        section_ar="المرتجعات والإلغاءات",
        kind="manage",
        sensitive=True,
        note_ar="صلاحية واحدة تغطي إنشاء المرتجع وترحيله بنطاق الفرع دون فصل بين المُعدّ والمرحِّل؛ لا تُمنح للكاشير ولا للمحاسب؛ عكس مرتجع مرحّل يحتاج صلاحية عكس يوم المبيعات",
    ),
    Entry(
        "sales.view_application_receivables",
        "عرض ذمم التطبيقات",
        section_ar="ذمم التطبيقات",
        kind="view",
        note_ar="يعرض ما تدين به تطبيقات التوصيل مقصوراً على فروع المستخدم",
    ),
    Entry(
        "sales.manage_application_settlements",
        "إدارة تسويات التطبيقات",
        section_ar="تسويات التطبيقات",
        kind="manage",
        sensitive=True,
        note_ar="صلاحية واحدة على مستوى المنشأة تغطي إنشاء التسوية ومطابقتها وترحيلها وعكسها وتسجيل فرق التسوية؛ لا تُمنح لمن يدير الاتفاقيات ولا للمحاسب",
    ),
    Entry(
        "sales.close_cashier_shift",
        "إقفال وردية الكاشير",
        section_ar="إقفال الكاشير",
        kind="other",
        note_ar="فتح الوردية وعدّ الدرج وإعلان الإقفال؛ لا يعتمده",
    ),
    Entry(
        "sales.approve_cashier_closing",
        "اعتماد إقفال الكاشير",
        section_ar="إقفال الكاشير",
        kind="approve",
        sensitive=True,
        note_ar="يثبت العجز أو الزيادة؛ لا يمكن لمن أقفل الوردية اعتمادها بنفسه",
    ),
    Entry(
        "accounting.view_journal",
        "عرض قيود اليومية",
        section_ar="قيود اليومية",
        kind="view",
        sensitive=True,
        note_ar="يكشف كل قيود الأستاذ بما فيها قيود الكلفة والرواتب",
    ),
    Entry(
        "accounting.create_draft",
        "إنشاء مسودة قيد",
        section_ar="قيود اليومية",
        kind="create",
    ),
    Entry(
        "accounting.edit_draft",
        "تعديل مسودة قيد",
        section_ar="قيود اليومية",
        kind="edit",
    ),
    Entry(
        "accounting.post_journal",
        "ترحيل قيد يومية",
        section_ar="قيود اليومية",
        kind="post",
        sensitive=True,
    ),
    Entry(
        "accounting.reverse_journal",
        "عكس قيد مرحّل",
        section_ar="قيود اليومية",
        kind="reverse",
        sensitive=True,
    ),
    Entry(
        "accounting.post_restricted_manual_journal",
        "ترحيل قيد يدوي على حساب مراقبة مقيّد",
        section_ar="قيود اليومية",
        kind="post",
        sensitive=True,
        note_ar="يتجاوز حماية الحسابات التي تملكها الدفاتر المساعدة (الموردون والمبيعات) ويكسر مطابقتها مع الأستاذ",
    ),
    Entry(
        "accounting.view_chart_of_accounts",
        "عرض دليل الحسابات",
        section_ar="دليل الحسابات",
        kind="view",
    ),
    Entry(
        "accounting.manage_chart_of_accounts",
        "إدارة دليل الحسابات",
        section_ar="دليل الحسابات",
        kind="manage",
        note_ar="إنشاء الحسابات وتعديلها وأرشفتها من شاشة الدليل",
    ),
    Entry(
        "accounting.manage_accounts",
        "إدارة الحسابات النظامية المحمية",
        section_ar="دليل الحسابات",
        kind="manage",
        sensitive=True,
        note_ar="الصلاحية الهيكلية العليا: تسمح بتغيير سياسة الترحيل اليدوي لحساب مراقبة مُهيّأ من النظام",
    ),
    Entry(
        "accounting.manage_report_mappings",
        "إدارة ربط الحسابات بمجموعات القوائم المالية",
        section_ar="دليل الحسابات",
        kind="manage",
        note_ar="يحدد موضع كل حساب في قائمة الدخل والميزانية العمومية",
    ),
    Entry(
        "accounting.manage_cost_centers",
        "إدارة مراكز الكلفة",
        section_ar="دليل الحسابات",
        kind="manage",
        note_ar="معرّفة في النظام ولا تحرسها شاشة بعد؛ اشتراط مركز الكلفة يُضبط من بطاقة الحساب في الدليل",
    ),
    Entry(
        "accounting.manage_account_mappings",
        "إدارة ربط الأدوار المحاسبية بالحسابات",
        section_ar="ربط الحسابات",
        kind="manage",
        sensitive=True,
        note_ar="يقرر الحساب الذي تهبط فيه ترحيلات كل الفروع",
    ),
    Entry(
        "accounting.manage_cashboxes",
        "إدارة الصناديق",
        section_ar="الصناديق",
        kind="manage",
    ),
    Entry(
        "accounting.manage_bank_accounts",
        "إدارة الحسابات البنكية",
        section_ar="الحسابات البنكية",
        kind="manage",
    ),
    Entry(
        "accounting.view_supplier_liabilities",
        "عرض ذمم الموردين",
        section_ar="ذمم الموردين",
        kind="view",
        note_ar="قراءة فقط: يكشف أسماء الموردين والمبالغ المستحقة لهم",
    ),
    Entry(
        "accounting.view_application_receivables",
        "عرض ذمم التطبيقات ومطابقتها مع الأستاذ",
        section_ar="ذمم التطبيقات",
        kind="view",
        note_ar="شاشة المحاسبة على مستوى المنشأة (الدفتر المساعد مقابل الأستاذ)؛ تختلف عن صلاحية المبيعات التي تعرض الذمم بنطاق فروع المستخدم",
    ),
    Entry(
        "accounting.manage_expense_vouchers",
        "إدارة سندات المصروفات",
        section_ar="المصروفات",
        kind="manage",
        note_ar="إنشاء السند وتعديله فقط؛ لا يشمل الاعتماد أو الترحيل",
    ),
    Entry(
        "accounting.approve_expense_vouchers",
        "اعتماد وترحيل سندات المصروفات",
        section_ar="المصروفات",
        kind="approve",
        sensitive=True,
        note_ar="يصرف نقد الفرع؛ لا يُسمح لمن أنشأ السند باعتماده",
    ),
    Entry(
        "accounting.manage_accruals",
        "إدارة المستحقات",
        section_ar="المستحقات والمقدمات",
        kind="manage",
        sensitive=True,
        note_ar="صلاحية واحدة تغطي إنشاء المستحق واعتماده وترحيله؛ لا فصل مهام داخلها",
    ),
    Entry(
        "accounting.manage_prepayments",
        "إدارة المقدمات",
        section_ar="المستحقات والمقدمات",
        kind="manage",
        sensitive=True,
        note_ar="صلاحية واحدة تغطي إنشاء المقدم واعتماده وإطفاءه؛ لا فصل مهام داخلها",
    ),
    Entry(
        "accounting.soft_close_period",
        "إغلاق مبدئي لفترة محاسبية",
        section_ar="الفترات المحاسبية",
        kind="other",
        sensitive=True,
    ),
    Entry(
        "accounting.close_period",
        "إغلاق فترة محاسبية",
        section_ar="الفترات المحاسبية",
        kind="other",
        sensitive=True,
    ),
    Entry(
        "accounting.reopen_period",
        "إعادة فتح فترة محاسبية",
        section_ar="الفترات المحاسبية",
        kind="other",
        sensitive=True,
    ),
    Entry(
        "accounting.post_soft_closed_adjustment",
        "ترحيل تسوية في فترة مغلقة مبدئيًا",
        section_ar="الفترات المحاسبية",
        kind="post",
        sensitive=True,
        note_ar="يتجاوز الإغلاق المبدئي؛ يُفحص مع صلاحية الترحيل على الفرع",
    ),
    Entry(
        "accounting.reverse_in_soft_closed_period",
        "عكس قيد في فترة مغلقة مبدئيًا",
        section_ar="الفترات المحاسبية",
        kind="reverse",
        sensitive=True,
        note_ar="يتجاوز الإغلاق المبدئي؛ يُفحص مع صلاحية العكس على الفرع",
    ),
    Entry(
        "accounting.close_fiscal_year",
        "إغلاق السنة المالية وإعادة فتحها",
        section_ar="الفترات المحاسبية",
        kind="other",
        sensitive=True,
        note_ar="أخطر إجراء في الوحدة؛ معرّف في النظام ولا تحرسه شاشة بعد",
    ),
    Entry(
        "hr.view_employee_workspace",
        "عرض ملفات الموظفين",
        section_ar="الموظفون",
        kind="view",
        note_ar="يفتح أيضاً شاشة النظرة العامة للموارد البشرية من دون أي رقم راتب فردي",
    ),
    Entry(
        "hr.manage_employee",
        "إدارة ملفات الموظفين",
        section_ar="الموظفون",
        kind="manage",
        note_ar="إنشاء الموظف وتعديله وإضافة مستنداته وأرشفته وإعادة تفعيله",
    ),
    Entry(
        "hr.terminate_employee",
        "إنهاء خدمة موظف",
        section_ar="الموظفون",
        kind="other",
        note_ar="إنهاء الخدمة بتاريخ وسبب مدوّن؛ الأرشفة وإعادة التفعيل تتبعان إدارة الملفات",
    ),
    Entry(
        "hr.view_employee_personal",
        "عرض البيانات الشخصية للموظف",
        section_ar="الموظفون",
        kind="view",
        sensitive=True,
        note_ar="رقم الهوية والهاتف والعنوان وتاريخ الميلاد وجهة اتصال الطوارئ",
    ),
    Entry(
        "hr.view_employee_salary",
        "عرض رواتب الموظفين",
        section_ar="العقود والأجور",
        kind="view",
        sensitive=True,
        note_ar="يكشف الأجر في العقد وإجمالي الرواتب الشهري في النظرة العامة",
    ),
    Entry(
        "hr.view_contract_workspace",
        "عرض عقود الموظفين",
        section_ar="العقود والأجور",
        kind="view",
        note_ar="من دون مبلغ الأجر ما لم تُمنح صلاحية عرض الرواتب",
    ),
    Entry(
        "hr.manage_contract",
        "إدارة عقود الموظفين",
        section_ar="العقود والأجور",
        kind="manage",
        note_ar="إنشاء العقود وتعديل المسودات فقط قبل الاعتماد",
    ),
    Entry(
        "hr.approve_contract",
        "اعتماد عقد موظف",
        section_ar="العقود والأجور",
        kind="approve",
        sensitive=True,
        note_ar="يجمّد نسخة الأجر التي يُحتسب منها الراتب؛ لا يعتمد المنشئ عقده",
    ),
    Entry(
        "hr.view_shift_workspace",
        "عرض الورديات والجداول",
        section_ar="الورديات",
        kind="view",
    ),
    Entry(
        "hr.manage_shift",
        "إدارة تعريفات الورديات",
        section_ar="الورديات",
        kind="manage",
    ),
    Entry(
        "hr.assign_shift",
        "تعيين ورديات الموظفين",
        section_ar="الورديات",
        kind="other",
    ),
    Entry(
        "hr.view_attendance_workspace",
        "عرض سجل الحضور والانصراف",
        section_ar="الحضور والانصراف",
        kind="view",
    ),
    Entry(
        "hr.record_attendance",
        "تسجيل حركات الحضور والانصراف",
        section_ar="الحضور والانصراف",
        kind="other",
    ),
    Entry(
        "hr.correct_attendance",
        "تصحيح حركات الحضور",
        section_ar="الحضور والانصراف",
        kind="other",
        note_ar="يعكس الحركة الخاطئة ويسجّل بديلاً بسبب مدوّن، لا يعدّل الأصل",
    ),
    Entry(
        "hr.approve_attendance",
        "اعتماد أيام الحضور",
        section_ar="الحضور والانصراف",
        kind="approve",
        sensitive=True,
        note_ar="يشمل إعادة فتح يوم معتمد",
    ),
    Entry(
        "hr.view_leave_workspace",
        "عرض الإجازات والغياب",
        section_ar="الإجازات والغياب",
        kind="view",
    ),
    Entry(
        "hr.request_leave",
        "إنشاء طلبات الإجازة",
        section_ar="الإجازات والغياب",
        kind="create",
        note_ar="يشمل تقديم الطلب وإلغاءه وإدارة أنواع الإجازات",
    ),
    Entry(
        "hr.approve_leave",
        "اعتماد طلبات الإجازة",
        section_ar="الإجازات والغياب",
        kind="approve",
        sensitive=True,
        note_ar="الموافقة أو الرفض بسبب؛ يحدد أيام الإجازة التي تدخل الراتب",
    ),
    Entry(
        "hr.classify_absence",
        "تصنيف غياب الموظفين",
        section_ar="الإجازات والغياب",
        kind="other",
        sensitive=True,
        note_ar="تصنيف يوم غياب مكتشف من سجل الحضور بسبب مدوّن، وينعكس على الراتب",
    ),
    Entry(
        "hr.view_overtime_workspace",
        "عرض طلبات العمل الإضافي",
        section_ar="العمل الإضافي",
        kind="view",
    ),
    Entry(
        "hr.manage_overtime",
        "إنشاء طلبات العمل الإضافي",
        section_ar="العمل الإضافي",
        kind="create",
        note_ar="الإنشاء والتقديم للاعتماد",
    ),
    Entry(
        "hr.approve_overtime",
        "اعتماد طلبات العمل الإضافي",
        section_ar="العمل الإضافي",
        kind="approve",
        sensitive=True,
    ),
    Entry(
        "hr.view_deduction_workspace",
        "عرض استقطاعات الموظفين",
        section_ar="الاستقطاعات",
        kind="view",
    ),
    Entry(
        "hr.manage_deduction",
        "إنشاء استقطاعات الموظفين",
        section_ar="الاستقطاعات",
        kind="create",
        note_ar="الإنشاء والتقديم للاعتماد",
    ),
    Entry(
        "hr.approve_deduction",
        "اعتماد استقطاعات الموظفين",
        section_ar="الاستقطاعات",
        kind="approve",
        sensitive=True,
    ),
    Entry(
        "hr.view_advance_workspace",
        "عرض سلف الموظفين",
        section_ar="السلف",
        kind="view",
    ),
    Entry(
        "hr.manage_advance",
        "إنشاء طلبات السلف",
        section_ar="السلف",
        kind="create",
        note_ar="الإنشاء والتقديم للاعتماد",
    ),
    Entry(
        "hr.approve_advance",
        "اعتماد سلف الموظفين",
        section_ar="السلف",
        kind="approve",
        sensitive=True,
        note_ar="لا يعتمد المنشئ سلفته",
    ),
    Entry(
        "hr.disburse_advance",
        "صرف سلف الموظفين",
        section_ar="السلف",
        kind="other",
        sensitive=True,
        note_ar="تسجيل دفع السلفة نقداً أو مصرفياً بقيد محاسبي؛ معرّفة في النظام ولا تحرسها شاشة بعد",
    ),
    Entry(
        "hr.view_payroll_workspace",
        "عرض تشغيلات الرواتب",
        section_ar="احتساب الرواتب",
        kind="view",
        note_ar="من دون المبالغ ما لم تُمنح صلاحية عرض مبالغ الرواتب",
    ),
    Entry(
        "hr.calculate_payroll",
        "احتساب الرواتب",
        section_ar="احتساب الرواتب",
        kind="other",
        note_ar="إنشاء تشغيل الرواتب واحتسابه من العقود والحضور والمدخلات المعتمدة",
    ),
    Entry(
        "hr.review_payroll",
        "مراجعة تشغيل الرواتب",
        section_ar="احتساب الرواتب",
        kind="other",
        note_ar="يشمل إعادة التشغيل إلى الاحتساب بسبب مدوّن",
    ),
    Entry(
        "hr.approve_payroll",
        "اعتماد الرواتب",
        section_ar="اعتماد الرواتب",
        kind="approve",
        sensitive=True,
        note_ar="يعتمده مستخدم غير المنشئ وغير الحاسب",
    ),
    Entry(
        "hr.post_payroll",
        "ترحيل الرواتب وعكسها",
        section_ar="احتساب الرواتب",
        kind="post",
        sensitive=True,
        note_ar="ترحيل التشغيل المعتمد إلى الدفاتر وإطلاقه للصرف وعكس تشغيل مرحّل بتاريخ وسبب",
    ),
    Entry(
        "hr.pay_payroll",
        "صرف الرواتب",
        section_ar="صرف الرواتب",
        kind="other",
        sensitive=True,
        note_ar="تسجيل دفعات الرواتب المرحّلة وعكس دفعة بتاريخ وسبب",
    ),
    Entry(
        "hr.view_payroll_amounts",
        "عرض مبالغ الرواتب",
        section_ar="احتساب الرواتب",
        kind="view",
        sensitive=True,
        note_ar="يكشف سطور الرواتب ومبالغها لكل موظف داخل التشغيل",
    ),
    Entry(
        "hr.view_employee_statement",
        "عرض كشوف الموظفين وقسائم الرواتب",
        section_ar="كشوف الموظفين",
        kind="view",
        sensitive=True,
        note_ar="كشف الرواتب والسلف والاستقطاعات والمدفوعات والحضور لكل موظف",
    ),
)
