# Generated by Django 5.2.17 on 2026-08-09 07:28

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_conversion_overlap_and_category_guards'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryLot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(help_text='Our reference for this batch. Unique per item.', max_length=64, verbose_name='lot code')),
                ('supplier_lot_code', models.CharField(blank=True, help_text='As printed by the supplier. Not case-folded — it is their vocabulary.', max_length=64, verbose_name='supplier lot code')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('received_on', models.DateField(blank=True, null=True, verbose_name='first received on')),
                ('produced_by_document_type', models.CharField(blank=True, max_length=100, verbose_name='produced by document type')),
                ('produced_by_document_id', models.CharField(blank=True, max_length=64, verbose_name='produced by document id')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical inventory lot',
                'verbose_name_plural': 'historical inventory lots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Our reference for this batch. Unique per item.', max_length=64, verbose_name='lot code')),
                ('supplier_lot_code', models.CharField(blank=True, help_text='As printed by the supplier. Not case-folded — it is their vocabulary.', max_length=64, verbose_name='supplier lot code')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('received_on', models.DateField(blank=True, null=True, verbose_name='first received on')),
                ('produced_by_document_type', models.CharField(blank=True, max_length=100, verbose_name='produced by document type')),
                ('produced_by_document_id', models.CharField(blank=True, max_length=64, verbose_name='produced by document id')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.inventoryitem', verbose_name='item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'inventory lot',
                'verbose_name_plural': 'inventory lots',
                'ordering': ['item__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source_document_type', models.CharField(blank=True, max_length=100, verbose_name='source document type')),
                ('source_document_id', models.CharField(blank=True, max_length=64, verbose_name='source document id')),
                ('source_event', models.CharField(blank=True, choices=[('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], help_text='Blank only for a posting with no upstream document.', max_length=16, verbose_name='source event')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='idempotency key')),
                ('request_fingerprint', models.CharField(max_length=64, verbose_name='request fingerprint')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('posted_at', models.DateTimeField(verbose_name='posted at')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='reference')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockledgerentry', verbose_name='reverses')),
            ],
            options={
                'verbose_name': 'stock ledger entry',
                'verbose_name_plural': 'stock ledger entries',
                'ordering': ['-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'رصيد افتتاحي'), ('RECEIPT', 'إدخال'), ('ISSUE', 'صرف'), ('TRANSFER_OUT', 'تحويل صادر'), ('TRANSFER_IN', 'تحويل وارد'), ('WASTE', 'هالك'), ('COUNT_GAIN', 'فائض جرد'), ('COUNT_LOSS', 'عجز جرد'), ('PRODUCTION_IN', 'إنتاج وارد'), ('PRODUCTION_OUT', 'صرف للإنتاج'), ('MANUAL_ADJUSTMENT', 'تسوية يدوية'), ('REVERSAL', 'عكس قيد')], max_length=20, verbose_name='movement type')),
                ('effect_key', models.CharField(max_length=120, verbose_name='effect key')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('inventory_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='inventory value')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit cost')),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity before')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity after')),
                ('value_before', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='value before')),
                ('value_after', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='value after')),
                ('average_before', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='average before')),
                ('average_after', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='average after')),
                ('posted_sequence', models.BigIntegerField(verbose_name='posted sequence')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='posted at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.branch', verbose_name='branch')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockledgerentry', verbose_name='ledger entry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventoryitem', verbose_name='item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventorylot', verbose_name='lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.organization', verbose_name='organization')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='inventory.stockmovement', verbose_name='reverses movement')),
                ('source_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.itempackageconversion', verbose_name='source conversion')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-posted_sequence'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='quantity')),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=21, verbose_name='value')),
                ('average_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=21, verbose_name='average cost')),
                ('last_posted_sequence', models.BigIntegerField(default=0, verbose_name='last posted sequence')),
                ('version', models.PositiveBigIntegerField(default=0, verbose_name='version')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='frozen')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='organizations.branch', verbose_name='branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.inventoryitem', verbose_name='item')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.inventorylot', verbose_name='lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='organizations.organization', verbose_name='organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.warehouse', verbose_name='warehouse')),
                ('last_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockmovement', verbose_name='last movement')),
            ],
            options={
                'verbose_name': 'stock balance',
                'verbose_name_plural': 'stock balances',
                'ordering': ['warehouse__code', 'item__code'],
            },
        ),
        migrations.CreateModel(
            name='StockPostingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.BigIntegerField(default=0, verbose_name='last sequence')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_posting_sequence', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'stock posting sequence',
                'verbose_name_plural': 'stock posting sequences',
            },
        ),
        migrations.CreateModel(
            name='ValuationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='received quantity')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='remaining quantity')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit cost')),
                ('posted_sequence', models.BigIntegerField(verbose_name='posted sequence')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_layers', to='inventory.inventoryitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuation_layers', to='inventory.inventorylot')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_layer', to='inventory.stockmovement', verbose_name='inbound movement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_layers', to='organizations.organization', verbose_name='organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_layers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'valuation layer',
                'verbose_name_plural': 'valuation layers',
                'ordering': ['posted_sequence'],
            },
        ),
        migrations.CreateModel(
            name='ValuationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity')),
                ('strategy', models.CharField(max_length=32, verbose_name='strategy')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_allocations', to='inventory.stockmovement', verbose_name='outbound movement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_allocations', to='organizations.organization', verbose_name='organization')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.valuationlayer', verbose_name='layer')),
            ],
            options={
                'verbose_name': 'valuation allocation',
                'verbose_name_plural': 'valuation allocations',
                'ordering': ['movement_id', 'layer_id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['organization', 'expiry_date'], name='lot_org_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('item', 'code'), name='inventory_lot_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='inventory_lot_code_not_empty'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['organization', 'effective_at'], name='stock_entry_org_effective_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['source_document_type', 'source_document_id'], name='stock_entry_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_document_id', ''), ('source_document_type', ''), ('source_event', '')), models.Q(models.Q(('source_document_type', ''), _negated=True), models.Q(('source_document_id', ''), _negated=True), models.Q(('source_event', ''), _negated=True)), _connector='OR'), name='stock_entry_source_identity_all_or_none'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('source_event__in', ['', 'POSTED', 'REVERSED'])), name='stock_entry_source_event_is_known'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), name='stock_entry_idempotency_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='stock_entry_idempotency_key_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event', ''), _negated=True), fields=('organization', 'source_document_type', 'source_document_id', 'source_event'), name='stock_entry_source_event_unique_per_organization'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'posted_sequence'], name='movement_org_sequence_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'item', 'lot'], name='movement_stock_key_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'effective_at'], name='movement_item_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('organization', 'posted_sequence'), name='stock_movement_sequence_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('entry', 'effect_key'), name='stock_movement_effect_key_unique_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('effect_key', ''), _negated=True), name='stock_movement_effect_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gt', Decimal('0')), ('value_after', Decimal('0')), _connector='OR'), name='stock_movement_zero_quantity_has_zero_value'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', Decimal('0'))), name='stock_movement_quantity_after_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('value_after__gte', Decimal('0'))), name='stock_movement_value_after_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reverses', models.F('id')), _negated=True), name='stock_movement_does_not_reverse_itself'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['organization', 'item'], name='balance_org_item_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['branch', 'item'], name='balance_branch_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item', 'lot'), name='stock_balance_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', Decimal('0'))), name='stock_balance_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0'))), name='stock_balance_value_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', Decimal('0'))), name='stock_balance_average_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0')), ('value', Decimal('0')), _connector='OR'), name='stock_balance_zero_quantity_has_zero_value'),
        ),
        migrations.AddConstraint(
            model_name='stockpostingsequence',
            constraint=models.CheckConstraint(condition=models.Q(('last_sequence__gte', 0)), name='stock_sequence_not_negative'),
        ),
        migrations.AddIndex(
            model_name='valuationlayer',
            index=models.Index(fields=['warehouse', 'item', 'lot', 'posted_sequence'], name='layer_stock_key_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='valuationlayer',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gt', Decimal('0'))), name='valuation_layer_received_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='valuationlayer',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', Decimal('0'))), name='valuation_layer_remaining_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='valuationlayer',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0'))), name='valuation_layer_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='valuationallocation',
            constraint=models.UniqueConstraint(fields=('movement', 'layer'), name='valuation_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='valuationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='valuation_allocation_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='valuationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('strategy', ''), _negated=True), name='valuation_allocation_strategy_named'),
        ),
    ]
