# Generated by Django 5.2.17 on 2026-08-09 10:24

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountrole_historicalaccountrole_and_more'),
        ('inventory', '0004_stock_ledger_immutability'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('view_item', 'Can view the item master'), ('manage_items', 'Can create and archive inventory items'), ('manage_conversions', 'Can manage item package conversions'), ('view_stock', 'Can view stock on hand'), ('view_valuation', 'Can view inventory cost and valuation'), ('create_draft_movement', 'Can create a draft stock movement'), ('create_opening_stock', 'Can prepare and submit an opening stock document'), ('post_opening_stock', 'Can post opening stock'), ('post_receipt', 'Can post a stock receipt'), ('post_issue', 'Can post a stock issue'), ('post_transfer', 'Can post a stock transfer'), ('post_waste', 'Can post stock waste'), ('conduct_stock_count', 'Can conduct a stock count'), ('approve_stock_count', 'Can approve a stock count'), ('post_adjustment', 'Can post a stock adjustment'), ('reverse_movement', 'Can reverse a stock movement'), ('override_negative_stock', 'Can post stock below zero')], 'verbose_name': 'inventory item', 'verbose_name_plural': 'inventory items'},
        ),
        migrations.CreateModel(
            name='HistoricalInventoryAccountMapping',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='account')),
                ('account_role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.accountrole', verbose_name='account role')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.itemcategory', verbose_name='category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventoryitem', verbose_name='item')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical inventory account mapping',
                'verbose_name_plural': 'historical inventory account mappings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_mappings', to='accounting.account', verbose_name='account')),
                ('account_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_mappings', to='accounting.accountrole', verbose_name='account role')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='inventory.itemcategory', verbose_name='category')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='inventory.inventoryitem', verbose_name='item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_account_mappings', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'inventory account mapping',
                'verbose_name_plural': 'inventory account mappings',
                'ordering': ['organization__code', 'account_role__code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي')], max_length=32, verbose_name='document type')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_sequences', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'inventory document sequence',
                'verbose_name_plural': 'inventory document sequences',
            },
        ),
        migrations.CreateModel(
            name='OpeningStockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('document_number', models.CharField(blank=True, max_length=32, verbose_name='document number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدَّم'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('cutoff_at', models.DateTimeField(verbose_name='cutoff at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence reference')),
                ('narration', models.TextField(blank=True, verbose_name='narration')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_documents', to='organizations.branch', verbose_name='branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_opening_documents', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_documents', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_documents', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_opening_documents', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_opening_documents', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_opening_documents', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_documents', to='inventory.stockledgerentry', verbose_name='stock ledger entry')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_opening_documents', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'opening stock document',
                'verbose_name_plural': 'opening stock documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningStockLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('entered_package_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='entered package quantity')),
                ('measured_base_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='measured base quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='unit cost')),
                ('total_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='total value')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.openingstockdocument', verbose_name='document')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_lines', to='accounting.account', verbose_name='inventory account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_lines', to='inventory.inventoryitem', verbose_name='item')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_lines', to='accounting.journalline', verbose_name='journal line')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_lines', to='inventory.inventorylot', verbose_name='lot')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_line', to='inventory.stockmovement', verbose_name='stock movement')),
                ('package_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_lines', to='inventory.itempackageconversion', verbose_name='package conversion')),
                ('resolved_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_lines', to='inventory.inventoryaccountmapping', verbose_name='resolved inventory mapping')),
                ('resolved_organization_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_opening_lines', to='accounting.organizationaccountmapping', verbose_name='resolved organization mapping')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_lines', to='inventory.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'opening stock line',
                'verbose_name_plural': 'opening stock lines',
                'ordering': ['document_id', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryaccountmapping',
            index=models.Index(fields=['organization', 'account_role', 'is_active'], name='inv_mapping_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaccountmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('category__isnull', True)), models.Q(('item__isnull', True), ('category__isnull', False)), _connector='OR'), name='inventory_mapping_one_target'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaccountmapping',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='inventory_mapping_period_is_ordered'),
        ),
        migrations.AddConstraint(
            model_name='inventoryaccountmapping',
            constraint=models.UniqueConstraint(fields=('organization', 'account_role', 'item', 'category', 'version'), name='inventory_mapping_version_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='inventorydocumentsequence',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'year'), name='inventory_document_sequence_unique_scope'),
        ),
        migrations.AddIndex(
            model_name='openingstockdocument',
            index=models.Index(fields=['organization', 'status'], name='opening_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='openingstockdocument',
            index=models.Index(fields=['branch', 'status'], name='opening_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_reference', ''), _negated=True), name='opening_evidence_reference_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['DRAFT', 'SUBMITTED']), ('document_number', '')), models.Q(('status__in', ['POSTED', 'REVERSED']), models.Q(('document_number', ''), _negated=True)), _connector='OR'), name='opening_numbered_iff_posted'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('organization', 'document_number'), name='opening_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('submitted_by__isnull', False), ('submitted_at__isnull', False)), _connector='OR'), name='opening_submitted_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['POSTED', 'REVERSED']), _negated=True), models.Q(('posted_by__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='opening_posted_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversed_by__isnull', False), ('reversed_at__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='opening_reversed_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('posted_by__isnull', True), ('submitted_by__isnull', True), models.Q(('posted_by', models.F('submitted_by')), _negated=True), _connector='OR'), name='opening_submitter_is_not_poster'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='opening_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.UniqueConstraint(fields=('document', 'warehouse', 'item', 'lot'), name='opening_line_valuation_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', Decimal('0'))), name='opening_line_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', Decimal('0'))), name='opening_line_unit_cost_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.CheckConstraint(condition=models.Q(('total_value__gt', Decimal('0'))), name='opening_line_value_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.CheckConstraint(condition=models.Q(('entered_package_quantity__isnull', True), ('entered_package_quantity__gt', Decimal('0')), _connector='OR'), name='opening_line_package_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.CheckConstraint(condition=models.Q(('measured_base_quantity__isnull', True), ('measured_base_quantity__gt', Decimal('0')), _connector='OR'), name='opening_line_measured_positive'),
        ),
        migrations.AddConstraint(
            model_name='openingstockline',
            constraint=models.CheckConstraint(condition=models.Q(('measured_base_quantity__isnull', True), ('package_conversion__isnull', False), _connector='OR'), name='opening_line_measured_needs_package'),
        ),
    ]
