# Generated by Django 5.2.17 on 2026-08-09 21:21

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_account_role_seed_and_guards'),
        ('inventory', '0006_opening_document_guards'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbalance',
            name='control_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='accounting.account', verbose_name='inventory control account'),
        ),
        # `preserve_default=False`: the epoch is a one-off value for the ALTER
        # only, never a model default. A business date is derived from a real
        # branch cutoff and a real moment; a row that defaulted to one would be
        # a posting claiming to belong to a day nobody chose. The ledger tables
        # are empty at this migration, so no row ever receives it.
        migrations.AddField(
            model_name='stockledgerentry',
            name='business_date',
            field=models.DateField(db_index=True, default=datetime.date(1970, 1, 1), verbose_name='business date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='control_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='accounting.account', verbose_name='inventory control account'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0')), ('control_account__isnull', True), _connector='OR'), name='stock_balance_empty_position_has_no_control_account'),
        ),
    ]
