# Generated by Django 5.2.17 on 2026-08-09 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_account_role_seed_and_guards'),
        ('inventory', '0007_business_date_and_control_account'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openingstockdocument',
            name='business_date_timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='business date timezone'),
        ),
        migrations.AddField(
            model_name='openingstockdocument',
            name='business_day_start',
            field=models.TimeField(blank=True, null=True, verbose_name='business day start'),
        ),
        migrations.AddConstraint(
            model_name='openingstockdocument',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(models.Q(('business_date_timezone', ''), _negated=True), ('business_day_start__isnull', False)), _connector='OR'), name='opening_business_date_snapshot_present'),
        ),
    ]
