# Generated by Django 5.2.17 on 2026-08-09 21:49

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_operational_account_roles'),
        ('inventory', '0008_opening_business_date_snapshot'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('view_item', 'Can view the item master'), ('manage_items', 'Can create and archive inventory items'), ('manage_conversions', 'Can manage item package conversions'), ('view_stock', 'Can view stock on hand'), ('view_valuation', 'Can view inventory cost and valuation'), ('create_draft_movement', 'Can create a draft stock movement'), ('create_opening_stock', 'Can prepare and submit an opening stock document'), ('post_opening_stock', 'Can post opening stock'), ('post_receipt', 'Can post a stock receipt'), ('post_issue', 'Can post a stock issue'), ('post_return_in', 'Can return previously issued stock to inventory'), ('post_transfer', 'Can post a stock transfer'), ('post_waste', 'Can post stock waste'), ('conduct_stock_count', 'Can conduct a stock count'), ('approve_stock_count', 'Can approve a stock count'), ('post_adjustment', 'Can post a stock adjustment'), ('reverse_movement', 'Can reverse a stock movement'), ('override_negative_stock', 'Can post stock below zero')], 'verbose_name': 'inventory item', 'verbose_name_plural': 'inventory items'},
        ),
        migrations.AlterField(
            model_name='inventorydocumentsequence',
            name='document_type',
            field=models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي'), ('INVENTORY_RECEIPT', 'استلام مخزني غير مفوتر'), ('INVENTORY_ISSUE', 'صرف مخزني للاستهلاك'), ('INVENTORY_RETURN_IN', 'إرجاع من صرف سابق')], max_length=32, verbose_name='document type'),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryMovementDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('document_number', models.CharField(blank=True, max_length=32, verbose_name='document number')),
                ('document_type', models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي'), ('INVENTORY_RECEIPT', 'استلام مخزني غير مفوتر'), ('INVENTORY_ISSUE', 'صرف مخزني للاستهلاك'), ('INVENTORY_RETURN_IN', 'إرجاع من صرف سابق')], max_length=32, verbose_name='document type')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('evidence_reference', models.CharField(help_text='Delivery note, requisition, or return slip. Required.', max_length=200, verbose_name='evidence reference')),
                ('narration', models.TextField(blank=True, verbose_name='narration')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch')),
                ('cost_center', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.costcenter', verbose_name='cost center')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('stock_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockledgerentry', verbose_name='stock ledger entry')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'historical inventory movement document',
                'verbose_name_plural': 'historical inventory movement documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryMovementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('document_number', models.CharField(blank=True, max_length=32, verbose_name='document number')),
                ('document_type', models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي'), ('INVENTORY_RECEIPT', 'استلام مخزني غير مفوتر'), ('INVENTORY_ISSUE', 'صرف مخزني للاستهلاك'), ('INVENTORY_RETURN_IN', 'إرجاع من صرف سابق')], max_length=32, verbose_name='document type')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('evidence_reference', models.CharField(help_text='Delivery note, requisition, or return slip. Required.', max_length=200, verbose_name='evidence reference')),
                ('narration', models.TextField(blank=True, verbose_name='narration')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='organizations.branch', verbose_name='branch')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='accounting.costcenter', verbose_name='cost center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_documents', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='accounting.journalentry', verbose_name='journal entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='organizations.organization', verbose_name='organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_inventory_documents', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_inventory_documents', to='accounting.journalentry', verbose_name='reversal journal entry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_inventory_documents', to=settings.AUTH_USER_MODEL, verbose_name='reversed by')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='inventory.stockledgerentry', verbose_name='stock ledger entry')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='inventory.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'inventory movement document',
                'verbose_name_plural': 'inventory movement documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovementDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('entered_package_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='entered package quantity')),
                ('measured_base_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='measured base quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='base quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True, verbose_name='unit cost')),
                ('total_value', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='total value')),
                ('contra_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_contra_lines', to='accounting.account', verbose_name='contra account')),
                ('contra_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_lines', to='accounting.costcenter', verbose_name='contra cost center')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorymovementdocument', verbose_name='document')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_lines', to='accounting.account', verbose_name='inventory account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='inventory.inventoryitem', verbose_name='item')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_lines', to='accounting.journalline', verbose_name='journal line')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='inventory.inventorylot', verbose_name='lot')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_line', to='inventory.stockmovement', verbose_name='stock movement')),
                ('package_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='inventory.itempackageconversion', verbose_name='package conversion')),
                ('resolved_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='inventory.inventoryaccountmapping', verbose_name='resolved inventory mapping')),
                ('resolved_organization_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_document_lines', to='accounting.organizationaccountmapping', verbose_name='resolved organization mapping')),
                ('source_issue_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.inventorymovementdocumentline', verbose_name='source issue line')),
            ],
            options={
                'verbose_name': 'inventory document line',
                'verbose_name_plural': 'inventory document lines',
                'ordering': ['document_id', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorymovementdocument',
            index=models.Index(fields=['organization', 'document_type', 'status'], name='inv_doc_org_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovementdocument',
            index=models.Index(fields=['warehouse', 'business_date'], name='inv_doc_wh_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_reference', ''), _negated=True), name='inventory_document_evidence_reference_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ['INVENTORY_RECEIPT', 'INVENTORY_ISSUE', 'INVENTORY_RETURN_IN'])), name='inventory_document_type_is_operational'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('document_number', '')), models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('document_number', ''), _negated=True)), _connector='OR'), name='inventory_document_numbered_iff_posted'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('organization', 'document_number'), name='inventory_document_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('posted_by__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='inventory_document_posted_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(models.Q(('business_date_timezone', ''), _negated=True), ('business_day_start__isnull', False)), _connector='OR'), name='inventory_document_business_date_snapshot_present'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversed_by__isnull', False), ('reversed_at__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='inventory_document_reversed_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='inventory_document_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.UniqueConstraint(fields=('document', 'item', 'lot'), name='inventory_document_line_valuation_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('base_quantity__gt', Decimal('0'))), name='inventory_document_line_quantity_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gt', Decimal('0')), _connector='OR'), name='inventory_document_line_unit_cost_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('total_value__isnull', True), ('total_value__gt', Decimal('0')), _connector='OR'), name='inventory_document_line_value_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('entered_package_quantity__isnull', True), ('entered_package_quantity__gt', Decimal('0')), _connector='OR'), name='inventory_document_line_package_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('measured_base_quantity__isnull', True), ('measured_base_quantity__gt', Decimal('0')), _connector='OR'), name='inventory_document_line_measured_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('measured_base_quantity__isnull', True), ('package_conversion__isnull', False), _connector='OR'), name='inventory_document_line_measured_needs_package'),
        ),
    ]
