# Generated by Django 5.2.17 on 2026-08-10 04:30

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_inter_branch_clearing_role'),
        ('inventory', '0013_transfer_guards'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        ('units', '0002_historicalunitofmeasure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryAdjustmentDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('document_number', models.CharField(blank=True, max_length=32, verbose_name='document number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence reference')),
                ('reason', models.TextField(verbose_name='reason')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical inventory adjustment',
                'verbose_name_plural': 'historical inventory adjustments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryReasonCode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(help_text='Canonicalised to upper case. Reserved forever once used.', max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('applies_to', models.CharField(choices=[('WASTE', 'إتلاف'), ('COUNT_VARIANCE', 'فروقات الجرد'), ('MANUAL_ADJUSTMENT', 'تسوية يدوية')], max_length=20, verbose_name='applies to')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='requires a comment')),
                ('requires_evidence', models.BooleanField(default=False, verbose_name='requires evidence')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical inventory reason code',
                'verbose_name_plural': 'historical inventory reason codes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockCount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='public id')),
                ('count_number', models.CharField(blank=True, max_length=32, verbose_name='count number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_PROGRESS', 'جاري الجرد'), ('SUBMITTED', 'مقدّم للاعتماد'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغى'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=12, verbose_name='status')),
                ('scope_type', models.CharField(choices=[('FULL_WAREHOUSE', 'جرد كامل للمخزن')], default='FULL_WAREHOUSE', max_length=20, verbose_name='scope')),
                ('cutoff_at', models.DateTimeField(blank=True, null=True, verbose_name='cutoff at')),
                ('business_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='evidence reference')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical stock count',
                'verbose_name_plural': 'historical stock counts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('document_number', models.CharField(blank=True, max_length=32, verbose_name='document number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحّل'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=10, verbose_name='status')),
                ('effective_at', models.DateTimeField(verbose_name='effective at')),
                ('business_date', models.DateField(verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('evidence_reference', models.CharField(max_length=200, verbose_name='evidence reference')),
                ('reason', models.TextField(verbose_name='reason')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
            ],
            options={
                'verbose_name': 'inventory adjustment',
                'verbose_name_plural': 'inventory adjustments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('kind', models.CharField(choices=[('QUANTITY_GAIN', 'زيادة كمية'), ('QUANTITY_LOSS', 'نقص كمية'), ('VALUE_ONLY', 'إعادة تقييم بالقيمة فقط')], max_length=16, verbose_name='kind')),
                ('entered_package_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='entered package quantity')),
                ('measured_base_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='measured base quantity')),
                ('base_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, verbose_name='base quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True, verbose_name='unit cost')),
                ('zero_cost_confirmed', models.BooleanField(default=False, verbose_name='zero cost confirmed')),
                ('value_adjustment', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='value adjustment')),
                ('total_value', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='total value')),
                ('line_comment', models.CharField(blank=True, max_length=200, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'inventory adjustment line',
                'verbose_name_plural': 'inventory adjustment lines',
                'ordering': ['document_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Canonicalised to upper case. Reserved forever once used.', max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('applies_to', models.CharField(choices=[('WASTE', 'إتلاف'), ('COUNT_VARIANCE', 'فروقات الجرد'), ('MANUAL_ADJUSTMENT', 'تسوية يدوية')], max_length=20, verbose_name='applies to')),
                ('requires_comment', models.BooleanField(default=False, verbose_name='requires a comment')),
                ('requires_evidence', models.BooleanField(default=False, verbose_name='requires evidence')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'inventory reason code',
                'verbose_name_plural': 'inventory reason codes',
                'ordering': ['organization__code', 'applies_to', 'code'],
                'permissions': [('manage_reason_codes', 'Can create and archive inventory reason codes')],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('count_number', models.CharField(blank=True, max_length=32, verbose_name='count number')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('IN_PROGRESS', 'جاري الجرد'), ('SUBMITTED', 'مقدّم للاعتماد'), ('POSTED', 'مرحّل'), ('CANCELLED', 'ملغى'), ('REVERSED', 'معكوس')], default='DRAFT', max_length=12, verbose_name='status')),
                ('scope_type', models.CharField(choices=[('FULL_WAREHOUSE', 'جرد كامل للمخزن')], default='FULL_WAREHOUSE', max_length=20, verbose_name='scope')),
                ('cutoff_at', models.DateTimeField(blank=True, null=True, verbose_name='cutoff at')),
                ('business_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='business date')),
                ('business_date_timezone', models.CharField(blank=True, max_length=64, verbose_name='business date timezone')),
                ('business_day_start', models.TimeField(blank=True, null=True, verbose_name='business day start')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='evidence reference')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('reversal_reason', models.TextField(blank=True, verbose_name='reversal reason')),
            ],
            options={
                'verbose_name': 'stock count',
                'verbose_name_plural': 'stock counts',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('line_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='line uid')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
                ('book_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='book quantity')),
                ('book_value', models.DecimalField(decimal_places=3, max_digits=21, verbose_name='book value')),
                ('book_average', models.DecimalField(decimal_places=6, max_digits=21, verbose_name='book average cost')),
                ('book_posted_sequence', models.BigIntegerField(default=0, verbose_name='posted sequence at cutoff')),
                ('is_unexpected', models.BooleanField(default=False, verbose_name='unexpected stock')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='counted quantity')),
                ('entered_package_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='entered package quantity')),
                ('measured_base_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='measured base quantity')),
                ('line_note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('approved_unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True, verbose_name='approved unit cost')),
                ('zero_cost_confirmed', models.BooleanField(default=False, verbose_name='zero cost confirmed')),
                ('variance_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='variance quantity')),
                ('variance_value', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True, verbose_name='variance value')),
            ],
            options={
                'verbose_name': 'stock count line',
                'verbose_name_plural': 'stock count lines',
                'ordering': ['count_id', 'sequence'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inventorymovementdocument',
            name='inventory_document_type_is_operational',
        ),
        migrations.AddField(
            model_name='inventorymovementdocumentline',
            name='line_comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovementdocument',
            name='document_type',
            field=models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي'), ('INVENTORY_RECEIPT', 'استلام مخزني غير مفوتر'), ('INVENTORY_ISSUE', 'صرف مخزني للاستهلاك'), ('INVENTORY_RETURN_IN', 'إرجاع من صرف سابق'), ('INVENTORY_TRANSFER', 'تحويل مخزني'), ('INVENTORY_TRANSFER_RECEIPT', 'استلام تحويل'), ('INVENTORY_TRANSFER_SHORTAGE', 'إقفال عجز تحويل'), ('INVENTORY_WASTE', 'إتلاف مخزني'), ('INVENTORY_STOCK_COUNT', 'جرد فعلي'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزنية يدوية')], max_length=32, verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='inventorydocumentsequence',
            name='document_type',
            field=models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي'), ('INVENTORY_RECEIPT', 'استلام مخزني غير مفوتر'), ('INVENTORY_ISSUE', 'صرف مخزني للاستهلاك'), ('INVENTORY_RETURN_IN', 'إرجاع من صرف سابق'), ('INVENTORY_TRANSFER', 'تحويل مخزني'), ('INVENTORY_TRANSFER_RECEIPT', 'استلام تحويل'), ('INVENTORY_TRANSFER_SHORTAGE', 'إقفال عجز تحويل'), ('INVENTORY_WASTE', 'إتلاف مخزني'), ('INVENTORY_STOCK_COUNT', 'جرد فعلي'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزنية يدوية')], max_length=32, verbose_name='document type'),
        ),
        migrations.AlterField(
            model_name='inventorymovementdocument',
            name='document_type',
            field=models.CharField(choices=[('INVENTORY_OPENING', 'رصيد افتتاحي'), ('INVENTORY_RECEIPT', 'استلام مخزني غير مفوتر'), ('INVENTORY_ISSUE', 'صرف مخزني للاستهلاك'), ('INVENTORY_RETURN_IN', 'إرجاع من صرف سابق'), ('INVENTORY_TRANSFER', 'تحويل مخزني'), ('INVENTORY_TRANSFER_RECEIPT', 'استلام تحويل'), ('INVENTORY_TRANSFER_SHORTAGE', 'إقفال عجز تحويل'), ('INVENTORY_WASTE', 'إتلاف مخزني'), ('INVENTORY_STOCK_COUNT', 'جرد فعلي'), ('INVENTORY_ADJUSTMENT', 'تسوية مخزنية يدوية')], max_length=32, verbose_name='document type'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovementdocument',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ['INVENTORY_RECEIPT', 'INVENTORY_ISSUE', 'INVENTORY_RETURN_IN', 'INVENTORY_WASTE'])), name='inventory_document_type_is_operational'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.costcenter', verbose_name='cost center'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='posted by'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='reversed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='stock_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockledgerentry', verbose_name='stock ledger entry'),
        ),
        migrations.AddField(
            model_name='historicalinventoryadjustmentdocument',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='historicalinventoryreasoncode',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventoryreasoncode',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='conducted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='conducted by'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.costcenter', verbose_name='cost center'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='journal entry'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='reversal journal entry'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='reversal_stock_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockledgerentry', verbose_name='reversal stock entry'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='reversed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reversed by'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='stock_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockledgerentry', verbose_name='stock ledger entry'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='submitted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='historicalstockcount',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='accounting.costcenter', verbose_name='cost center'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='accounting.journalentry', verbose_name='journal entry'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='posted by'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_inventory_adjustments', to='accounting.journalentry', verbose_name='reversal journal entry'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='reversed by'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='stock_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='inventory.stockledgerentry', verbose_name='stock ledger entry'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentdocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='inventory.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='control_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='accounting.account', verbose_name='control account'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryadjustmentdocument', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.inventoryitem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.inventorylot', verbose_name='lot'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_line', to='inventory.stockmovement', verbose_name='stock movement'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='package_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.itempackageconversion', verbose_name='package conversion'),
        ),
        migrations.AddField(
            model_name='inventoryreasoncode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reason_codes', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentline',
            name='reason_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.inventoryreasoncode', verbose_name='reason code'),
        ),
        migrations.AddField(
            model_name='inventorymovementdocumentline',
            name='reason_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_lines', to='inventory.inventoryreasoncode', verbose_name='reason code'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='organizations.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conducted_stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='conducted by'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='accounting.costcenter', verbose_name='cost center'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='accounting.journalentry', verbose_name='journal entry'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='organizations.organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_stock_counts', to='accounting.journalentry', verbose_name='reversal journal entry'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reversal_stock_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_stock_counts', to='inventory.stockledgerentry', verbose_name='reversal stock entry'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='reversed by'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='stock_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.stockledgerentry', verbose_name='stock ledger entry'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='frozen_by_count',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockcount', verbose_name='frozen by count'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='frozen_by_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frozen_warehouse_links', to='inventory.stockcount', verbose_name='frozen by count'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('frozen_by_count__isnull', False)), fields=('frozen_by_count',), name='warehouse_freeze_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('frozen_by_count__isnull', True), models.Q(('warehouse_type', 'IN_TRANSIT'), _negated=True), _connector='OR'), name='warehouse_in_transit_is_never_counted'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='units.unitofmeasure', verbose_name='base unit'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='book_control_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='accounting.account', verbose_name='book control account'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='book_last_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockmovement', verbose_name='last movement at cutoff'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='count'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.inventoryitem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.inventorylot', verbose_name='lot'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_line', to='inventory.stockmovement', verbose_name='stock movement'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='package_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.itempackageconversion', verbose_name='package conversion'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='reason_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_lines', to='inventory.inventoryreasoncode', verbose_name='reason code'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentdocument',
            index=models.Index(fields=['organization', 'status'], name='inv_adjustment_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentdocument',
            index=models.Index(fields=['warehouse', 'business_date'], name='inv_adjustment_wh_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_reference', ''), _negated=True), name='inventory_adjustment_evidence_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inventory_adjustment_reason_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('document_number', '')), models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('document_number', ''), _negated=True)), _connector='OR'), name='inventory_adjustment_numbered_iff_posted'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('organization', 'document_number'), name='inventory_adjustment_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('posted_by__isnull', False), ('posted_at__isnull', False)), _connector='OR'), name='inventory_adjustment_posted_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(models.Q(('business_date_timezone', ''), _negated=True), ('business_day_start__isnull', False)), _connector='OR'), name='inventory_adjustment_business_date_snapshot_present'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversed_by__isnull', False), ('reversed_at__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='inventory_adjustment_reversed_fields_present'),
        ),
        migrations.AddIndex(
            model_name='inventoryreasoncode',
            index=models.Index(fields=['organization', 'applies_to', 'is_active'], name='reason_code_org_use_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreasoncode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='inventory_reason_code_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreasoncode',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9._-]*$')), name='inventory_reason_code_format'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreasoncode',
            constraint=models.CheckConstraint(condition=models.Q(('name_ar', ''), _negated=True), name='inventory_reason_code_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreasoncode',
            constraint=models.CheckConstraint(condition=models.Q(('applies_to__in', ['WASTE', 'COUNT_VARIANCE', 'MANUAL_ADJUSTMENT'])), name='inventory_reason_code_application_is_known'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.UniqueConstraint(fields=('document', 'sequence'), name='inventory_adjustment_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.UniqueConstraint(fields=('document', 'item', 'lot'), name='inventory_adjustment_line_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['QUANTITY_GAIN', 'QUANTITY_LOSS', 'VALUE_ONLY'])), name='inventory_adjustment_line_kind_is_known'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['QUANTITY_GAIN', 'QUANTITY_LOSS']), ('base_quantity__gt', Decimal('0'))), models.Q(('kind', 'VALUE_ONLY'), ('base_quantity', Decimal('0'))), _connector='OR'), name='inventory_adjustment_line_quantity_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'QUANTITY_GAIN'), ('unit_cost__isnull', False)), models.Q(models.Q(('kind', 'QUANTITY_GAIN'), _negated=True), ('unit_cost__isnull', True)), _connector='OR'), name='inventory_adjustment_line_cost_iff_gain'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', Decimal('0')), _connector='OR'), name='inventory_adjustment_line_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('zero_cost_confirmed', False), ('unit_cost', Decimal('0')), _connector='OR'), name='inventory_adjustment_line_zero_cost_flag_matches'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'VALUE_ONLY'), ('value_adjustment__isnull', False), models.Q(('value_adjustment', Decimal('0')), _negated=True)), models.Q(models.Q(('kind', 'VALUE_ONLY'), _negated=True), ('value_adjustment__isnull', True)), _connector='OR'), name='inventory_adjustment_line_value_iff_value_only'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('measured_base_quantity__isnull', True), ('package_conversion__isnull', False), _connector='OR'), name='inventory_adjustment_line_measured_needs_package'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('entered_package_quantity__isnull', True), ('entered_package_quantity__gt', Decimal('0')), _connector='OR'), name='inventory_adjustment_line_package_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['organization', 'status'], name='stock_count_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['warehouse', 'business_date'], name='stock_count_wh_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['IN_PROGRESS', 'SUBMITTED'])), fields=('warehouse',), name='stock_count_one_active_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(condition=models.Q(('count_number', ''), _negated=True), fields=('organization', 'count_number'), name='stock_count_number_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DRAFT'), ('count_number', '')), models.Q(models.Q(('status', 'DRAFT'), _negated=True), models.Q(('count_number', ''), _negated=True)), _connector='OR'), name='stock_count_numbered_iff_started'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), models.Q(('cutoff_at__isnull', False), ('business_date__isnull', False), models.Q(('business_date_timezone', ''), _negated=True), ('business_day_start__isnull', False), ('conducted_by__isnull', False), ('started_at__isnull', False)), _connector='OR'), name='stock_count_cutoff_snapshot_present'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['SUBMITTED', 'POSTED', 'REVERSED']), _negated=True), models.Q(('submitted_by__isnull', False), ('submitted_at__isnull', False)), _connector='OR'), name='stock_count_submitted_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['POSTED', 'REVERSED']), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='stock_count_approved_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), ('conducted_by__isnull', True), models.Q(('approved_by', models.F('conducted_by')), _negated=True), _connector='OR'), name='stock_count_approver_is_not_the_conductor'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_by__isnull', False), ('cancelled_at__isnull', False), models.Q(('cancellation_reason', ''), _negated=True)), _connector='OR'), name='stock_count_cancelled_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REVERSED'), _negated=True), models.Q(('reversed_by__isnull', False), ('reversed_at__isnull', False), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='stock_count_reversed_fields_present'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['POSTED', 'REVERSED']), models.Q(('stock_entry__isnull', True), ('journal_entry__isnull', True)), _connector='OR'), name='stock_count_entries_only_when_posted'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'REVERSED'), models.Q(('reversal_stock_entry__isnull', True), ('reversal_journal_entry__isnull', True)), _connector='OR'), name='stock_count_reversal_entries_only_when_reversed'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['FULL_WAREHOUSE'])), name='stock_count_scope_is_known'),
        ),
        migrations.AddIndex(
            model_name='stockcountline',
            index=models.Index(fields=['count', 'is_unexpected'], name='count_line_unexpected_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('count', 'sequence'), name='stock_count_line_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.UniqueConstraint(fields=('count', 'item', 'lot'), name='stock_count_line_key_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__isnull', True), ('counted_quantity__gte', Decimal('0')), _connector='OR'), name='stock_count_line_counted_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('book_quantity__gte', Decimal('0'))), name='stock_count_line_book_quantity_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('book_value__gte', Decimal('0'))), name='stock_count_line_book_value_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('is_unexpected', False), models.Q(('book_quantity', Decimal('0')), ('book_value', Decimal('0')), ('book_average', Decimal('0'))), _connector='OR'), name='stock_count_line_unexpected_has_no_book'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('approved_unit_cost__isnull', True), ('approved_unit_cost__gte', Decimal('0')), _connector='OR'), name='stock_count_line_approved_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('zero_cost_confirmed', False), ('approved_unit_cost', Decimal('0')), _connector='OR'), name='stock_count_line_zero_cost_flag_matches'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(('measured_base_quantity__isnull', True), ('package_conversion__isnull', False), _connector='OR'), name='stock_count_line_measured_needs_package'),
        ),
    ]
