"""
The import boundary, added by Task 1.7.

Two tables and no new ledger surface. `ImportBatch` holds one uploaded file's
parsed rows, its verdict, and what applying it changed; `ImportRowResult` holds
one row each, valid ones included, because "what did this import actually
change" is the question an auditor asks and a table of only errors cannot
answer it.

Nothing here can reach a posted movement. `ImportKind` has no value for a
receipt, issue, transfer, count, waste or adjustment, and the one value that
touches the ledger at all — `OPENING_STOCK_DRAFT` — produces a draft somebody
posts through the normal service.

The constraints are the interesting part:

- `inventory_import_branch_matches_kind` — a branch-scoped kind names a branch
  and an organization-scoped one must not.
- `inventory_import_rows_add_up` — valid + errors = rows, so a batch cannot
  report a total that disagrees with its own rows.
- `inventory_import_failed_applied_nothing` — a failed batch applied nothing,
  which is the atomicity promise stated where the database can hold it.
- `inventory_import_one_applied_batch_per_content` — a partial unique index on
  APPLIED batches: re-uploading a file is fine, re-applying the same content is
  a retry rather than a second import.
"""

# Generated by Django 5.2.17 on 2026-08-10 15:56

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_task_1_6_guards"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="public id"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=32, verbose_name="batch number"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ITEM_CATEGORY", "مجموعات الأصناف"),
                            ("PACKAGE_UNIT", "وحدات التعبئة"),
                            ("INVENTORY_ITEM", "الأصناف"),
                            ("ITEM_CONVERSION", "تحويلات وحدات الصنف"),
                            ("BRANCH_ITEM_SETTING", "إعدادات الصنف في الفرع"),
                            ("WAREHOUSE", "المخازن"),
                            ("OPENING_STOCK_DRAFT", "مسودة رصيد افتتاحي"),
                        ],
                        max_length=32,
                        verbose_name="kind",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "مرفوع"),
                            ("VALIDATED", "مدقّق"),
                            ("FAILED_VALIDATION", "فشل التدقيق"),
                            ("APPLIED", "مطبّق"),
                            ("CANCELLED", "ملغى"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "content_hash",
                    models.CharField(db_index=True, max_length=64, verbose_name="content hash"),
                ),
                ("byte_size", models.PositiveIntegerField(verbose_name="byte size")),
                ("row_count", models.PositiveIntegerField(default=0, verbose_name="rows")),
                (
                    "valid_row_count",
                    models.PositiveIntegerField(default=0, verbose_name="valid rows"),
                ),
                (
                    "error_row_count",
                    models.PositiveIntegerField(default=0, verbose_name="rows in error"),
                ),
                (
                    "applied_row_count",
                    models.PositiveIntegerField(default=0, verbose_name="rows applied"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="validated at"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="applied at"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cancelled at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="applied by",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_import_batches",
                        to="organizations.branch",
                        verbose_name="branch",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cancelled by",
                    ),
                ),
                (
                    "opening_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="inventory.openingstockdocument",
                        verbose_name="opening document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_import_batches",
                        to="organizations.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "import batch",
                "verbose_name_plural": "import batches",
                "ordering": ("-created_at", "-id"),
                "permissions": [
                    ("import_master_data", "Can import inventory master data"),
                    ("import_opening_draft", "Can import an opening stock draft"),
                    ("view_import_history", "Can view inventory import history"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRowResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("row_number", models.PositiveIntegerField(verbose_name="row number")),
                (
                    "external_key",
                    models.CharField(blank=True, max_length=200, verbose_name="external key"),
                ),
                ("is_valid", models.BooleanField(default=False, verbose_name="valid")),
                ("errors", models.JSONField(blank=True, default=dict, verbose_name="errors")),
                ("payload", models.JSONField(default=dict, verbose_name="payload")),
                (
                    "applied_action",
                    models.CharField(blank=True, max_length=16, verbose_name="applied action"),
                ),
                (
                    "applied_object_id",
                    models.CharField(blank=True, max_length=64, verbose_name="applied object id"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="inventory.importbatch",
                        verbose_name="batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "import row",
                "verbose_name_plural": "import rows",
                "ordering": ("batch", "row_number"),
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["organization", "kind", "status"], name="inventory_i_organiz_c5fc6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["organization", "-created_at"], name="inventory_i_organiz_e00aee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind__in", ["BRANCH_ITEM_SETTING", "OPENING_STOCK_DRAFT", "WAREHOUSE"]),
                        ("branch__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            (
                                "kind__in",
                                ["BRANCH_ITEM_SETTING", "OPENING_STOCK_DRAFT", "WAREHOUSE"],
                            ),
                            _negated=True,
                        ),
                        ("branch__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="inventory_import_branch_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "APPLIED"), _negated=True),
                    models.Q(("applied_by__isnull", False), ("applied_at__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_import_applied_records_who_and_when",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "CANCELLED"), _negated=True),
                    models.Q(
                        ("cancelled_at__isnull", False), models.Q(("reason", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="inventory_import_cancelled_states_a_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "FAILED_VALIDATION"), _negated=True),
                    ("applied_row_count", 0),
                    _connector="OR",
                ),
                name="inventory_import_failed_applied_nothing",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("applied_row_count__lte", models.F("valid_row_count"))),
                name="inventory_import_applied_within_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "row_count",
                        django.db.models.expressions.CombinedExpression(
                            models.F("valid_row_count"), "+", models.F("error_row_count")
                        ),
                    )
                ),
                name="inventory_import_rows_add_up",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "APPLIED")),
                fields=("organization", "kind", "content_hash"),
                name="inventory_import_one_applied_batch_per_content",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrowresult",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="inventory_import_row_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrowresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_valid", True), ("errors", {})),
                    ("is_valid", False),
                    _connector="OR",
                ),
                name="inventory_import_valid_row_has_no_errors",
            ),
        ),
    ]
