"""
`ImportKind` narrowed to what is actually implemented, and enforced.

Migration 0016 declared seven kinds; three had a validator and an apply writer.
The other four — inventory items, item conversions, warehouses and
opening-stock drafts — were placeholders, and a placeholder in a production
enum is a dropdown entry that accepts somebody's file and then fails.

This removes them and adds `inventory_import_kind_is_supported`, a
CheckConstraint over the surviving three. Django choices are a form-layer
courtesy: a raw INSERT, a data migration or a `bulk_create` walks straight past
them, and a batch whose kind has no validator could never be previewed or
applied — it would sit in the import history looking like work somebody did.

A follow-up rather than an edit to 0016, because 0016 is already applied to the
development database and to `khan_mandi_t17a_check`. Rewriting an applied
migration in place leaves those databases claiming a state they do not have.

`inventory_import_branch_matches_kind` is dropped and recreated because it
names the branch-scoped kinds, and that set shrank with the enum.

Opening-stock import stays deferred deliberately. It is the only kind that
would reach the ledger — even as a draft it sets the ledger's starting position
— so it earns its own review. `inventory.import_opening_draft` remains a
reserved permission granted to no role while that is true.
"""

# Generated by Django 5.2.17 on 2026-08-10 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_task_1_7_imports"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="importbatch",
            name="inventory_import_branch_matches_kind",
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ITEM_CATEGORY", "مجموعات الأصناف"),
                    ("PACKAGE_UNIT", "وحدات التعبئة"),
                    ("BRANCH_ITEM_SETTING", "إعدادات الصنف في الفرع"),
                ],
                max_length=32,
                verbose_name="kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind__in", ["BRANCH_ITEM_SETTING"]), ("branch__isnull", False)),
                    models.Q(
                        models.Q(("kind__in", ["BRANCH_ITEM_SETTING"]), _negated=True),
                        ("branch__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="inventory_import_branch_matches_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["BRANCH_ITEM_SETTING", "ITEM_CATEGORY", "PACKAGE_UNIT"])
                ),
                name="inventory_import_kind_is_supported",
            ),
        ),
    ]
