"""
Stock locations, added by Task 1.7B.

Three tables, and none of them carries money. `StockLocationBalance` has a
quantity and no value, no average cost and no control account, because ADR-018
§2 gives value to the warehouse and "where" to the location — moving a box
between two bins must revalue nothing. Widening the valuation key instead would
have revalued stock on every put-away, which is the outcome that decision
exists to prevent.

`stock_location_balance_key_unique` is NULL-safe: a lotless position is one
position, not one row per null.

`stock_location_movement_sign_matches_type` makes the sign a property of the
event rather than the caller's opinion. Without it a picking event that
increased a bin would read as a put-away in every report.

The unlocated remainder is deliberately not a column. It is
`StockBalance.quantity − sum(located)`, derived, because a second stored number
is a second thing that can drift from the warehouse total.
"""

# Generated by Django 5.2.17 on 2026-08-10 23:57

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_task_1_7a_supported_import_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStockLocation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("code", models.CharField(max_length=32, verbose_name="code")),
                ("name_ar", models.CharField(max_length=200, verbose_name="name (Arabic)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=200, verbose_name="name (English)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical stock location",
                "verbose_name_plural": "historical stock locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("code", models.CharField(max_length=32, verbose_name="code")),
                ("name_ar", models.CharField(max_length=200, verbose_name="name (Arabic)")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=200, verbose_name="name (English)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock location",
                "verbose_name_plural": "stock locations",
                "ordering": ["warehouse__code", "code"],
                "permissions": [
                    ("manage_locations", "Can create and archive stock locations"),
                    ("move_location_stock", "Can move stock between locations"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLocationBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_balances",
                        to="inventory.inventoryitem",
                        verbose_name="item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="inventory.stocklocation",
                        verbose_name="location",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_balances",
                        to="inventory.inventorylot",
                        verbose_name="lot",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_balances",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock location balance",
                "verbose_name_plural": "stock location balances",
                "ordering": ["warehouse__code", "location__code", "item__code"],
            },
        ),
        migrations.CreateModel(
            name="StockLocationMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PUT_AWAY", "إدخال إلى موقع"),
                            ("PICK", "سحب من موقع"),
                            ("TRANSFER_IN", "نقل داخلي وارد"),
                            ("TRANSFER_OUT", "نقل داخلي صادر"),
                        ],
                        max_length=20,
                        verbose_name="movement type",
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="base quantity"
                    ),
                ),
                (
                    "quantity_after",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="quantity after"
                    ),
                ),
                ("effective_at", models.DateTimeField(verbose_name="effective at")),
                ("posted_at", models.DateTimeField(auto_now_add=True, verbose_name="posted at")),
                (
                    "reference",
                    models.CharField(blank=True, max_length=200, verbose_name="reference"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_movements",
                        to="inventory.inventoryitem",
                        verbose_name="item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stocklocation",
                        verbose_name="location",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_movements",
                        to="inventory.inventorylot",
                        verbose_name="lot",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="posted by",
                    ),
                ),
                (
                    "stock_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_movements",
                        to="inventory.stockmovement",
                        verbose_name="stock movement",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_movements",
                        to="inventory.warehouse",
                        verbose_name="warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock location movement",
                "verbose_name_plural": "stock location movements",
                "ordering": ["-posted_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "code"), name="stock_location_code_unique_per_warehouse"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[A-Z0-9][A-Z0-9._-]*$")),
                name="stock_location_code_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_ar", ""), _negated=True),
                name="stock_location_name_ar_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocationbalance",
            index=models.Index(
                fields=["warehouse", "item", "lot"], name="inventory_s_warehou_2465c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocationbalance",
            constraint=models.UniqueConstraint(
                fields=("location", "item", "lot"),
                name="stock_location_balance_key_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocationbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", Decimal("0"))),
                name="stock_location_balance_quantity_not_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocationmovement",
            index=models.Index(
                fields=["location", "item", "lot"], name="inventory_s_locatio_22de7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocationmovement",
            index=models.Index(
                fields=["warehouse", "-posted_at"], name="inventory_s_warehou_5ce3fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocationmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_quantity", Decimal("0")), _negated=True),
                name="stock_location_movement_quantity_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocationmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_after__gte", Decimal("0"))),
                name="stock_location_movement_after_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocationmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("movement_type__in", ["PUT_AWAY", "TRANSFER_IN"]),
                        ("base_quantity__gt", Decimal("0")),
                    ),
                    models.Q(
                        ("movement_type__in", ["PICK", "TRANSFER_OUT"]),
                        ("base_quantity__lt", Decimal("0")),
                    ),
                    _connector="OR",
                ),
                name="stock_location_movement_sign_matches_type",
            ),
        ),
    ]
