# Generated by Django 5.2.17 on 2026-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_task_1_7b_stock_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'رصيد افتتاحي'), ('RECEIPT', 'إدخال'), ('ISSUE', 'صرف'), ('RETURN_IN', 'إرجاع من صرف'), ('RETURN_OUT', 'إرجاع إلى المورد'), ('TRANSFER_OUT', 'تحويل صادر'), ('TRANSFER_IN', 'تحويل وارد'), ('TRANSFER_SHORTAGE', 'عجز تحويل'), ('WASTE', 'هالك'), ('COUNT_GAIN', 'فائض جرد'), ('COUNT_LOSS', 'عجز جرد'), ('PRODUCTION_IN', 'إنتاج وارد'), ('PRODUCTION_OUT', 'صرف للإنتاج'), ('MANUAL_ADJUSTMENT', 'تسوية يدوية'), ('REVERSAL', 'عكس قيد')], max_length=20, verbose_name='movement type'),
        ),
    ]
