# Generated by Django 5.2.17 on 2026-08-15 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_return_out_movement_type'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='inventory_import_branch_matches_kind',
        ),
        migrations.RemoveConstraint(
            model_name='importbatch',
            name='inventory_import_kind_is_supported',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('ITEM_CATEGORY', 'مجموعات الأصناف'), ('PACKAGE_UNIT', 'وحدات التعبئة'), ('BRANCH_ITEM_SETTING', 'إعدادات الصنف في الفرع'), ('SUPPLIER', 'الموردون'), ('SUPPLIER_ITEM', 'كتالوج الموردين'), ('PURCHASE_REQUEST_DRAFT', 'مسودات طلبات الشراء')], max_length=32, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['BRANCH_ITEM_SETTING', 'PURCHASE_REQUEST_DRAFT']), ('branch__isnull', False)), models.Q(models.Q(('kind__in', ['BRANCH_ITEM_SETTING', 'PURCHASE_REQUEST_DRAFT']), _negated=True), ('branch__isnull', True)), _connector='OR'), name='inventory_import_branch_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['BRANCH_ITEM_SETTING', 'ITEM_CATEGORY', 'PACKAGE_UNIT', 'PURCHASE_REQUEST_DRAFT', 'SUPPLIER', 'SUPPLIER_ITEM'])), name='inventory_import_kind_is_supported'),
        ),
    ]
