# Generated by Django 5.2.17 on 2026-08-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_procurement_import_kinds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['organization__code', 'code'], 'permissions': [('view_item', 'Can view the item master'), ('manage_items', 'Can create and archive inventory items'), ('create_item', 'Can register a new inventory item'), ('edit_item', 'Can change an existing inventory item'), ('manage_conversions', 'Can manage item package conversions'), ('view_stock', 'Can view stock on hand'), ('view_valuation', 'Can view inventory cost and valuation'), ('create_draft_movement', 'Can create a draft stock movement'), ('create_opening_stock', 'Can prepare and submit an opening stock document'), ('post_opening_stock', 'Can post opening stock'), ('post_receipt', 'Can post a stock receipt'), ('post_issue', 'Can post a stock issue'), ('post_return_in', 'Can return previously issued stock to inventory'), ('post_transfer', 'Can post a stock transfer'), ('close_transfer_shortage', "Can close a transfer's missing quantity as a loss"), ('post_waste', 'Can post stock waste'), ('conduct_stock_count', 'Can conduct a stock count'), ('approve_stock_count', 'Can approve a stock count'), ('post_adjustment', 'Can post a stock adjustment'), ('reverse_movement', 'Can reverse a stock movement'), ('override_negative_stock', 'Can post stock below zero')], 'verbose_name': 'inventory item', 'verbose_name_plural': 'inventory items'},
        ),
    ]
