"""
Withdraw the un-invoiced receipt, the return-from-issue, and the movement
reason vocabulary's management surface.

The two document types leave `InventoryDocumentType`, so the operational CHECK
constraint narrows to the issue and the waste note. Any **draft** of a
withdrawn type is deleted first, because the constraint could not be created
over it; a *posted* one would be history and is refused instead — this
migration will not silently destroy a posted document.

`InventoryReasonCode` itself stays. Three tables reference it, one of them in
Procurement, and the rows already posted against a code have to keep saying
what they said. What goes is the ability to reach it: its screens, its API,
its permission, and the trigger that made a reason code *mandatory* on a waste
line — mandatory against a vocabulary nobody can add to would have stopped
waste being recorded at all.
"""

# Generated by Django 5.2.17 on 2026-08-27 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_withdrawn_drafts(apps, schema_editor):
    """
    Delete the drafts of the two withdrawn types, and refuse posted ones.

    A draft has no movement, no journal and no document number: deleting it is
    what `delete_document` does on the screen every day. A posted document is
    history, and this migration would rather fail than take it.
    """
    Document = apps.get_model("inventory", "InventoryMovementDocument")
    withdrawn = ["INVENTORY_RECEIPT", "INVENTORY_RETURN_IN"]

    posted = Document.objects.filter(document_type__in=withdrawn).exclude(status="DRAFT")
    if posted.exists():
        numbers = ", ".join(
            posted.values_list("document_number", flat=True).order_by("document_number")[:20]
        )
        raise RuntimeError(
            "This database holds posted documents of a withdrawn type "
            f"({numbers}). Reverse them before withdrawing the type; this "
            "migration will not delete posted history."
        )

    drafts = Document.objects.filter(document_type__in=withdrawn, status="DRAFT")
    Document.objects.filter(pk__in=drafts.values("pk")).delete()

    Sequence = apps.get_model("inventory", "InventoryDocumentSequence")
    Sequence.objects.filter(document_type__in=withdrawn).delete()


def drop_withdrawn_permissions(apps, schema_editor):
    """
    Remove the three permissions from the auth table.

    Django adds permissions from `Meta.permissions` and never removes them, so
    without this they would keep appearing in the role editor and in the admin
    long after the screens they guarded had gone — grants nobody can exercise
    and nobody can audit. Deleting the row cascades to every group and user
    that held it.
    """
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="inventory",
        codename__in=["post_return_in", "manage_reason_codes", "view_import_history"],
    ).delete()


#: A waste line may still *carry* a reason code — the rows already posted do,
#: and their integrity rules still hold — but it is no longer required to,
#: because the vocabulary can no longer be added to.
REASON_TRIGGER_WITHOUT_THE_REQUIREMENT = """
CREATE OR REPLACE FUNCTION inventory_document_line_reason_matches_type()
RETURNS TRIGGER AS $$
DECLARE
    doc_type text;
    doc_org integer;
    reason_application text;
    reason_org integer;
BEGIN
    SELECT document_type, organization_id INTO doc_type, doc_org
    FROM inventory_inventorymovementdocument
    WHERE id = NEW.document_id;

    IF doc_type = 'INVENTORY_WASTE' THEN
        IF NEW.reason_code_id IS NOT NULL THEN
            SELECT applies_to, organization_id
            INTO reason_application, reason_org
            FROM inventory_inventoryreasoncode
            WHERE id = NEW.reason_code_id;

            IF reason_org IS DISTINCT FROM doc_org THEN
                RAISE EXCEPTION 'reason code belongs to another organization'
                    USING ERRCODE = 'check_violation';
            END IF;
            IF reason_application <> 'WASTE' THEN
                RAISE EXCEPTION 'reason code applies to %, not to waste', reason_application
                    USING ERRCODE = 'check_violation';
            END IF;
        END IF;
    ELSIF NEW.reason_code_id IS NOT NULL THEN
        RAISE EXCEPTION 'a % line takes no reason code', doc_type
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

#: Exactly the function migration 0015 installed, for `migrate` backwards.
REASON_TRIGGER_WITH_THE_REQUIREMENT = """
CREATE OR REPLACE FUNCTION inventory_document_line_reason_matches_type()
RETURNS TRIGGER AS $$
DECLARE
    doc_type text;
    doc_org integer;
    reason_application text;
    reason_org integer;
    reason_active boolean;
BEGIN
    SELECT document_type, organization_id INTO doc_type, doc_org
    FROM inventory_inventorymovementdocument
    WHERE id = NEW.document_id;

    IF doc_type = 'INVENTORY_WASTE' THEN
        IF NEW.reason_code_id IS NULL THEN
            RAISE EXCEPTION 'a waste line needs a reason code'
                USING ERRCODE = 'check_violation';
        END IF;
        SELECT applies_to, organization_id, is_active
        INTO reason_application, reason_org, reason_active
        FROM inventory_inventoryreasoncode
        WHERE id = NEW.reason_code_id;

        IF reason_org IS DISTINCT FROM doc_org THEN
            RAISE EXCEPTION 'reason code belongs to another organization'
                USING ERRCODE = 'check_violation';
        END IF;
        IF reason_application <> 'WASTE' THEN
            RAISE EXCEPTION 'reason code applies to %, not to waste', reason_application
                USING ERRCODE = 'check_violation';
        END IF;
    ELSIF NEW.reason_code_id IS NOT NULL THEN
        RAISE EXCEPTION 'a % line takes no reason code', doc_type
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_split_manage_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_withdrawn_drafts, migrations.RunPython.noop, elidable=False),
        migrations.RunPython(drop_withdrawn_permissions, migrations.RunPython.noop, elidable=False),
        migrations.RunSQL(
            REASON_TRIGGER_WITHOUT_THE_REQUIREMENT,
            reverse_sql=REASON_TRIGGER_WITH_THE_REQUIREMENT,
        ),
    ]
