# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventoryitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalinventoryreasoncode',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalitemcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalpackageunit',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalstocklocation',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalwarehouse',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='inventoryreasoncode',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='packageunit',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='stocklocation',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='name_en',
        ),
    ]
