# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_historicalinventoryitem_name_and_more'),
        ('organizations', '0011_alter_roledefinition_options'),
        ('units', '0005_alter_historicalunitofmeasure_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryitem',
            name='inventory_item_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryreasoncode',
            name='inventory_reason_code_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='itemcategory',
            name='item_category_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='packageunit',
            name='package_unit_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='stocklocation',
            name='stock_location_name_ar_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='warehouse_name_ar_not_empty',
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='inventory_item_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreasoncode',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='inventory_reason_code_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='item_category_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='packageunit',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='package_unit_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='stock_location_name_ar_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='warehouse_name_ar_not_empty'),
        ),
    ]
