# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_remove_inventoryitem_inventory_item_name_ar_not_empty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openingstockdocument",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="opening_stock_documents",
                to="inventory.warehouse",
                verbose_name="warehouse",
            ),
        ),
    ]
