# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_opening_stock_document_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingstockdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("SUBMITTED", "بانتظار الترحيل المحاسبي"),
                    ("POSTED", "مرحّل"),
                    ("REVERSED", "معكوس"),
                ],
                default="DRAFT",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
