# Generated by Django 5.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0031_alter_openingstockdocument_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingstockdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "مسودة"),
                    ("SUBMITTED", "محال سابقاً للترحيل المحاسبي"),
                    ("POSTED", "مرحّل"),
                    ("REVERSED", "معكوس"),
                ],
                default="DRAFT",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="openingstockdocument",
            name="opening_submitted_fields_present",
        ),
        migrations.AddConstraint(
            model_name="openingstockdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(status__in=["DRAFT", "POSTED", "REVERSED"])
                | (
                    models.Q(status="SUBMITTED")
                    & models.Q(submitted_by__isnull=False)
                    & models.Q(submitted_at__isnull=False)
                ),
                name="opening_submitted_fields_present",
            ),
        ),
    ]
