# Generated by Django 5.2.17 on 2026-08-19 19:52

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


NO_APPROVED_OVERLAP = """
ALTER TABLE hr_employeecontract
ADD CONSTRAINT hr_employee_contract_no_approved_overlap
EXCLUDE USING gist (
    employee_id WITH =,
    daterange(start_date, end_date, '[]') WITH &&
)
WHERE (status = 'APPROVED');
"""

DROP_NO_APPROVED_OVERLAP = """
ALTER TABLE hr_employeecontract
DROP CONSTRAINT IF EXISTS hr_employee_contract_no_approved_overlap;
"""

SCOPE_AND_IMMUTABILITY_GUARDS = """
CREATE OR REPLACE FUNCTION hr_employee_scope_and_delete_guard()
RETURNS TRIGGER AS $$
DECLARE branch_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'employee % cannot be deleted; archive it', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT organization_id INTO branch_organization
      FROM organizations_branch WHERE id = NEW.branch_id;
    IF branch_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'employee % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_employee_scope_and_delete
BEFORE INSERT OR UPDATE OR DELETE ON hr_employee
FOR EACH ROW EXECUTE FUNCTION hr_employee_scope_and_delete_guard();

CREATE OR REPLACE FUNCTION hr_contract_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE
    employee_organization bigint;
    branch_organization bigint;
    policy_organization bigint;
    transition_columns text[] := ARRAY['status', 'end_date', 'updated_at'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'approved employee contract % cannot be deleted', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO employee_organization
      FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id INTO branch_organization
      FROM organizations_branch WHERE id = NEW.branch_id;
    SELECT organization_id INTO policy_organization
      FROM hr_payrollpolicy WHERE id = NEW.payroll_policy_id;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR branch_organization IS DISTINCT FROM NEW.organization_id
       OR policy_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'employee contract % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status <> 'DRAFT' THEN
        IF OLD.status = 'APPROVED'
           AND NEW.status = 'CANCELLED'
           AND (to_jsonb(NEW) - ARRAY['status', 'updated_at'])
               = (to_jsonb(OLD) - ARRAY['status', 'updated_at']) THEN
            RETURN NEW;
        END IF;
        IF OLD.status = 'APPROVED'
           AND NEW.status IN ('SUPERSEDED', 'CLOSED')
           AND NEW.end_date IS NOT NULL
           AND (to_jsonb(NEW) - transition_columns)
               = (to_jsonb(OLD) - transition_columns) THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'approved employee contract % is immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_contract_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_employeecontract
FOR EACH ROW EXECUTE FUNCTION hr_contract_scope_and_freeze_guard();
"""

DROP_SCOPE_AND_IMMUTABILITY_GUARDS = """
DROP TRIGGER IF EXISTS hr_contract_scope_and_freeze ON hr_employeecontract;
DROP FUNCTION IF EXISTS hr_contract_scope_and_freeze_guard();
DROP TRIGGER IF EXISTS hr_employee_scope_and_delete ON hr_employee;
DROP FUNCTION IF EXISTS hr_employee_scope_and_delete_guard();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('identity_number', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('marital_status', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('workplace', models.CharField(blank=True, max_length=160)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('ON_LEAVE', 'في إجازة'), ('SUSPENDED', 'موقوف'), ('TERMINATED', 'منتهية خدمته'), ('ARCHIVED', 'مؤرشف')], default='ACTIVE', max_length=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], default='CASH', max_length=12)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__code', 'code'],
                'permissions': [('view_employee_workspace', 'Can view employee workspace'), ('manage_employee', 'Can manage employees'), ('terminate_employee', 'Can terminate employees'), ('view_employee_personal', 'Can view personal employee information'), ('view_employee_salary', 'Can view employee salary information')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, upload_to='hr/employee-documents/%Y/%m/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employee_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('identity_number', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('marital_status', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('workplace', models.CharField(blank=True, max_length=160)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('ON_LEAVE', 'في إجازة'), ('SUSPENDED', 'موقوف'), ('TERMINATED', 'منتهية خدمته'), ('ARCHIVED', 'مؤرشف')], default='ACTIVE', max_length=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], default='CASH', max_length=12)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('document_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('file', models.TextField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee document',
                'verbose_name_plural': 'historical employee documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayrollPolicy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proration_basis', models.CharField(choices=[('CALENDAR_DAY', 'أيام التقويم'), ('SCHEDULED_WORKDAY', 'أيام العمل المجدولة'), ('HOURLY', 'بالساعة')], max_length=24)),
                ('money_rounding', models.DecimalField(decimal_places=3, default=Decimal('0.001'), max_digits=8)),
                ('hour_rounding', models.DecimalField(decimal_places=3, default=Decimal('0.001'), max_digits=8)),
                ('salary_cutoff_day', models.PositiveSmallIntegerField(default=25)),
                ('release_day', models.PositiveSmallIntegerField(default=1)),
                ('overtime_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8)),
                ('max_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('unpaid_leave_affects_payroll', models.BooleanField(default=True)),
                ('deduction_cap_percentage', models.DecimalField(decimal_places=3, default=Decimal('100.000'), max_digits=6)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical payroll policy',
                'verbose_name_plural': 'historical payroll policys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('proration_basis', models.CharField(choices=[('CALENDAR_DAY', 'أيام التقويم'), ('SCHEDULED_WORKDAY', 'أيام العمل المجدولة'), ('HOURLY', 'بالساعة')], max_length=24)),
                ('money_rounding', models.DecimalField(decimal_places=3, default=Decimal('0.001'), max_digits=8)),
                ('hour_rounding', models.DecimalField(decimal_places=3, default=Decimal('0.001'), max_digits=8)),
                ('salary_cutoff_day', models.PositiveSmallIntegerField(default=25)),
                ('release_day', models.PositiveSmallIntegerField(default=1)),
                ('overtime_multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8)),
                ('max_overtime_minutes', models.PositiveIntegerField(default=0)),
                ('unpaid_leave_affects_payroll', models.BooleanField(default=True)),
                ('deduction_cap_percentage', models.DecimalField(decimal_places=3, default=Decimal('100.000'), max_digits=6)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payroll_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_policies', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__code', 'code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeContract',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'دائم'), ('FIXED_TERM', 'محدد المدة'), ('TEMPORARY', 'مؤقت')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد'), ('SUPERSEDED', 'مستبدل'), ('CLOSED', 'مغلق'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=16)),
                ('job_title', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('wage_basis', models.CharField(choices=[('MONTHLY', 'شهري'), ('DAILY', 'يومي'), ('HOURLY', 'بالساعة')], max_length=12)),
                ('basic_salary', models.DecimalField(decimal_places=3, max_digits=18)),
                ('scheduled_work_days', models.DecimalField(decimal_places=3, max_digits=6)),
                ('scheduled_hours', models.DecimalField(decimal_places=3, max_digits=8)),
                ('probation_days', models.PositiveIntegerField(default=0)),
                ('default_shift_code', models.CharField(blank=True, max_length=40)),
                ('fixed_allowances', models.JSONField(blank=True, default=list)),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('payroll_policy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.payrollpolicy')),
            ],
            options={
                'verbose_name': 'historical employee contract',
                'verbose_name_plural': 'historical employee contracts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'دائم'), ('FIXED_TERM', 'محدد المدة'), ('TEMPORARY', 'مؤقت')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد'), ('SUPERSEDED', 'مستبدل'), ('CLOSED', 'مغلق'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=16)),
                ('job_title', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('wage_basis', models.CharField(choices=[('MONTHLY', 'شهري'), ('DAILY', 'يومي'), ('HOURLY', 'بالساعة')], max_length=12)),
                ('basic_salary', models.DecimalField(decimal_places=3, max_digits=18)),
                ('scheduled_work_days', models.DecimalField(decimal_places=3, max_digits=6)),
                ('scheduled_hours', models.DecimalField(decimal_places=3, max_digits=8)),
                ('probation_days', models.PositiveIntegerField(default=0)),
                ('default_shift_code', models.CharField(blank=True, max_length=40)),
                ('fixed_allowances', models.JSONField(blank=True, default=list)),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_employee_contracts', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_employee_contracts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_contracts', to='organizations.organization')),
                ('payroll_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='hr.payrollpolicy')),
            ],
            options={
                'ordering': ['employee__code', '-version'],
                'permissions': [('view_contract_workspace', 'Can view employee contract workspace'), ('manage_contract', 'Can manage employee contracts'), ('approve_contract', 'Can approve employee contracts')],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='hr_employee_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='hr_employee_termination_after_hire'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'TERMINATED'), _negated=True), ('termination_date__isnull', False), _connector='OR'), name='hr_terminated_employee_has_date'),
        ),
        migrations.AddConstraint(
            model_name='employeedocument',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('issue_date__isnull', True), ('expiry_date__gte', models.F('issue_date')), _connector='OR'), name='hr_employee_document_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='hr_payroll_policy_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='hr_payroll_policy_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('salary_cutoff_day__gte', 1), ('salary_cutoff_day__lte', 31)), name='hr_payroll_policy_cutoff_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('release_day__gte', 1), ('release_day__lte', 31)), name='hr_payroll_policy_release_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('money_rounding__gt', 0), ('hour_rounding__gt', 0), ('overtime_multiplier__gte', 0), ('deduction_cap_percentage__gte', 0)), name='hr_payroll_policy_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeecontract',
            constraint=models.UniqueConstraint(fields=('employee', 'version'), name='hr_employee_contract_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='employeecontract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hr_employee_contract_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeecontract',
            constraint=models.CheckConstraint(condition=models.Q(('basic_salary__gt', 0), ('scheduled_work_days__gt', 0), ('scheduled_hours__gt', 0)), name='hr_employee_contract_work_values_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeecontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='hr_approved_contract_has_evidence'),
        ),
        migrations.RunSQL(sql=NO_APPROVED_OVERLAP, reverse_sql=DROP_NO_APPROVED_OVERLAP),
        migrations.RunSQL(
            sql=SCOPE_AND_IMMUTABILITY_GUARDS,
            reverse_sql=DROP_SCOPE_AND_IMMUTABILITY_GUARDS,
        ),
    ]
