# Generated by Django 5.2.17 on 2026-08-19 20:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


SHIFT_AND_ATTENDANCE_GUARDS = """
ALTER TABLE hr_shift
ADD CONSTRAINT hr_shift_no_effective_overlap
EXCLUDE USING gist (
    branch_id WITH =,
    code WITH =,
    daterange(effective_from, effective_to, '[]') WITH &&
)
WHERE (is_active);

ALTER TABLE hr_shiftassignment
ADD CONSTRAINT hr_shift_assignment_no_overlap
EXCLUDE USING gist (
    employee_id WITH =,
    daterange(effective_from, effective_to, '[]') WITH &&
);

CREATE OR REPLACE FUNCTION hr_shift_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE branch_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF EXISTS (SELECT 1 FROM hr_shiftassignment WHERE shift_id = OLD.id)
           OR EXISTS (SELECT 1 FROM hr_attendanceevent WHERE scheduled_shift_id = OLD.id) THEN
            RAISE EXCEPTION 'used shift version % cannot be deleted', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO branch_organization
      FROM organizations_branch WHERE id = NEW.branch_id;
    IF branch_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'shift % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE'
       AND (EXISTS (SELECT 1 FROM hr_shiftassignment WHERE shift_id = OLD.id)
            OR EXISTS (SELECT 1 FROM hr_attendanceevent WHERE scheduled_shift_id = OLD.id))
       AND (to_jsonb(NEW) - ARRAY['updated_at']) <> (to_jsonb(OLD) - ARRAY['updated_at']) THEN
        RAISE EXCEPTION 'used shift version % is immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_shift_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_shift
FOR EACH ROW EXECUTE FUNCTION hr_shift_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_shift_assignment_scope_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; shift_organization bigint; employee_branch bigint; shift_branch bigint;
BEGIN
    SELECT organization_id, branch_id INTO employee_organization, employee_branch
      FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id, branch_id INTO shift_organization, shift_branch
      FROM hr_shift WHERE id = NEW.shift_id;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR shift_organization IS DISTINCT FROM NEW.organization_id
       OR employee_branch IS DISTINCT FROM shift_branch THEN
        RAISE EXCEPTION 'shift assignment % crosses organization or branch scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_shift_assignment_scope
BEFORE INSERT OR UPDATE ON hr_shiftassignment
FOR EACH ROW EXECUTE FUNCTION hr_shift_assignment_scope_guard();

CREATE OR REPLACE FUNCTION hr_attendance_event_append_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; employee_branch bigint; branch_organization bigint; shift_branch bigint;
BEGIN
    IF TG_OP = 'UPDATE' OR TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'attendance event % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT organization_id, branch_id INTO employee_organization, employee_branch
      FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id INTO branch_organization
      FROM organizations_branch WHERE id = NEW.branch_id;
    IF NEW.scheduled_shift_id IS NOT NULL THEN
        SELECT branch_id INTO shift_branch FROM hr_shift WHERE id = NEW.scheduled_shift_id;
    END IF;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR branch_organization IS DISTINCT FROM NEW.organization_id
       OR employee_branch IS DISTINCT FROM NEW.branch_id
       OR (NEW.scheduled_shift_id IS NOT NULL AND shift_branch IS DISTINCT FROM NEW.branch_id) THEN
        RAISE EXCEPTION 'attendance event % crosses organization or branch scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_attendance_event_append_only
BEFORE INSERT OR UPDATE OR DELETE ON hr_attendanceevent
FOR EACH ROW EXECUTE FUNCTION hr_attendance_event_append_guard();

CREATE OR REPLACE FUNCTION hr_attendance_approval_scope_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; employee_branch bigint; branch_organization bigint;
BEGIN
    SELECT organization_id, branch_id INTO employee_organization, employee_branch
      FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id INTO branch_organization
      FROM organizations_branch WHERE id = NEW.branch_id;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR branch_organization IS DISTINCT FROM NEW.organization_id
       OR employee_branch IS DISTINCT FROM NEW.branch_id THEN
        RAISE EXCEPTION 'attendance approval % crosses organization or branch scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_attendance_approval_scope
BEFORE INSERT OR UPDATE ON hr_attendancedayapproval
FOR EACH ROW EXECUTE FUNCTION hr_attendance_approval_scope_guard();
"""

DROP_SHIFT_AND_ATTENDANCE_GUARDS = """
DROP TRIGGER IF EXISTS hr_attendance_approval_scope ON hr_attendancedayapproval;
DROP FUNCTION IF EXISTS hr_attendance_approval_scope_guard();
DROP TRIGGER IF EXISTS hr_attendance_event_append_only ON hr_attendanceevent;
DROP FUNCTION IF EXISTS hr_attendance_event_append_guard();
DROP TRIGGER IF EXISTS hr_shift_assignment_scope ON hr_shiftassignment;
DROP FUNCTION IF EXISTS hr_shift_assignment_scope_guard();
DROP TRIGGER IF EXISTS hr_shift_scope_and_freeze ON hr_shift;
DROP FUNCTION IF EXISTS hr_shift_scope_and_freeze_guard();
ALTER TABLE hr_shiftassignment DROP CONSTRAINT IF EXISTS hr_shift_assignment_no_overlap;
ALTER TABLE hr_shift DROP CONSTRAINT IF EXISTS hr_shift_no_effective_overlap;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAttendanceDayApproval',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REOPENED', 'أعيد فتحه')], default='DRAFT', max_length=12)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical attendance day approval',
                'verbose_name_plural': 'historical attendance day approvals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('scheduled_minutes', models.PositiveIntegerField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=1)),
                ('early_departure_threshold_minutes', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical shift',
                'verbose_name_plural': 'historical shifts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('scheduled_minutes', models.PositiveIntegerField()),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=1)),
                ('early_departure_threshold_minutes', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_shifts', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hr_shifts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_shifts', to='organizations.organization')),
            ],
            options={
                'ordering': ['branch__code', 'code', '-version'],
                'permissions': [('view_shift_workspace', 'Can view shift workspace'), ('manage_shift', 'Can manage shift definitions'), ('assign_shift', 'Can assign employee shifts')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalShiftAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rotation_code', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.shift')),
            ],
            options={
                'verbose_name': 'historical shift assignment',
                'verbose_name_plural': 'historical shift assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'دخول'), ('CHECK_OUT', 'خروج'), ('BREAK_OUT', 'بدء استراحة'), ('BREAK_IN', 'نهاية استراحة')], max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'إدخال يدوي'), ('DEVICE_IMPORT', 'استيراد جهاز'), ('FUTURE_FINGERPRINT_IMPORT', 'استيراد بصمة مستقبلي')], max_length=32)),
                ('device_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='organizations.organization')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='hr.attendanceevent')),
                ('scheduled_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='hr.shift')),
            ],
            options={
                'ordering': ['business_date', 'employee__code', 'occurred_at', 'id'],
                'permissions': [('view_attendance_workspace', 'Can view attendance workspace'), ('record_attendance', 'Can record attendance events'), ('correct_attendance', 'Can correct attendance events'), ('approve_attendance', 'Can approve attendance days')],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('rotation_code', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_assignments', to='organizations.organization')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shift')),
            ],
            options={
                'ordering': ['employee__code', '-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('business_date', models.DateField(db_index=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'دخول'), ('CHECK_OUT', 'خروج'), ('BREAK_OUT', 'بدء استراحة'), ('BREAK_IN', 'نهاية استراحة')], max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'إدخال يدوي'), ('DEVICE_IMPORT', 'استيراد جهاز'), ('FUTURE_FINGERPRINT_IMPORT', 'استيراد بصمة مستقبلي')], max_length=32)),
                ('device_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('supersedes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.attendanceevent')),
                ('scheduled_shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.shift')),
                ('shift_assignment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.shiftassignment')),
            ],
            options={
                'verbose_name': 'historical attendance event',
                'verbose_name_plural': 'historical attendance events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='shift_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_events', to='hr.shiftassignment'),
        ),
        migrations.CreateModel(
            name='AttendanceDayApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('REOPENED', 'أعيد فتحه')], default='DRAFT', max_length=12)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_attendance_days', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_approvals', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_approvals', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_approvals', to='organizations.organization')),
            ],
            options={
                'ordering': ['-business_date', 'employee__code'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'business_date'), name='hr_attendance_day_unique'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='hr_attendance_approval_has_evidence')],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('branch', 'code', 'version'), name='hr_shift_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='hr_shift_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_minutes__gt', 0), ('break_minutes__lt', models.F('scheduled_minutes'))), name='hr_shift_duration_valid'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='hr_shift_assignment_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendanceevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('supersedes__isnull', True), ('correction_reason', '')), models.Q(('supersedes__isnull', False), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='hr_attendance_correction_has_reason'),
        ),
        migrations.RunSQL(
            sql=SHIFT_AND_ATTENDANCE_GUARDS,
            reverse_sql=DROP_SHIFT_AND_ATTENDANCE_GUARDS,
        ),
    ]
