# Generated by Django 5.2.17 on 2026-08-19 21:04

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


HR_OPERATION_GUARDS = r"""
ALTER TABLE hr_leaverequest
ADD CONSTRAINT hr_leave_no_approved_overlap
EXCLUDE USING gist (
    employee_id WITH =,
    tstzrange(start_at, end_at, '[)') WITH &&
)
WHERE (status = 'APPROVED');

CREATE OR REPLACE FUNCTION hr_leave_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; leave_type_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'leave request % cannot be deleted after submission', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO employee_organization FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id INTO leave_type_organization FROM hr_leavetype WHERE id = NEW.leave_type_id;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR leave_type_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'leave request % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status <> 'DRAFT'
       AND (to_jsonb(NEW) - ARRAY['status', 'approved_by_id', 'approved_at', 'rejection_reason', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'approved_by_id', 'approved_at', 'rejection_reason', 'updated_at']) THEN
        RAISE EXCEPTION 'submitted leave request % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_leave_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_leaverequest
FOR EACH ROW EXECUTE FUNCTION hr_leave_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_absence_scope_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; employee_branch bigint; branch_organization bigint;
        leave_organization bigint; leave_employee bigint; leave_status text;
BEGIN
    SELECT organization_id, branch_id INTO employee_organization, employee_branch
      FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id INTO branch_organization
      FROM organizations_branch WHERE id = NEW.branch_id;
    IF NEW.leave_request_id IS NOT NULL THEN
        SELECT organization_id, employee_id, status
          INTO leave_organization, leave_employee, leave_status
          FROM hr_leaverequest WHERE id = NEW.leave_request_id;
    END IF;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR employee_branch IS DISTINCT FROM NEW.branch_id
       OR branch_organization IS DISTINCT FROM NEW.organization_id
       OR (NEW.leave_request_id IS NOT NULL AND
           (leave_organization IS DISTINCT FROM NEW.organization_id
            OR leave_employee IS DISTINCT FROM NEW.employee_id
            OR leave_status IS DISTINCT FROM 'APPROVED')) THEN
        RAISE EXCEPTION 'absence record % crosses employee, branch, or leave scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_absence_scope
BEFORE INSERT OR UPDATE ON hr_absencerecord
FOR EACH ROW EXECUTE FUNCTION hr_absence_scope_guard();

CREATE OR REPLACE FUNCTION hr_overtime_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; shift_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'overtime request % cannot be deleted after submission', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO employee_organization FROM hr_employee WHERE id = NEW.employee_id;
    SELECT organization_id INTO shift_organization FROM hr_shift WHERE id = NEW.shift_id;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR shift_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'overtime request % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status <> 'DRAFT'
       AND (to_jsonb(NEW) - ARRAY['status', 'approved_minutes', 'multiplier', 'approved_by_id', 'approved_at', 'payroll_inclusion_reference', 'included_at', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'approved_minutes', 'multiplier', 'approved_by_id', 'approved_at', 'payroll_inclusion_reference', 'included_at', 'updated_at']) THEN
        RAISE EXCEPTION 'submitted overtime request % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_overtime_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_overtimerequest
FOR EACH ROW EXECUTE FUNCTION hr_overtime_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_deduction_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint; replaced_organization bigint; replaced_employee bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'deduction % cannot be deleted after submission', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO employee_organization FROM hr_employee WHERE id = NEW.employee_id;
    IF NEW.replaces_id IS NOT NULL THEN
        SELECT organization_id, employee_id INTO replaced_organization, replaced_employee
          FROM hr_employeededuction WHERE id = NEW.replaces_id;
    END IF;
    IF employee_organization IS DISTINCT FROM NEW.organization_id
       OR (NEW.replaces_id IS NOT NULL AND
           (replaced_organization IS DISTINCT FROM NEW.organization_id
            OR replaced_employee IS DISTINCT FROM NEW.employee_id)) THEN
        RAISE EXCEPTION 'deduction % crosses employee or organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status <> 'DRAFT'
       AND (to_jsonb(NEW) - ARRAY['status', 'approved_amount', 'approved_by_id', 'approved_at', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'approved_amount', 'approved_by_id', 'approved_at', 'updated_at']) THEN
        RAISE EXCEPTION 'submitted deduction % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_deduction_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_employeededuction
FOR EACH ROW EXECUTE FUNCTION hr_deduction_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_advance_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE employee_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'advance % cannot be deleted after submission', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO employee_organization FROM hr_employee WHERE id = NEW.employee_id;
    IF employee_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'advance % crosses organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status <> 'DRAFT'
       AND (to_jsonb(NEW) - ARRAY['status', 'approved_by_id', 'approved_at', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'approved_by_id', 'approved_at', 'updated_at']) THEN
        RAISE EXCEPTION 'submitted advance % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_advance_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_employeeadvance
FOR EACH ROW EXECUTE FUNCTION hr_advance_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_deduction_allocation_append_guard()
RETURNS TRIGGER AS $$
DECLARE approved numeric; allocated numeric; parent_status text;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'deduction allocation % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT approved_amount, status INTO approved, parent_status
      FROM hr_employeededuction WHERE id = NEW.deduction_id FOR UPDATE;
    SELECT COALESCE(SUM(amount), 0) INTO allocated
      FROM hr_deductionallocation WHERE deduction_id = NEW.deduction_id;
    IF parent_status IS DISTINCT FROM 'APPROVED' OR allocated + NEW.amount > approved THEN
        RAISE EXCEPTION 'deduction allocation exceeds the approved balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_deduction_allocation_append_only
BEFORE INSERT OR UPDATE OR DELETE ON hr_deductionallocation
FOR EACH ROW EXECUTE FUNCTION hr_deduction_allocation_append_guard();

CREATE OR REPLACE FUNCTION hr_advance_disbursement_append_guard()
RETURNS TRIGGER AS $$
DECLARE principal numeric; disbursed numeric; recovered numeric; parent_status text;
        journal_organization bigint; advance_organization bigint; original_amount numeric;
        original_advance bigint; signed_amount numeric;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'advance disbursement % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT principal_amount, status, organization_id
      INTO principal, parent_status, advance_organization
      FROM hr_employeeadvance WHERE id = NEW.advance_id FOR UPDATE;
    IF parent_status NOT IN ('APPROVED', 'PARTIALLY_DISBURSED', 'DISBURSED') THEN
        RAISE EXCEPTION 'only an approved advance can be disbursed'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance disbursement journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.reversal_of_id IS NOT NULL THEN
        SELECT amount, advance_id INTO original_amount, original_advance
          FROM hr_advancedisbursement WHERE id = NEW.reversal_of_id;
        IF original_advance IS DISTINCT FROM NEW.advance_id OR original_amount IS DISTINCT FROM NEW.amount THEN
            RAISE EXCEPTION 'advance reversal must exactly reverse a disbursement from the same advance'
                USING ERRCODE = 'check_violation';
        END IF;
        signed_amount := -NEW.amount;
    ELSE
        signed_amount := NEW.amount;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO disbursed FROM hr_advancedisbursement WHERE advance_id = NEW.advance_id;
    SELECT COALESCE(SUM(amount), 0) INTO recovered
      FROM hr_advancerecoveryallocation WHERE advance_id = NEW.advance_id;
    IF disbursed + signed_amount > principal OR disbursed + signed_amount < recovered THEN
        RAISE EXCEPTION 'advance disbursement exceeds principal or falls below recovered balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_advance_disbursement_append_only
BEFORE INSERT OR UPDATE OR DELETE ON hr_advancedisbursement
FOR EACH ROW EXECUTE FUNCTION hr_advance_disbursement_append_guard();

CREATE OR REPLACE FUNCTION hr_advance_recovery_append_guard()
RETURNS TRIGGER AS $$
DECLARE disbursed numeric; recovered numeric; journal_organization bigint; advance_organization bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'advance recovery % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT organization_id INTO advance_organization
      FROM hr_employeeadvance WHERE id = NEW.advance_id FOR UPDATE;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance recovery journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO disbursed FROM hr_advancedisbursement WHERE advance_id = NEW.advance_id;
    SELECT COALESCE(SUM(amount), 0) INTO recovered
      FROM hr_advancerecoveryallocation WHERE advance_id = NEW.advance_id;
    IF recovered + NEW.amount > disbursed THEN
        RAISE EXCEPTION 'advance recovery exceeds the disbursed balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_advance_recovery_append_only
BEFORE INSERT OR UPDATE OR DELETE ON hr_advancerecoveryallocation
FOR EACH ROW EXECUTE FUNCTION hr_advance_recovery_append_guard();
"""

DROP_HR_OPERATION_GUARDS = r"""
DROP TRIGGER IF EXISTS hr_advance_recovery_append_only ON hr_advancerecoveryallocation;
DROP FUNCTION IF EXISTS hr_advance_recovery_append_guard();
DROP TRIGGER IF EXISTS hr_advance_disbursement_append_only ON hr_advancedisbursement;
DROP FUNCTION IF EXISTS hr_advance_disbursement_append_guard();
DROP TRIGGER IF EXISTS hr_deduction_allocation_append_only ON hr_deductionallocation;
DROP FUNCTION IF EXISTS hr_deduction_allocation_append_guard();
DROP TRIGGER IF EXISTS hr_advance_scope_and_freeze ON hr_employeeadvance;
DROP FUNCTION IF EXISTS hr_advance_scope_and_freeze_guard();
DROP TRIGGER IF EXISTS hr_deduction_scope_and_freeze ON hr_employeededuction;
DROP FUNCTION IF EXISTS hr_deduction_scope_and_freeze_guard();
DROP TRIGGER IF EXISTS hr_overtime_scope_and_freeze ON hr_overtimerequest;
DROP FUNCTION IF EXISTS hr_overtime_scope_and_freeze_guard();
DROP TRIGGER IF EXISTS hr_absence_scope ON hr_absencerecord;
DROP FUNCTION IF EXISTS hr_absence_scope_guard();
DROP TRIGGER IF EXISTS hr_leave_scope_and_freeze ON hr_leaverequest;
DROP FUNCTION IF EXISTS hr_leave_scope_and_freeze_guard();
ALTER TABLE hr_leaverequest DROP CONSTRAINT IF EXISTS hr_leave_no_approved_overlap;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_expenses_deferrals_and_year_end'),
        ('hr', '0002_historicalattendancedayapproval_historicalshift_and_more'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('advance_type', models.CharField(choices=[('SALARY_ADVANCE', 'سلفة راتب'), ('EMPLOYEE_LOAN', 'قرض موظف'), ('CASH_SHORTAGE', 'عجز صندوق مستحق'), ('DAMAGE', 'ضرر مثبت مستحق'), ('OTHER', 'ذمة موظف أخرى')], max_length=24)),
                ('principal_amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('PARTIALLY_DISBURSED', 'مصروف جزئياً'), ('DISBURSED', 'مصروف'), ('CLOSED', 'مسدد'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=24)),
                ('recovery_mode', models.CharField(choices=[('ONE_TIME', 'دفعة واحدة'), ('INSTALMENTS', 'أقساط')], max_length=16)),
                ('instalment_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('instalment_count', models.PositiveIntegerField(default=1)),
                ('first_recovery_period', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], max_length=12)),
                ('evidence_reference', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_advances', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_advances', to='organizations.organization')),
            ],
            options={
                'ordering': ['-request_date', 'employee__code'],
                'permissions': [('view_advance_workspace', 'Can view employee advances'), ('manage_advance', 'Can manage employee advances'), ('approve_advance', 'Can approve employee advances'), ('disburse_advance', 'Can disburse employee advances')],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRecoveryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payroll_reference', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('recovered_at', models.DateTimeField()),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_recoveries', to='accounting.journalentry')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='hr.employeeadvance')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('disbursement_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], max_length=12)),
                ('evidence_reference', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_advance_disbursements', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_disbursements', to='accounting.journalentry')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='hr.advancedisbursement')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='hr.employeeadvance')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deduction_type', models.CharField(choices=[('ABSENCE', 'غياب'), ('LATENESS', 'تأخر'), ('EARLY_DEPARTURE', 'انصراف مبكر'), ('ADMINISTRATIVE', 'استقطاع إداري'), ('DAMAGE', 'ضرر مثبت'), ('CASH_SHORTAGE', 'عجز صندوق'), ('EQUIPMENT', 'زي أو معدات'), ('OTHER', 'أخرى')], max_length=24)),
                ('original_amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('approved_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('effective_period', models.DateField()),
                ('recovery_mode', models.CharField(choices=[('ONE_TIME', 'دفعة واحدة'), ('INSTALMENTS', 'أقساط')], max_length=16)),
                ('instalment_count', models.PositiveIntegerField(default=1)),
                ('evidence_reference', models.CharField(max_length=200)),
                ('evidence_file', models.FileField(blank=True, upload_to='hr/deduction-evidence/%Y/%m/')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_deductions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deductions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_deductions', to='organizations.organization')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='hr.employeededuction')),
            ],
            options={
                'ordering': ['-effective_period', 'employee__code'],
                'permissions': [('view_deduction_workspace', 'Can view deduction workspace'), ('manage_deduction', 'Can manage employee deductions'), ('approve_deduction', 'Can approve employee deductions')],
            },
        ),
        migrations.CreateModel(
            name='DeductionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payroll_reference', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('allocated_at', models.DateTimeField()),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hr.employeededuction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeAdvance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('advance_type', models.CharField(choices=[('SALARY_ADVANCE', 'سلفة راتب'), ('EMPLOYEE_LOAN', 'قرض موظف'), ('CASH_SHORTAGE', 'عجز صندوق مستحق'), ('DAMAGE', 'ضرر مثبت مستحق'), ('OTHER', 'ذمة موظف أخرى')], max_length=24)),
                ('principal_amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('PARTIALLY_DISBURSED', 'مصروف جزئياً'), ('DISBURSED', 'مصروف'), ('CLOSED', 'مسدد'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=24)),
                ('recovery_mode', models.CharField(choices=[('ONE_TIME', 'دفعة واحدة'), ('INSTALMENTS', 'أقساط')], max_length=16)),
                ('instalment_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('instalment_count', models.PositiveIntegerField(default=1)),
                ('first_recovery_period', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'نقداً'), ('BANK', 'تحويل مصرفي')], max_length=12)),
                ('evidence_reference', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical employee advance',
                'verbose_name_plural': 'historical employee advances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeDeduction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deduction_type', models.CharField(choices=[('ABSENCE', 'غياب'), ('LATENESS', 'تأخر'), ('EARLY_DEPARTURE', 'انصراف مبكر'), ('ADMINISTRATIVE', 'استقطاع إداري'), ('DAMAGE', 'ضرر مثبت'), ('CASH_SHORTAGE', 'عجز صندوق'), ('EQUIPMENT', 'زي أو معدات'), ('OTHER', 'أخرى')], max_length=24)),
                ('original_amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('approved_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('effective_period', models.DateField()),
                ('recovery_mode', models.CharField(choices=[('ONE_TIME', 'دفعة واحدة'), ('INSTALMENTS', 'أقساط')], max_length=16)),
                ('instalment_count', models.PositiveIntegerField(default=1)),
                ('evidence_reference', models.CharField(max_length=200)),
                ('evidence_file', models.TextField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('replaces', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employeededuction')),
            ],
            options={
                'verbose_name': 'historical employee deduction',
                'verbose_name_plural': 'historical employee deductions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLeaveType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('paid_treatment', models.CharField(choices=[('PAID', 'مدفوعة'), ('UNPAID', 'غير مدفوعة'), ('POLICY', 'وفق السياسة')], max_length=12)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'historical leave type',
                'verbose_name_plural': 'historical leave types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOvertimeRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('business_date', models.DateField()),
                ('requested_minutes', models.PositiveIntegerField()),
                ('approved_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('REQUESTED', 'مطلوب مسبقاً'), ('ATTENDANCE_DERIVED', 'مشتق من الحضور'), ('MANUAL_CORRECTION', 'تصحيح يدوي')], max_length=24)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=8)),
                ('classification', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField()),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('evidence_file', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_inclusion_reference', models.CharField(blank=True, max_length=120)),
                ('included_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.shift')),
            ],
            options={
                'verbose_name': 'historical overtime request',
                'verbose_name_plural': 'historical overtime requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('requested_minutes', models.PositiveIntegerField()),
                ('paid_treatment', models.CharField(choices=[('PAID', 'مدفوعة'), ('UNPAID', 'غير مدفوعة'), ('POLICY', 'وفق السياسة')], max_length=12)),
                ('reason', models.TextField()),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('evidence_file', models.FileField(blank=True, upload_to='hr/leave-evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_leave', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_leave', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at', 'employee__code'],
                'permissions': [('view_leave_workspace', 'Can view leave workspace'), ('request_leave', 'Can create leave requests'), ('approve_leave', 'Can approve leave requests'), ('classify_absence', 'Can classify employee absences')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAbsenceRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('business_date', models.DateField()),
                ('classification', models.CharField(choices=[('ABSENT', 'غياب غير مبرر'), ('APPROVED_PAID_LEAVE', 'إجازة مدفوعة معتمدة'), ('APPROVED_UNPAID_LEAVE', 'إجازة غير مدفوعة معتمدة'), ('EXCUSED', 'غياب بعذر'), ('NOT_SCHEDULED', 'غير مجدول')], max_length=32)),
                ('reason', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('leave_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.leaverequest')),
            ],
            options={
                'verbose_name': 'historical absence record',
                'verbose_name_plural': 'historical absence records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('business_date', models.DateField()),
                ('classification', models.CharField(choices=[('ABSENT', 'غياب غير مبرر'), ('APPROVED_PAID_LEAVE', 'إجازة مدفوعة معتمدة'), ('APPROVED_UNPAID_LEAVE', 'إجازة غير مدفوعة معتمدة'), ('EXCUSED', 'غياب بعذر'), ('NOT_SCHEDULED', 'غير مجدول')], max_length=32)),
                ('reason', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_records', to='organizations.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classified_absences', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_records', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_records', to='organizations.organization')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absence_records', to='hr.leaverequest')),
            ],
            options={
                'ordering': ['-business_date', 'employee__code'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('paid_treatment', models.CharField(choices=[('PAID', 'مدفوعة'), ('UNPAID', 'غير مدفوعة'), ('POLICY', 'وفق السياسة')], max_length=12)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leave_types', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_types', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype'),
        ),
        migrations.CreateModel(
            name='HistoricalLeaveRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('requested_minutes', models.PositiveIntegerField()),
                ('paid_treatment', models.CharField(choices=[('PAID', 'مدفوعة'), ('UNPAID', 'غير مدفوعة'), ('POLICY', 'وفق السياسة')], max_length=12)),
                ('reason', models.TextField()),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('evidence_file', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.leavetype')),
            ],
            options={
                'verbose_name': 'historical leave request',
                'verbose_name_plural': 'historical leave requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_date', models.DateField()),
                ('requested_minutes', models.PositiveIntegerField()),
                ('approved_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('REQUESTED', 'مطلوب مسبقاً'), ('ATTENDANCE_DERIVED', 'مشتق من الحضور'), ('MANUAL_CORRECTION', 'تصحيح يدوي')], max_length=24)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=8)),
                ('classification', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField()),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('evidence_file', models.FileField(blank=True, upload_to='hr/overtime-evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('SUBMITTED', 'مقدم'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payroll_inclusion_reference', models.CharField(blank=True, max_length=120)),
                ('included_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_overtime', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_overtime', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='organizations.organization')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_requests', to='hr.shift')),
            ],
            options={
                'ordering': ['-business_date', 'employee__code'],
                'permissions': [('view_overtime_workspace', 'Can view overtime workspace'), ('manage_overtime', 'Can create overtime requests'), ('approve_overtime', 'Can approve overtime requests')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeadvance',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0), ('instalment_amount__gte', 0), ('instalment_amount__lte', models.F('principal_amount')), ('instalment_count__gt', 0)), name='hr_advance_values_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeeadvance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='hr_approved_advance_has_evidence'),
        ),
        migrations.AddConstraint(
            model_name='advancerecoveryallocation',
            constraint=models.UniqueConstraint(fields=('advance', 'payroll_reference'), name='hr_advance_payroll_unique'),
        ),
        migrations.AddConstraint(
            model_name='advancerecoveryallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='hr_advance_recovery_positive'),
        ),
        migrations.AddConstraint(
            model_name='advancedisbursement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='hr_advance_disbursement_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeededuction',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0), ('approved_amount__gte', 0), ('approved_amount__lte', models.F('original_amount'))), name='hr_deduction_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeededuction',
            constraint=models.CheckConstraint(condition=models.Q(('instalment_count__gt', 0)), name='hr_deduction_instalments_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeededuction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False), ('approved_amount__gt', 0)), _connector='OR'), name='hr_approved_deduction_has_evidence'),
        ),
        migrations.AddConstraint(
            model_name='deductionallocation',
            constraint=models.UniqueConstraint(fields=('deduction', 'payroll_reference'), name='hr_deduction_payroll_unique'),
        ),
        migrations.AddConstraint(
            model_name='deductionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='hr_deduction_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='absencerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'business_date'), name='hr_absence_employee_day_unique'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='hr_leave_type_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='hr_leave_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_minutes__gt', 0)), name='hr_leave_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='hr_approved_leave_has_evidence'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_minutes__gt', 0)), name='hr_overtime_minutes_positive'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(condition=models.Q(('approved_minutes__lte', models.F('requested_minutes'))), name='hr_overtime_approved_within_request'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gte', 0)), name='hr_overtime_multiplier_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False), ('approved_minutes__gt', 0)), _connector='OR'), name='hr_approved_overtime_has_evidence'),
        ),
        migrations.RunSQL(sql=HR_OPERATION_GUARDS, reverse_sql=DROP_HR_OPERATION_GUARDS),
    ]
