# Generated by Django 5.2.17 on 2026-08-19 22:00

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
import simple_history.models
from django.conf import settings
from django.db import migrations, models

PAYROLL_GUARDS = r"""
CREATE OR REPLACE FUNCTION hr_payroll_run_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE branch_organization bigint; policy_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'payroll run % cannot be deleted after calculation', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO branch_organization FROM organizations_branch WHERE id = NEW.branch_id;
    SELECT organization_id INTO policy_organization FROM hr_payrollpolicy WHERE id = NEW.policy_id;
    IF branch_organization IS DISTINCT FROM NEW.organization_id
       OR policy_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'payroll run % crosses branch, policy, or organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status IN ('REVIEWED', 'APPROVED', 'POSTED', 'RELEASED', 'PARTIALLY_PAID', 'PAID', 'REVERSED')
       AND (to_jsonb(NEW) - ARRAY['status', 'reviewed_by_id', 'reviewed_at', 'approved_by_id', 'approved_at', 'posted_by_id', 'posted_at', 'released_by_id', 'released_at', 'rejection_reason', 'accrual_journal_id', 'reversal_journal_id', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'reviewed_by_id', 'reviewed_at', 'approved_by_id', 'approved_at', 'posted_by_id', 'posted_at', 'released_by_id', 'released_at', 'rejection_reason', 'accrual_journal_id', 'reversal_journal_id', 'updated_at']) THEN
        RAISE EXCEPTION 'reviewed payroll run % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_payroll_run_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_payrollrun
FOR EACH ROW EXECUTE FUNCTION hr_payroll_run_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_payroll_employee_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE run_organization bigint; run_branch bigint; run_status text;
        employee_organization bigint; employee_branch bigint; contract_employee bigint;
BEGIN
    SELECT organization_id, branch_id, status INTO run_organization, run_branch, run_status
      FROM hr_payrollrun WHERE id = COALESCE(NEW.payroll_run_id, OLD.payroll_run_id);
    IF TG_OP = 'DELETE' THEN
        IF run_status NOT IN ('DRAFT', 'CALCULATED') THEN
            RAISE EXCEPTION 'frozen payroll employee line % is immutable', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id, branch_id INTO employee_organization, employee_branch
      FROM hr_employee WHERE id = NEW.employee_id;
    SELECT employee_id INTO contract_employee FROM hr_employeecontract WHERE id = NEW.contract_id;
    IF employee_organization IS DISTINCT FROM run_organization
       OR employee_branch IS DISTINCT FROM run_branch
       OR contract_employee IS DISTINCT FROM NEW.employee_id THEN
        RAISE EXCEPTION 'payroll employee line % crosses run, employee, or contract scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND run_status NOT IN ('DRAFT', 'CALCULATED') THEN
        RAISE EXCEPTION 'frozen payroll employee line % is immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_payroll_employee_scope_and_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_payrollemployeeline
FOR EACH ROW EXECUTE FUNCTION hr_payroll_employee_scope_and_freeze_guard();

CREATE OR REPLACE FUNCTION hr_payroll_component_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE run_status text;
BEGIN
    SELECT run.status INTO run_status
      FROM hr_payrollrun run
      JOIN hr_payrollemployeeline employee_line ON employee_line.payroll_run_id = run.id
     WHERE employee_line.id = COALESCE(NEW.employee_line_id, OLD.employee_line_id);
    IF TG_OP = 'DELETE' THEN
        IF run_status NOT IN ('DRAFT', 'CALCULATED') THEN
            RAISE EXCEPTION 'frozen payroll component % is immutable', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND run_status NOT IN ('DRAFT', 'CALCULATED') THEN
        RAISE EXCEPTION 'frozen payroll component % is immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_payroll_component_freeze
BEFORE INSERT OR UPDATE OR DELETE ON hr_payrollcomponentline
FOR EACH ROW EXECUTE FUNCTION hr_payroll_component_freeze_guard();

CREATE OR REPLACE FUNCTION hr_payroll_reconcile_guard()
RETURNS TRIGGER AS $$
DECLARE run_id bigint; run_row hr_payrollrun%ROWTYPE; employee_count integer;
        gross numeric; deductions numeric; net numeric;
BEGIN
    IF TG_TABLE_NAME = 'hr_payrollrun' THEN
        run_id := NEW.id;
    ELSE
        run_id := NEW.payroll_run_id;
    END IF;
    SELECT * INTO run_row FROM hr_payrollrun WHERE id = run_id;
    IF run_row.status IN ('REVIEWED', 'APPROVED', 'POSTED', 'RELEASED', 'PARTIALLY_PAID', 'PAID') THEN
        SELECT COUNT(*), COALESCE(SUM(gross_pay), 0), COALESCE(SUM(total_deductions), 0), COALESCE(SUM(net_pay), 0)
          INTO employee_count, gross, deductions, net
          FROM hr_payrollemployeeline WHERE payroll_run_id = run_id;
        IF employee_count <> run_row.employee_count
           OR gross <> run_row.gross_total
           OR deductions <> run_row.deduction_total
           OR net <> run_row.net_total THEN
            RAISE EXCEPTION 'payroll run % does not reconcile to employee lines', run_id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER hr_payroll_run_reconciles
AFTER INSERT OR UPDATE ON hr_payrollrun
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION hr_payroll_reconcile_guard();
CREATE CONSTRAINT TRIGGER hr_payroll_line_reconciles
AFTER INSERT OR UPDATE ON hr_payrollemployeeline
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION hr_payroll_reconcile_guard();

CREATE OR REPLACE FUNCTION hr_payroll_payment_scope_guard()
RETURNS TRIGGER AS $$
DECLARE run_organization bigint; run_branch bigint; run_status text; journal_organization bigint;
        original_run bigint; original_amount numeric; original_method text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'payroll payment % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF TG_OP = 'UPDATE' THEN
        IF NEW.status = 'REVERSED'
           AND (to_jsonb(NEW) - ARRAY['status', 'updated_at']) = (to_jsonb(OLD) - ARRAY['status', 'updated_at']) THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'payroll payment % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT organization_id, branch_id, status INTO run_organization, run_branch, run_status
      FROM hr_payrollrun WHERE id = NEW.payroll_run_id FOR UPDATE;
    SELECT organization_id INTO journal_organization
      FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
    IF run_organization IS DISTINCT FROM NEW.organization_id
       OR run_branch IS DISTINCT FROM NEW.branch_id
       OR journal_organization IS DISTINCT FROM NEW.organization_id
       OR run_status NOT IN ('RELEASED', 'PARTIALLY_PAID', 'PAID') THEN
        RAISE EXCEPTION 'payroll payment % crosses scope or run is not released', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.reversal_of_id IS NOT NULL THEN
        SELECT payroll_run_id, amount, method INTO original_run, original_amount, original_method
          FROM hr_payrollpayment WHERE id = NEW.reversal_of_id;
        IF original_run IS DISTINCT FROM NEW.payroll_run_id
           OR original_amount IS DISTINCT FROM NEW.amount
           OR original_method IS DISTINCT FROM NEW.method THEN
            RAISE EXCEPTION 'payroll payment reversal must exactly mirror its original'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_payroll_payment_scope
BEFORE INSERT OR UPDATE OR DELETE ON hr_payrollpayment
FOR EACH ROW EXECUTE FUNCTION hr_payroll_payment_scope_guard();

CREATE OR REPLACE FUNCTION hr_payroll_allocation_guard()
RETURNS TRIGGER AS $$
DECLARE payment_run bigint; line_run bigint; payment_reversal bigint;
        line_net numeric; already_paid numeric; signed_amount numeric;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'payroll payment allocation % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT payroll_run_id, reversal_of_id INTO payment_run, payment_reversal
      FROM hr_payrollpayment WHERE id = NEW.payment_id;
    SELECT payroll_run_id, net_pay INTO line_run, line_net
      FROM hr_payrollemployeeline WHERE id = NEW.employee_line_id FOR UPDATE;
    SELECT COALESCE(SUM(CASE WHEN payment.reversal_of_id IS NULL THEN allocation.amount ELSE -allocation.amount END), 0)
      INTO already_paid
      FROM hr_payrollpaymentallocation allocation
      JOIN hr_payrollpayment payment ON payment.id = allocation.payment_id
     WHERE allocation.employee_line_id = NEW.employee_line_id;
    signed_amount := CASE WHEN payment_reversal IS NULL THEN NEW.amount ELSE -NEW.amount END;
    IF payment_run IS DISTINCT FROM line_run
       OR already_paid + signed_amount > line_net
       OR already_paid + signed_amount < 0 THEN
        RAISE EXCEPTION 'payroll allocation crosses run or exceeds employee outstanding pay'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER hr_payroll_allocation_append_only
BEFORE INSERT OR UPDATE OR DELETE ON hr_payrollpaymentallocation
FOR EACH ROW EXECUTE FUNCTION hr_payroll_allocation_guard();

CREATE OR REPLACE FUNCTION hr_payroll_payment_total_guard()
RETURNS TRIGGER AS $$
DECLARE target_payment_id bigint; expected numeric; allocated numeric;
BEGIN
    IF TG_TABLE_NAME = 'hr_payrollpayment' THEN
        target_payment_id := NEW.id;
    ELSE
        target_payment_id := NEW.payment_id;
    END IF;
    SELECT amount INTO expected FROM hr_payrollpayment WHERE id = target_payment_id;
    SELECT COALESCE(SUM(amount), 0) INTO allocated
      FROM hr_payrollpaymentallocation WHERE payment_id = target_payment_id;
    IF expected IS NOT NULL AND allocated <> expected THEN
        RAISE EXCEPTION 'payroll payment % allocations do not equal payment amount', target_payment_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER hr_payroll_payment_allocations_equal
AFTER INSERT ON hr_payrollpayment
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION hr_payroll_payment_total_guard();
CREATE CONSTRAINT TRIGGER hr_payroll_allocation_total_equal
AFTER INSERT ON hr_payrollpaymentallocation
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION hr_payroll_payment_total_guard();
"""

DROP_PAYROLL_GUARDS = r"""
DROP TRIGGER IF EXISTS hr_payroll_allocation_total_equal ON hr_payrollpaymentallocation;
DROP TRIGGER IF EXISTS hr_payroll_payment_allocations_equal ON hr_payrollpayment;
DROP FUNCTION IF EXISTS hr_payroll_payment_total_guard();
DROP TRIGGER IF EXISTS hr_payroll_allocation_append_only ON hr_payrollpaymentallocation;
DROP FUNCTION IF EXISTS hr_payroll_allocation_guard();
DROP TRIGGER IF EXISTS hr_payroll_payment_scope ON hr_payrollpayment;
DROP FUNCTION IF EXISTS hr_payroll_payment_scope_guard();
DROP TRIGGER IF EXISTS hr_payroll_line_reconciles ON hr_payrollemployeeline;
DROP TRIGGER IF EXISTS hr_payroll_run_reconciles ON hr_payrollrun;
DROP FUNCTION IF EXISTS hr_payroll_reconcile_guard();
DROP TRIGGER IF EXISTS hr_payroll_component_freeze ON hr_payrollcomponentline;
DROP FUNCTION IF EXISTS hr_payroll_component_freeze_guard();
DROP TRIGGER IF EXISTS hr_payroll_employee_scope_and_freeze ON hr_payrollemployeeline;
DROP FUNCTION IF EXISTS hr_payroll_employee_scope_and_freeze_guard();
DROP TRIGGER IF EXISTS hr_payroll_run_scope_and_freeze ON hr_payrollrun;
DROP FUNCTION IF EXISTS hr_payroll_run_scope_and_freeze_guard();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0022_alter_accountrole_domain_and_more"),
        ("hr", "0003_employeeadvance_advancerecoveryallocation_and_more"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPayrollRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("run_number", models.CharField(max_length=48)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("accounting_date", models.DateField()),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("currency", models.CharField(default="IQD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("CALCULATED", "محسوب"),
                            ("REVIEWED", "تمت مراجعته"),
                            ("APPROVED", "معتمد"),
                            ("POSTED", "مرحّل محاسبياً"),
                            ("RELEASED", "مطلق للصرف"),
                            ("PARTIALLY_PAID", "مصروف جزئياً"),
                            ("PAID", "مصروف بالكامل"),
                            ("REVERSED", "معكوس"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "basic_pay_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "allowance_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "overtime_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "reward_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "deduction_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payroll run",
                "verbose_name_plural": "historical payroll runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PayrollComponentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BASIC", "أجر أساسي"),
                            ("FIXED_ALLOWANCE", "بدل ثابت"),
                            ("VARIABLE_ALLOWANCE", "بدل متغير"),
                            ("OVERTIME", "عمل إضافي"),
                            ("REWARD", "مكافأة"),
                            ("ABSENCE", "غياب"),
                            ("LATENESS", "تأخر"),
                            ("EARLY_DEPARTURE", "انصراف مبكر"),
                            ("DEDUCTION", "استقطاع"),
                            ("ADVANCE_RECOVERY", "استرداد سلفة"),
                        ],
                        max_length=24,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("label_ar", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=18),
                ),
                (
                    "multiplier",
                    models.DecimalField(decimal_places=6, default=Decimal("1"), max_digits=12),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=18)),
                ("is_deduction", models.BooleanField(default=False)),
                ("source_type", models.CharField(blank=True, max_length=80)),
                ("source_id", models.CharField(blank=True, max_length=80)),
                ("source_snapshot", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["employee_line__employee_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollEmployeeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("contract_version", models.PositiveIntegerField()),
                ("employee_code", models.CharField(max_length=40)),
                ("employee_name_ar", models.CharField(max_length=200)),
                ("job_title", models.CharField(max_length=120)),
                (
                    "wage_basis",
                    models.CharField(
                        choices=[("MONTHLY", "شهري"), ("DAILY", "يومي"), ("HOURLY", "بالساعة")],
                        max_length=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "نقداً"), ("BANK", "تحويل مصرفي")], max_length=12
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=160)),
                ("basic_salary_snapshot", models.DecimalField(decimal_places=3, max_digits=18)),
                (
                    "scheduled_days",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=10),
                ),
                ("scheduled_minutes", models.PositiveIntegerField(default=0)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("paid_leave_minutes", models.PositiveIntegerField(default=0)),
                ("unpaid_leave_minutes", models.PositiveIntegerField(default=0)),
                ("absence_minutes", models.PositiveIntegerField(default=0)),
                ("lateness_minutes", models.PositiveIntegerField(default=0)),
                ("early_departure_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                (
                    "basic_pay",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "fixed_allowances",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "variable_allowances",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "rewards",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "absence_deduction",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "lateness_deduction",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "early_departure_deduction",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "administrative_deduction",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "advance_recovery",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18),
                ),
                ("gross_pay", models.DecimalField(decimal_places=3, max_digits=18)),
                ("total_deductions", models.DecimalField(decimal_places=3, max_digits=18)),
                ("net_pay", models.DecimalField(decimal_places=3, max_digits=18)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("source_snapshot", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["employee_code"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("payment_number", models.CharField(max_length=48)),
                ("payment_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[("CASH", "نقداً"), ("BANK", "تحويل مصرفي")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=20)),
                ("reference", models.CharField(max_length=200)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("POSTED", "مرحّل"), ("REVERSED", "معكوس")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollPaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("amount", models.DecimalField(decimal_places=3, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("run_number", models.CharField(max_length=48)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("accounting_date", models.DateField()),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("currency", models.CharField(default="IQD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("CALCULATED", "محسوب"),
                            ("REVIEWED", "تمت مراجعته"),
                            ("APPROVED", "معتمد"),
                            ("POSTED", "مرحّل محاسبياً"),
                            ("RELEASED", "مطلق للصرف"),
                            ("PARTIALLY_PAID", "مصروف جزئياً"),
                            ("PAID", "مصروف بالكامل"),
                            ("REVERSED", "معكوس"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "basic_pay_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "allowance_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "overtime_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "reward_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "deduction_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=20),
                ),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-period_end", "branch__code", "-id"],
                "permissions": [
                    ("view_payroll_workspace", "Can view payroll workspace"),
                    ("calculate_payroll", "Can calculate payroll"),
                    ("review_payroll", "Can review payroll"),
                    ("approve_payroll", "Can approve payroll"),
                    ("post_payroll", "Can post or reverse payroll"),
                    ("pay_payroll", "Can pay payroll"),
                    ("view_payroll_amounts", "Can view payroll amounts"),
                    ("view_employee_statement", "Can view employee statements"),
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="payrollpolicy",
            name="hr_payroll_policy_values_valid",
        ),
        migrations.AddField(
            model_name="historicalpayrollpolicy",
            name="absence_multiplier",
            field=models.DecimalField(decimal_places=3, default=Decimal("1.000"), max_digits=8),
        ),
        migrations.AddField(
            model_name="historicalpayrollpolicy",
            name="deduct_early_departure",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalpayrollpolicy",
            name="deduct_lateness",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalpayrollpolicy",
            name="unpaid_leave_multiplier",
            field=models.DecimalField(decimal_places=3, default=Decimal("1.000"), max_digits=8),
        ),
        migrations.AddField(
            model_name="payrollpolicy",
            name="absence_multiplier",
            field=models.DecimalField(decimal_places=3, default=Decimal("1.000"), max_digits=8),
        ),
        migrations.AddField(
            model_name="payrollpolicy",
            name="deduct_early_departure",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="payrollpolicy",
            name="deduct_lateness",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="payrollpolicy",
            name="unpaid_leave_multiplier",
            field=models.DecimalField(decimal_places=3, default=Decimal("1.000"), max_digits=8),
        ),
        migrations.AddConstraint(
            model_name="payrollpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("money_rounding__gt", 0),
                    ("hour_rounding__gt", 0),
                    ("overtime_multiplier__gte", 0),
                    ("deduction_cap_percentage__gte", 0),
                    ("absence_multiplier__gte", 0),
                    ("unpaid_leave_multiplier__gte", 0),
                ),
                name="hr_payroll_policy_values_valid",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="accrual_journal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="calculated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="hr.payrollpolicy",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="reversal_journal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollemployeeline",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_lines",
                to="hr.employeecontract",
            ),
        ),
        migrations.AddField(
            model_name="payrollemployeeline",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_lines",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="payrollcomponentline",
            name="employee_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                to="hr.payrollemployeeline",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_payments",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_payroll_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_payments",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_payments",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="hr.payrollpayment",
            ),
        ),
        migrations.AddField(
            model_name="payrollpaymentallocation",
            name="employee_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_allocations",
                to="hr.payrollemployeeline",
            ),
        ),
        migrations.AddField(
            model_name="payrollpaymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="hr.payrollpayment",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="accrual_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_accrual_runs",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_runs",
                to="organizations.branch",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="calculated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calculated_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_runs",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_runs",
                to="hr.payrollpolicy",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posted_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="released_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="reversal_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_payroll_runs",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_payroll_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payrollpayment",
            name="payroll_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="hr.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="payrollemployeeline",
            name="payroll_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_lines",
                to="hr.payrollrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollcomponentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="hr_payroll_component_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollpaymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "employee_line"), name="hr_payroll_payment_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollpaymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="hr_payroll_payment_allocation_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "run_number"), name="hr_payroll_run_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "REVERSED"), _negated=True),
                fields=("organization", "branch", "period_start", "period_end"),
                name="hr_payroll_live_period_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="hr_payroll_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("basic_pay_total__gte", 0),
                    ("allowance_total__gte", 0),
                    ("overtime_total__gte", 0),
                    ("reward_total__gte", 0),
                    ("gross_total__gte", 0),
                    ("deduction_total__gte", 0),
                    ("net_total__gte", 0),
                    (
                        "net_total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("gross_total"), "-", models.F("deduction_total")
                        ),
                    ),
                ),
                name="hr_payroll_run_totals_reconcile",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollpayment",
            constraint=models.UniqueConstraint(
                fields=("organization", "payment_number"), name="hr_payroll_payment_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollpayment",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="hr_payroll_payment_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="hr_payroll_payment_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollemployeeline",
            constraint=models.UniqueConstraint(
                fields=("payroll_run", "employee"), name="hr_payroll_employee_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollemployeeline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("basic_pay__gte", 0),
                    ("fixed_allowances__gte", 0),
                    ("variable_allowances__gte", 0),
                    ("overtime_pay__gte", 0),
                    ("rewards__gte", 0),
                    ("gross_pay__gte", 0),
                    ("total_deductions__gte", 0),
                    ("net_pay__gte", 0),
                    (
                        "net_pay",
                        django.db.models.expressions.CombinedExpression(
                            models.F("gross_pay"), "-", models.F("total_deductions")
                        ),
                    ),
                ),
                name="hr_payroll_employee_totals_reconcile",
            ),
        ),
        migrations.RunSQL(sql=PAYROLL_GUARDS, reverse_sql=DROP_PAYROLL_GUARDS),
    ]
