# Generated by Django 5.2.17 on 2026-08-19 22:52

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

PAYROLL_REVERSAL_GUARDS = r"""
CREATE OR REPLACE FUNCTION hr_payroll_run_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE branch_organization bigint; policy_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'payroll run % cannot be deleted after calculation', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO branch_organization FROM organizations_branch WHERE id = NEW.branch_id;
    SELECT organization_id INTO policy_organization FROM hr_payrollpolicy WHERE id = NEW.policy_id;
    IF branch_organization IS DISTINCT FROM NEW.organization_id
       OR policy_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'payroll run % crosses branch, policy, or organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status IN ('REVIEWED', 'APPROVED', 'POSTED', 'RELEASED', 'PARTIALLY_PAID', 'PAID', 'REVERSED')
       AND (to_jsonb(NEW) - ARRAY['status', 'reviewed_by_id', 'reviewed_at', 'approved_by_id', 'approved_at', 'posted_by_id', 'posted_at', 'released_by_id', 'released_at', 'paid_at', 'rejection_reason', 'accrual_journal_id', 'reversal_journal_id', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'reviewed_by_id', 'reviewed_at', 'approved_by_id', 'approved_at', 'posted_by_id', 'posted_at', 'released_by_id', 'released_at', 'paid_at', 'rejection_reason', 'accrual_journal_id', 'reversal_journal_id', 'updated_at']) THEN
        RAISE EXCEPTION 'reviewed payroll run % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_deduction_allocation_append_guard()
RETURNS TRIGGER AS $$
DECLARE approved numeric; allocated numeric; parent_status text; signed_amount numeric;
        deduction_organization bigint; journal_organization bigint; run_organization bigint;
        original_deduction bigint; original_amount numeric; original_reversal bigint; original_run bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'deduction allocation % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT approved_amount, status, organization_id
      INTO approved, parent_status, deduction_organization
      FROM hr_employeededuction WHERE id = NEW.deduction_id FOR UPDATE;
    IF parent_status IS DISTINCT FROM 'APPROVED' THEN
        RAISE EXCEPTION 'only an approved deduction can be allocated'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM deduction_organization THEN
            RAISE EXCEPTION 'deduction allocation journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.payroll_run_id IS NOT NULL THEN
        SELECT organization_id INTO run_organization FROM hr_payrollrun WHERE id = NEW.payroll_run_id;
        IF run_organization IS DISTINCT FROM deduction_organization THEN
            RAISE EXCEPTION 'deduction allocation payroll run crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.reversal_of_id IS NOT NULL THEN
        SELECT deduction_id, amount, reversal_of_id, payroll_run_id
          INTO original_deduction, original_amount, original_reversal, original_run
          FROM hr_deductionallocation WHERE id = NEW.reversal_of_id;
        IF original_deduction IS DISTINCT FROM NEW.deduction_id
           OR original_amount IS DISTINCT FROM NEW.amount
           OR original_reversal IS NOT NULL
           OR original_run IS DISTINCT FROM NEW.payroll_run_id THEN
            RAISE EXCEPTION 'deduction reversal must exactly mirror its original allocation'
                USING ERRCODE = 'check_violation';
        END IF;
        signed_amount := -NEW.amount;
    ELSE
        signed_amount := NEW.amount;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO allocated FROM hr_deductionallocation WHERE deduction_id = NEW.deduction_id;
    IF allocated + signed_amount > approved OR allocated + signed_amount < 0 THEN
        RAISE EXCEPTION 'deduction allocation exceeds or reverses beyond the approved balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_advance_recovery_append_guard()
RETURNS TRIGGER AS $$
DECLARE disbursed numeric; recovered numeric; signed_amount numeric;
        journal_organization bigint; advance_organization bigint; run_organization bigint;
        original_advance bigint; original_amount numeric; original_reversal bigint; original_run bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'advance recovery % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT organization_id INTO advance_organization
      FROM hr_employeeadvance WHERE id = NEW.advance_id FOR UPDATE;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance recovery journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.payroll_run_id IS NOT NULL THEN
        SELECT organization_id INTO run_organization FROM hr_payrollrun WHERE id = NEW.payroll_run_id;
        IF run_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance recovery payroll run crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.reversal_of_id IS NOT NULL THEN
        SELECT advance_id, amount, reversal_of_id, payroll_run_id
          INTO original_advance, original_amount, original_reversal, original_run
          FROM hr_advancerecoveryallocation WHERE id = NEW.reversal_of_id;
        IF original_advance IS DISTINCT FROM NEW.advance_id
           OR original_amount IS DISTINCT FROM NEW.amount
           OR original_reversal IS NOT NULL
           OR original_run IS DISTINCT FROM NEW.payroll_run_id THEN
            RAISE EXCEPTION 'advance recovery reversal must exactly mirror its original allocation'
                USING ERRCODE = 'check_violation';
        END IF;
        signed_amount := -NEW.amount;
    ELSE
        signed_amount := NEW.amount;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO disbursed FROM hr_advancedisbursement WHERE advance_id = NEW.advance_id;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO recovered FROM hr_advancerecoveryallocation WHERE advance_id = NEW.advance_id;
    IF recovered + signed_amount > disbursed OR recovered + signed_amount < 0 THEN
        RAISE EXCEPTION 'advance recovery exceeds or reverses beyond the disbursed balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_advance_disbursement_append_guard()
RETURNS TRIGGER AS $$
DECLARE principal numeric; disbursed numeric; recovered numeric; parent_status text;
        journal_organization bigint; advance_organization bigint; original_amount numeric;
        original_advance bigint; signed_amount numeric;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'advance disbursement % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT principal_amount, status, organization_id
      INTO principal, parent_status, advance_organization
      FROM hr_employeeadvance WHERE id = NEW.advance_id FOR UPDATE;
    IF parent_status NOT IN ('APPROVED', 'PARTIALLY_DISBURSED', 'DISBURSED') THEN
        RAISE EXCEPTION 'only an approved advance can be disbursed'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance disbursement journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.reversal_of_id IS NOT NULL THEN
        SELECT amount, advance_id INTO original_amount, original_advance
          FROM hr_advancedisbursement WHERE id = NEW.reversal_of_id;
        IF original_advance IS DISTINCT FROM NEW.advance_id OR original_amount IS DISTINCT FROM NEW.amount THEN
            RAISE EXCEPTION 'advance reversal must exactly reverse a disbursement from the same advance'
                USING ERRCODE = 'check_violation';
        END IF;
        signed_amount := -NEW.amount;
    ELSE
        signed_amount := NEW.amount;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO disbursed FROM hr_advancedisbursement WHERE advance_id = NEW.advance_id;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO recovered FROM hr_advancerecoveryallocation WHERE advance_id = NEW.advance_id;
    IF disbursed + signed_amount > principal OR disbursed + signed_amount < recovered THEN
        RAISE EXCEPTION 'advance disbursement exceeds principal or falls below recovered balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_payroll_payment_total_guard()
RETURNS TRIGGER AS $$
DECLARE target_payment_id bigint; expected numeric; allocated numeric;
BEGIN
    IF TG_TABLE_NAME = 'hr_payrollpayment' THEN
        target_payment_id := NEW.id;
    ELSE
        target_payment_id := NEW.payment_id;
    END IF;
    SELECT amount INTO expected FROM hr_payrollpayment WHERE id = target_payment_id;
    SELECT COALESCE(SUM(amount), 0) INTO allocated
      FROM hr_payrollpaymentallocation WHERE payment_id = target_payment_id;
    IF expected IS NOT NULL AND allocated <> expected THEN
        RAISE EXCEPTION 'payroll payment % allocations do not equal payment amount', target_payment_id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


PAYROLL_REVERSAL_GUARDS_ROLLBACK = r"""
CREATE OR REPLACE FUNCTION hr_payroll_run_scope_and_freeze_guard()
RETURNS TRIGGER AS $$
DECLARE branch_organization bigint; policy_organization bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'payroll run % cannot be deleted after calculation', OLD.id
                USING ERRCODE = 'restrict_violation';
        END IF;
        RETURN OLD;
    END IF;
    SELECT organization_id INTO branch_organization FROM organizations_branch WHERE id = NEW.branch_id;
    SELECT organization_id INTO policy_organization FROM hr_payrollpolicy WHERE id = NEW.policy_id;
    IF branch_organization IS DISTINCT FROM NEW.organization_id
       OR policy_organization IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION 'payroll run % crosses branch, policy, or organization scope', COALESCE(NEW.id, 0)
            USING ERRCODE = 'check_violation';
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.status IN ('REVIEWED', 'APPROVED', 'POSTED', 'RELEASED', 'PARTIALLY_PAID', 'PAID', 'REVERSED')
       AND (to_jsonb(NEW) - ARRAY['status', 'reviewed_by_id', 'reviewed_at', 'approved_by_id', 'approved_at', 'posted_by_id', 'posted_at', 'released_by_id', 'released_at', 'rejection_reason', 'accrual_journal_id', 'reversal_journal_id', 'updated_at'])
           <> (to_jsonb(OLD) - ARRAY['status', 'reviewed_by_id', 'reviewed_at', 'approved_by_id', 'approved_at', 'posted_by_id', 'posted_at', 'released_by_id', 'released_at', 'rejection_reason', 'accrual_journal_id', 'reversal_journal_id', 'updated_at']) THEN
        RAISE EXCEPTION 'reviewed payroll run % is structurally immutable', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_deduction_allocation_append_guard()
RETURNS TRIGGER AS $$
DECLARE approved numeric; allocated numeric; parent_status text;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'deduction allocation % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT approved_amount, status INTO approved, parent_status
      FROM hr_employeededuction WHERE id = NEW.deduction_id FOR UPDATE;
    SELECT COALESCE(SUM(amount), 0) INTO allocated
      FROM hr_deductionallocation WHERE deduction_id = NEW.deduction_id;
    IF parent_status IS DISTINCT FROM 'APPROVED' OR allocated + NEW.amount > approved THEN
        RAISE EXCEPTION 'deduction allocation exceeds the approved balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_advance_recovery_append_guard()
RETURNS TRIGGER AS $$
DECLARE disbursed numeric; recovered numeric; journal_organization bigint; advance_organization bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'advance recovery % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT organization_id INTO advance_organization
      FROM hr_employeeadvance WHERE id = NEW.advance_id FOR UPDATE;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance recovery journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO disbursed FROM hr_advancedisbursement WHERE advance_id = NEW.advance_id;
    SELECT COALESCE(SUM(amount), 0) INTO recovered
      FROM hr_advancerecoveryallocation WHERE advance_id = NEW.advance_id;
    IF recovered + NEW.amount > disbursed THEN
        RAISE EXCEPTION 'advance recovery exceeds the disbursed balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION hr_advance_disbursement_append_guard()
RETURNS TRIGGER AS $$
DECLARE principal numeric; disbursed numeric; recovered numeric; parent_status text;
        journal_organization bigint; advance_organization bigint; original_amount numeric;
        original_advance bigint; signed_amount numeric;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'advance disbursement % is append-only', OLD.id
            USING ERRCODE = 'restrict_violation';
    END IF;
    SELECT principal_amount, status, organization_id
      INTO principal, parent_status, advance_organization
      FROM hr_employeeadvance WHERE id = NEW.advance_id FOR UPDATE;
    IF parent_status NOT IN ('APPROVED', 'PARTIALLY_DISBURSED', 'DISBURSED') THEN
        RAISE EXCEPTION 'only an approved advance can be disbursed'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.journal_entry_id IS NOT NULL THEN
        SELECT organization_id INTO journal_organization
          FROM accounting_journalentry WHERE id = NEW.journal_entry_id;
        IF journal_organization IS DISTINCT FROM advance_organization THEN
            RAISE EXCEPTION 'advance disbursement journal crosses organization scope'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    IF NEW.reversal_of_id IS NOT NULL THEN
        SELECT amount, advance_id INTO original_amount, original_advance
          FROM hr_advancedisbursement WHERE id = NEW.reversal_of_id;
        IF original_advance IS DISTINCT FROM NEW.advance_id OR original_amount IS DISTINCT FROM NEW.amount THEN
            RAISE EXCEPTION 'advance reversal must exactly reverse a disbursement from the same advance'
                USING ERRCODE = 'check_violation';
        END IF;
        signed_amount := -NEW.amount;
    ELSE
        signed_amount := NEW.amount;
    END IF;
    SELECT COALESCE(SUM(CASE WHEN reversal_of_id IS NULL THEN amount ELSE -amount END), 0)
      INTO disbursed FROM hr_advancedisbursement WHERE advance_id = NEW.advance_id;
    SELECT COALESCE(SUM(amount), 0) INTO recovered
      FROM hr_advancerecoveryallocation WHERE advance_id = NEW.advance_id;
    IF disbursed + signed_amount > principal OR disbursed + signed_amount < recovered THEN
        RAISE EXCEPTION 'advance disbursement exceeds principal or falls below recovered balance'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0022_alter_accountrole_domain_and_more"),
        ("hr", "0004_historicalpayrollrun_payrollcomponentline_and_more"),
        ("organizations", "0004_inventory_master_data_and_warehouse_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advancerecoveryallocation",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advance_recovery_allocations",
                to="hr.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="advancerecoveryallocation",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="hr.advancerecoveryallocation",
            ),
        ),
        migrations.AddField(
            model_name="deductionallocation",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_deduction_allocations",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="deductionallocation",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deduction_allocations",
                to="hr.payrollrun",
            ),
        ),
        migrations.AddField(
            model_name="deductionallocation",
            name="reversal_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="hr.deductionallocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayrollrun",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalPayrollPayment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="updated at"),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("payment_number", models.CharField(max_length=48)),
                ("payment_date", models.DateField()),
                (
                    "method",
                    models.CharField(
                        choices=[("CASH", "نقداً"), ("BANK", "تحويل مصرفي")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=20)),
                ("reference", models.CharField(max_length=200)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("POSTED", "مرحّل"), ("REVERSED", "معكوس")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.payrollrun",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="hr.payrollpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payroll payment",
                "verbose_name_plural": "historical payroll payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunSQL(
            PAYROLL_REVERSAL_GUARDS,
            PAYROLL_REVERSAL_GUARDS_ROLLBACK,
        ),
    ]
