# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalleavetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalpayrollpolicy',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='payrollpolicy',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='name_en',
        ),
    ]
