# Generated by Django 5.2.17 on 2026-08-31 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0012_drop_access_change_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('scope_key', models.CharField(max_length=200, verbose_name='scope key')),
                ('detector_code', models.CharField(max_length=100, verbose_name='detector code')),
                ('fingerprint', models.CharField(max_length=300, verbose_name='fingerprint')),
                ('domain', models.CharField(choices=[('DATA_QUALITY', 'جودة البيانات'), ('INVENTORY', 'المخزون'), ('PROCUREMENT', 'المشتريات'), ('SALES', 'المبيعات'), ('KITCHEN', 'المطبخ والكلفة'), ('ACCOUNTING', 'المحاسبة'), ('HR', 'الموارد البشرية'), ('CONDUCT', 'سلوك الاستخدام')], max_length=20, verbose_name='domain')),
                ('sensitivity', models.CharField(choices=[('OPERATIONAL', 'تشغيلية'), ('FINANCIAL', 'مالية'), ('HR_RESTRICTED', 'مقيّدة — موارد بشرية')], default='OPERATIONAL', max_length=20, verbose_name='sensitivity')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='organizations.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insights', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'insight',
                'verbose_name_plural': 'insights',
                'ordering': ['-created_at', '-id'],
                'permissions': [('manage_insight', 'Can acknowledge, dismiss and reopen a finding'), ('run_insights', 'Can start an analysis run'), ('configure_insights', 'Can change detector thresholds')],
            },
        ),
        migrations.CreateModel(
            name='InsightRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('requested_detectors', models.JSONField(default=list, verbose_name='requested detectors')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end (exclusive)')),
                ('trigger', models.CharField(choices=[('MANUAL', 'يدوي'), ('SCHEDULED', 'مجدول')], default='MANUAL', max_length=16, verbose_name='trigger')),
                ('settings_version', models.PositiveIntegerField(default=0, verbose_name='settings version')),
                ('source_cutoffs', models.JSONField(default=dict, verbose_name='source cutoffs')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('actor', models.ForeignKey(blank=True, help_text='فارغ للتشغيل المجدول.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_runs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_runs', to='organizations.branch', verbose_name='branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insight_runs', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'insight run',
                'verbose_name_plural': 'insight runs',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InsightObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end (exclusive)')),
                ('source_cutoffs', models.JSONField(default=dict, verbose_name='source cutoffs')),
                ('detector_version', models.CharField(max_length=32, verbose_name='detector version')),
                ('settings_version', models.PositiveIntegerField(default=0, verbose_name='settings version')),
                ('severity', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية'), ('CRITICAL', 'حرجة')], max_length=16, verbose_name='severity')),
                ('confidence', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'عالية')], max_length=16, verbose_name='confidence')),
                ('coverage', models.CharField(choices=[('COMPLETE', 'كاملة'), ('PARTIAL', 'جزئية'), ('INSUFFICIENT', 'غير كافية')], max_length=16, verbose_name='coverage')),
                ('title_ar', models.CharField(max_length=240, verbose_name='title')),
                ('narrative_ar', models.TextField(verbose_name='narrative')),
                ('recommendation_ar', models.TextField(verbose_name='recommendation')),
                ('evidence', models.JSONField(default=dict, verbose_name='evidence')),
                ('observed_at', models.DateTimeField(verbose_name='observed at')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='insights.insight', verbose_name='insight')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='insights.insightrun', verbose_name='run')),
            ],
            options={
                'verbose_name': 'insight observation',
                'verbose_name_plural': 'insight observations',
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InsightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_type', models.CharField(choices=[('OPENED', 'فُتحت'), ('ACKNOWLEDGED', 'جرى الاطلاع'), ('RESOLVED', 'انتهت'), ('DISMISSED', 'صُرف النظر'), ('REOPENED', 'أُعيد فتحها')], max_length=20, verbose_name='event type')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('occurred_at', models.DateTimeField(verbose_name='occurred at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insight_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='insights.insight', verbose_name='insight')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='insights.insightrun', verbose_name='run')),
            ],
            options={
                'verbose_name': 'insight event',
                'verbose_name_plural': 'insight events',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InsightDetectorOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('detector_code', models.CharField(max_length=100, verbose_name='detector code')),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'نجح'), ('SKIPPED', 'تُخطّي'), ('FAILED', 'أخفق')], max_length=16, verbose_name='outcome')),
                ('coverage', models.CharField(choices=[('COMPLETE', 'كاملة'), ('PARTIAL', 'جزئية'), ('INSUFFICIENT', 'غير كافية')], max_length=16, verbose_name='coverage')),
                ('evaluated_fingerprints', models.JSONField(default=list, verbose_name='evaluated fingerprints')),
                ('evaluated_scope_count', models.PositiveIntegerField(default=0, verbose_name='evaluated scopes')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='candidates')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='error code')),
                ('error_summary', models.CharField(blank=True, max_length=300, verbose_name='error summary')),
                ('notes', models.JSONField(default=dict, verbose_name='limitations')),
                ('finished_at', models.DateTimeField(verbose_name='finished at')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='insights.insightrun', verbose_name='run')),
            ],
            options={
                'verbose_name': 'insight detector outcome',
                'verbose_name_plural': 'insight detector outcomes',
                'ordering': ['run', 'detector_code'],
            },
        ),
        migrations.AddField(
            model_name='insight',
            name='first_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_insights', to='insights.insightrun', verbose_name='first run'),
        ),
        migrations.CreateModel(
            name='DetectorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('detector_code', models.CharField(max_length=100, verbose_name='detector code')),
                ('version', models.PositiveIntegerField(verbose_name='version')),
                ('payload', models.JSONField(default=dict, verbose_name='settings')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detector_settings', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detector_settings', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'detector setting',
                'verbose_name_plural': 'detector settings',
                'ordering': ['organization', 'detector_code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'detector_code', 'version'), name='insights_setting_version_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='insightrun',
            index=models.Index(fields=['organization', '-started_at'], name='insights_run_org_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='insightrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='insights_run_period_is_half_open'),
        ),
        migrations.AddIndex(
            model_name='insightobservation',
            index=models.Index(fields=['insight', '-observed_at'], name='insights_obs_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='insightobservation',
            constraint=models.UniqueConstraint(fields=('insight', 'run'), name='insights_observation_unique_per_run'),
        ),
        migrations.AddConstraint(
            model_name='insightobservation',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='insights_observation_period_is_half_open'),
        ),
        migrations.AddIndex(
            model_name='insightevent',
            index=models.Index(fields=['insight', '-occurred_at'], name='insights_event_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='insightevent',
            constraint=models.CheckConstraint(condition=models.Q(('actor__isnull', False), ('run__isnull', False), _connector='OR'), name='insights_event_has_an_origin'),
        ),
        migrations.AddConstraint(
            model_name='insightevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['DISMISSED', 'REOPENED']), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='insights_event_decision_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='insightdetectoroutcome',
            constraint=models.UniqueConstraint(fields=('run', 'detector_code'), name='insights_outcome_unique_per_run'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['organization', 'detector_code'], name='insights_org_detector_idx'),
        ),
        migrations.AddConstraint(
            model_name='insight',
            constraint=models.UniqueConstraint(fields=('organization', 'detector_code', 'fingerprint'), name='insights_identity_unique'),
        ),
    ]
