# Generated by Django 5.2.17 on 2026-08-07 23:51

import apps.organizations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]*$')), name='organization_code_format'), models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='organization_names_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='name (English)')),
                ('timezone', models.CharField(default='Asia/Baghdad', help_text="IANA timezone in which this branch's operating day is measured.", max_length=64, validators=[apps.organizations.models.validate_timezone], verbose_name='timezone')),
                ('business_day_start_time', models.TimeField(help_text='The operating day runs 24 hours from this local time. A sale after midnight belongs to the day that started the previous morning.', verbose_name='business day start time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['organization__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('OWNER', 'مالك'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.branch', verbose_name='branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'branch membership',
                'verbose_name_plural': 'branch memberships',
                'ordering': ['branch__code', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='membership_unique_per_user_and_branch')],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='branch_code_unique_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9][A-Z0-9_-]*$')), name='branch_code_format'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name_ar', ''), _negated=True), models.Q(('name_en', ''), _negated=True)), name='branch_names_not_empty'),
        ),
    ]
