# Generated by Django 5.2.17 on 2026-08-08 22:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_historicalbranch_historicalbranchmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'مالك'), ('ACCOUNTING_MANAGER', 'مدير الحسابات'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='historicalbranchmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'مالك'), ('ACCOUNTING_MANAGER', 'مدير الحسابات'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='HistoricalOrganizationMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('role', models.CharField(choices=[('OWNER', 'مالك'), ('ACCOUNTING_MANAGER', 'مدير الحسابات'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'historical organization membership',
                'verbose_name_plural': 'historical organization memberships',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('OWNER', 'مالك'), ('ACCOUNTING_MANAGER', 'مدير الحسابات'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organization membership',
                'verbose_name_plural': 'organization memberships',
                'ordering': ['organization__code', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='org_membership_unique_per_user_and_organization')],
            },
        ),
    ]
