# Generated by Django 5.2.17 on 2026-08-09 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_inventory_master_data_and_warehouse_scope'),
        ('organizations', '0003_task_0_7_permissions_and_source_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmembership',
            name='warehouse_scope_mode',
            field=models.CharField(choices=[('ALL', 'كل المخازن'), ('SELECTED', 'مخازن محددة')], default='ALL', max_length=10, verbose_name='warehouse scope'),
        ),
        migrations.AddField(
            model_name='historicalbranchmembership',
            name='warehouse_scope_mode',
            field=models.CharField(choices=[('ALL', 'كل المخازن'), ('SELECTED', 'مخازن محددة')], default='ALL', max_length=10, verbose_name='warehouse scope'),
        ),
        migrations.CreateModel(
            name='BranchMembershipWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_scopes', to='organizations.branchmembership', verbose_name='branch membership')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_scopes', to='inventory.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'branch membership warehouse',
                'verbose_name_plural': 'branch membership warehouses',
                'ordering': ['branch_membership_id', 'warehouse__code'],
                'constraints': [models.UniqueConstraint(fields=('branch_membership', 'warehouse'), name='branch_membership_warehouse_unique')],
            },
        ),
    ]
