# Generated by Django 5.2.17 on 2026-08-23 02:23

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0004_inventory_master_data_and_warehouse_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmembership',
            name='role',
            field=models.CharField(max_length=64, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='historicalbranchmembership',
            name='role',
            field=models.CharField(max_length=64, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='historicalorganizationmembership',
            name='role',
            field=models.CharField(max_length=64, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(max_length=64, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='HistoricalRoleDefinition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('code', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]*$', 'الرمز بحروف لاتينية صغيرة وأرقام وشرطات فقط، ويبدأ بحرف أو رقم.')], verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('based_on', models.CharField(blank=True, choices=[('OWNER', 'مالك'), ('ACCOUNTING_MANAGER', 'مدير الحسابات'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='based on')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'historical role definition',
                'verbose_name_plural': 'historical role definitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=24, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]*$', 'الرمز بحروف لاتينية صغيرة وأرقام وشرطات فقط، ويبدأ بحرف أو رقم.')], verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('based_on', models.CharField(blank=True, choices=[('OWNER', 'مالك'), ('ACCOUNTING_MANAGER', 'مدير الحسابات'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب'), ('PURCHASING', 'مسؤول مشتريات'), ('STOREKEEPER', 'أمين مخزن'), ('CASHIER', 'أمين صندوق'), ('VIEWER', 'مطّلع')], max_length=20, verbose_name='based on')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_definitions', to='organizations.organization', verbose_name='organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='role_definitions', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'role definition',
                'verbose_name_plural': 'role definitions',
                'ordering': ['organization__code', 'name_ar'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='role_definition_code_unique_per_organization'), models.CheckConstraint(condition=models.Q(('code__regex', '^[a-z0-9][a-z0-9-]*$')), name='role_definition_code_format')],
            },
        ),
    ]
