# Generated by Django 5.2.17 on 2026-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_rename_legacy_name_ar_columns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='branch_names_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='organization',
            name='organization_names_not_empty',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalbranch',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalorganization',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='historicalroledefinition',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='roledefinition',
            name='name_en',
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='branch_names_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='organization_names_not_empty'),
        ),
    ]
