# Generated by Django 5.2.17 on 2026-08-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_branch_name_alter_historicalbranch_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roledefinition',
            options={'ordering': ['organization__code', 'name'], 'verbose_name': 'role definition', 'verbose_name_plural': 'role definitions'},
        ),
    ]
