# Generated by Django 5.2.17 on 2026-08-30 18:17

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop the access-change request workflow.

    Access used to be maker-checker: somebody proposed a grant and a second
    person approved it. In practice the owner was the only approver, every new
    hire waited on them, and the register shows the result — not one branch
    membership was ever granted through it. The manager now assigns posts
    directly on the employee's own screen, bounded by
    `_require_access_administrator` and recorded in the audit log.

    **The rows here are proposals, never authority.** A pending request
    granted nothing; an approved one already wrote its `BranchMembership` or
    `OrganizationMembership`, and those tables are untouched by this
    migration. Dropping this one therefore removes a paper trail of intent,
    not anybody's access — nobody loses a permission when it runs.
    """

    dependencies = [
        ("organizations", "0011_alter_roledefinition_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessChangeRequest",
        ),
    ]
